Repository numba/numba, pull requests merged in 2018-07, with the labels that each got.

#3076 Avoid ignored exception due to missing globals at interpreter teardown
  numba/lowering.py
Labels: 3 - Ready for Review

#3062 Fix cuda.In freeing devary before the kernel launch
  numba/cuda/args.py
  numba/cuda/simulator/kernel.py
Labels: 3 - Ready for Review

#3077 Adds optional number of processes for `-m` in testing
  buildscripts/condarecipe.buildbot/run_test.bat
  buildscripts/condarecipe.buildbot/run_test.sh
  buildscripts/condarecipe.local/run_test.bat
  buildscripts/condarecipe.local/run_test.sh
  buildscripts/incremental/test.cmd
  buildscripts/incremental/test.sh
  numba/testing/main.py
Labels: 3 - Ready for Review

#3091 Remove old recipes, switch to test config based on env var.
  buildscripts/condarecipe.buildbot/bld.bat
  buildscripts/condarecipe.buildbot/build.sh
  buildscripts/condarecipe.buildbot/license.txt
  buildscripts/condarecipe.buildbot/mandel.py
  buildscripts/condarecipe.buildbot/meta.yaml
  buildscripts/condarecipe.buildbot/run_test.bat
  buildscripts/condarecipe.buildbot/run_test.sh
  buildscripts/condarecipe.hsa/bld.bat
  buildscripts/condarecipe.hsa/build.sh
  buildscripts/condarecipe.hsa/custom_condarc
  buildscripts/condarecipe.hsa/license.txt
  buildscripts/condarecipe.hsa/mandel.py
  buildscripts/condarecipe.hsa/meta.yaml
  buildscripts/condarecipe.hsa/run_test.py
  buildscripts/condarecipe.local/run_test.bat
  buildscripts/condarecipe.local/run_test.sh
Labels: 3 - Ready for Review

#3080 Compute np.var and np.std correctly for complex types.
  numba/parfor.py
  numba/targets/arraymath.py
  numba/tests/test_array_reductions.py
  numba/tests/test_parfors.py
  numba/typing/arraydecl.py
Labels: 3 - Ready for Review

#3079 Implement +/-(types.boolean) Fix #2624
  numba/targets/numbers.py
  numba/tests/test_operators.py
  numba/typing/builtins.py
Labels: 3 - Ready for Review

#3059 Handler for known LoweringErrors.
  numba/compiler.py
  numba/ir_utils.py
  numba/tests/test_closure.py
  numba/tests/test_dataflow.py
  numba/tests/test_errorhandling.py
Labels: 3 - Ready for Review

#3094 Add higher ULP tolerance for products in complex space.
  numba/tests/test_array_reductions.py
Labels: 3 - Ready for Review

#3104 Workaround for #3098
  numba/tests/test_optional.py
Labels: 3 - Ready for Review

#3125 Skip cudasim only tests
  numba/cuda/testing.py
  numba/cuda/tests/cudasim/test_cudasim_issues.py
Labels: 3 - Ready for Review

#3167 In build script activate env before installing.
  buildscripts/incremental/setup_conda_environment.sh
Labels: 3 - Ready for Review

#3168 Py37 bytes output fix.
  numba/numba_entry.py
  numba/roc/hlc/hlc.py
Labels: 3 - Ready for Review

#3122 Add inliner to object mode pipeline
  numba/compiler.py
  numba/tests/test_comprehension.py
  numba/tests/test_errorhandling.py
Labels: 3 - Ready for Review

#3180 Add skip to broken test.
  numba/tests/test_parfors.py
Labels: 3 - Ready for Review

#3179 Updates for llvmlite 0.25
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  requirements.txt
  setup.py
Labels: 3 - Ready for Review

#3176 Move ROC vectorize init to npyufunc
  numba/npyufunc/__init__.py
  numba/roc/__init__.py
Labels: 3 - Ready for Review, ROC

#3165 Add FMA intrinsic support
  docs/source/cuda-reference/kernel.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/device_init.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_intrinsics.py
Labels: BuildFarm Passed, CUDA

#3152 Use cuda driver api to get best blocksize for best occupancy
  numba/cuda/compiler.py
  numba/cuda/tests/cudapy/test_deprecation.py
Labels: 3 - Ready for Review, CUDA

#3177 Add auto_synchronize support to ROC stream
  numba/roc/hsadrv/driver.py
  numba/roc/tests/hsapy/test_async_kernel.py
Labels: 3 - Ready for Review, BuildFarm Passed, ROC
