Repository numba/numba, pull requests merged in 2018-08, with the labels that each got.

#3178 Update ROC target documentation.
  docs/source/cuda/ufunc.rst
  docs/source/hsa/device-functions.rst
  docs/source/hsa/device-management.rst
  docs/source/hsa/memory.rst
  docs/source/hsa/overview.rst
  docs/source/index.rst
  docs/source/roc/device-functions.rst
  docs/source/roc/device-management.rst
  docs/source/roc/examples.rst
  docs/source/roc/index.rst
  docs/source/roc/intrinsics.rst
  docs/source/roc/kernels.rst
  docs/source/roc/memory.rst
  docs/source/roc/overview.rst
  docs/source/roc/ufunc.rst
  numba/roc/__init__.py
  setup.py
Labels: 3 - Ready for Review, ROC

#3191 CUDA: fix log size
  numba/cuda/cudadrv/driver.py
Labels: 3 - Ready for Review, CUDA

#3216 Fix libcuda.so loading in some container setup
  numba/cuda/cudadrv/driver.py
Labels: 3 - Ready for Review, BuildFarm Passed, CUDA

#3137 Fix for issue3103 (race condition detection)
  numba/errors.py
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: BuildFarm Passed, ParallelAccelerator

#3221 Support datetime/timedelta scalar argument to a CUDA kernel.
  numba/cuda/compiler.py
  numba/cuda/tests/cudapy/test_datetime.py
Labels: BuildFarm Passed, CUDA

#3017 Add facility to support with-contexts
  numba/__init__.py
  numba/compiler.py
  numba/controlflow.py
  numba/dataflow.py
  numba/datamodel/models.py
  numba/dispatcher.py
  numba/interpreter.py
  numba/ir.py
  numba/ir_utils.py
  numba/stencilparfor.py
  numba/tests/test_withlifting.py
  numba/transforms.py
  numba/types/misc.py
  numba/typing/typeof.py
  numba/withcontexts.py
Labels: 3 - Ready for Review

#3181 Support function extension in alias analysis
  numba/ir_utils.py
  numba/tests/test_remove_dead.py
Labels: BuildFarm Passed, ParallelAccelerator

#3227 Add NumPy 1.15 support
  .travis.yml
  README.rst
  appveyor.yml
  docs/source/user/installing.rst
  numba/tests/test_linalg.py
Labels: 3 - Ready for Review

#3233 Fix return type difference for 32bit ctypes.c_void_p
  numba/tests/test_ctypes.py
  numba/typing/ctypes_utils.py
Labels: 3 - Ready for Review, BuildFarm Passed

#3145 Support for np.fill_diagonal
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_array_manipulation.py
Labels: 3 - Ready for Review

#3235 Add 32bit Travis CI jobs
  .travis.yml
  buildscripts/incremental/install_miniconda.sh
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
Labels: 3 - Ready for Review

#3199 Support inferring stencil index as constant in simple unary expressions
  docs/source/user/stencil.rst
  numba/ir_utils.py
  numba/stencil.py
  numba/stencilparfor.py
  numba/tests/test_stencils.py
Labels: ParallelAccelerator, Pending BuildFarm

#3127 Support for reductions on arrays.
  docs/source/user/parallel.rst
  numba/inline_closurecall.py
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: BuildFarm Passed, ParallelAccelerator

#3237 Fix DeprecationWarning about imp module
  numba/serialize.py
  numba/tests/test_serialize.py
Labels: 3 - Ready for Review

#3258 Allow users to choose the type of issue they are reporting.
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: 3 - Ready for Review

#3242 Page with Numba talks and tutorial links
  docs/source/user/index.rst
  docs/source/user/talks.rst
Labels: 3 - Ready for Review

#3256 Fix #3251: Move imports of ABCs to collections.abc for Python >= 3.3
  numba/annotations/type_annotations.py
  numba/jitclass/base.py
  numba/roc/hsadrv/driver.py
  numba/typing/context.py
  numba/utils.py
Labels: 3 - Ready for Review

#3230 Fixes liveness analysis issue in looplifting
  numba/analysis.py
  numba/tests/test_looplifting.py
  numba/transforms.py
Labels: 3 - Ready for Review

#3266 Fix cuda pointer ownership problem with user/externally allocated pointer
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_cuda_memory.py
Labels: 3 - Ready for Review, BuildFarm Passed, CUDA

#3269 Tweak typography with CSS
  docs/_static/numba-docs.css
  docs/source/conf.py
Labels: 3 - Ready for Review

#3142 Fix Issue #3139 (parfors reuse of reduction variable across prange blocks)
  numba/npyufunc/parfor.py
  numba/tests/test_parfors.py
Labels: BuildFarm Passed, ParallelAccelerator

#3241 Fix #3225. Normalize 0nd array to scalar in typing of indexing code.
  numba/tests/test_fancy_indexing.py
  numba/tests/test_indexing.py
  numba/typing/arraydecl.py
Labels: 3 - Ready for Review

#3270 Update FAQ for functions passed as arguments
  docs/source/user/faq.rst
Labels: 3 - Ready for Review

#3280 Add wavebits property to the HSA Agent.
  numba/roc/hsadrv/driver.py
  numba/roc/tests/hsadrv/test_driver.py
Labels: 3 - Ready for Review, BuildFarm Passed
