Repository numba/numba, pull requests merged in 2018-09, with the labels that each got.

#3278 compiler threadsafety lockdown
  numba/ccallback.py
  numba/compiler.py
  numba/compiler_lock.py
  numba/cuda/compiler.py
  numba/dispatcher.py
  numba/npyufunc/ufuncbuilder.py
  numba/npyufunc/wrappers.py
  numba/pycc/cc.py
  numba/pycc/compiler.py
  numba/runtime/nrt.py
  numba/targets/base.py
  numba/targets/codegen.py
  numba/targets/cpu.py
  numba/tests/test_cgutils.py
  numba/tests/test_codegen.py
  numba/tests/test_compiler_lock.py
Labels: 3 - Ready for Review

#3234 Fix types and layout for `np.where`.
  numba/targets/arraymath.py
  numba/tests/test_array_methods.py
  numba/typing/npydecl.py
Labels: 3 - Ready for Review

#3172 Use float64 add Atomics, Where Available
  numba/cuda/compiler.py
  numba/cuda/nvvmutils.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/cuda/tests/cudapy/test_inspect.py
Labels: 3 - Ready for Review, BuildFarm Passed, CUDA

#3294 Add compiler lock to ROC compilation path.
  numba/roc/compiler.py
Labels: 3 - Ready for Review, Pending BuildFarm

#3212 Support for np.vander
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 3 - Ready for Review

#3209 Support for np.tri, np.tril and np.triu
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 3 - Ready for Review

#3281 Fix ds_permute types and add tests
  numba/roc/hsadecl.py
  numba/roc/hsaimpl.py
  numba/roc/tests/hsapy/test_intrinsics.py
  numba/roc/tests/hsapy/test_scan.py
Labels: 3 - Ready for Review, BuildFarm Passed

#3291 Add CPU count and CFS restrictions info to numba -s.
  numba/numba_entry.py
Labels: 3 - Ready for Review, BuildFarm Passed

#3302 Fix error due to mismatching dtype
  numba/tests/test_withlifting.py
Labels: 3 - Ready for Review

#3310 Fix IPC handling of sliced cuda array.
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudapy/test_ipc.py
Labels: 3 - Ready for Review, BuildFarm Passed, CUDA

#3329 Fix AOT on windows.
  numba/pycc/platform.py
  numba/tests/test_pycc.py
Labels: 3 - Ready for Review

#3340 Fix typo in error name.
  numba/withcontexts.py
Labels: 3 - Ready for Review
