Repository numba/numba, pull requests merged in 2019-06, with the labels that each got.

#4138 Remove tbb before Azure test only on Python 3, since it was already removed for Python 2
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge

#4085 Resolves #3314.
  numba/array_analysis.py
  numba/tests/test_parfors.py
Labels: 4 - Waiting on reviewer

#4129 Support contains for range
  numba/targets/rangeobj.py
  numba/tests/test_range.py
Labels: 5 - Ready to merge

#4132 Reduce usage of inttoptr
  numba/jitclass/boxing.py
  numba/npyufunc/parallel.py
  numba/npyufunc/parfor.py
  numba/targets/arrayobj.py
Labels: 5 - Ready to merge

#4137 CUDA - Fix round Builtin
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_intrinsics.py
Labels: 5 - Ready to merge

#4145 Use callable instead of checking __module__
  numba/extending.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge

#4147 fix docstring for DictType iterables
  numba/types/containers.py
Labels: 5 - Ready to merge

#4152 fix status check in dict lookup
  numba/dictobject.py
Labels: 5 - Ready to merge

#4165 Fix #4164 issue with NUMBAPRO_NVVM
  numba/cuda/cuda_paths.py
  numba/cuda/tests/nocuda/test_library_lookup.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4172 Abandon branch pruning if an arg name is redefined.
  numba/analysis.py
  numba/tests/test_analysis.py
Labels: 5 - Ready to merge

#4183 Fix #4156. Problem with defining in-loop variables.
  numba/cgutils.py
  numba/lowering.py
  numba/tests/test_practical_lowering_issues.py
Labels: 3 - Ready for Review

#4196 Catch missing imports of internal functions.
  numba/tests/test_errorhandling.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#4180 Update use of unlowerable global message.
  numba/ir_utils.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge

#4178 Fix unary operator overload, check with unicode impl
  numba/lowering.py
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4149 Implement dominance frontier for SSA for the Numba IR
  LICENSES.third-party
  numba/controlflow.py
  numba/tests/test_flow_control.py
Labels: 5 - Ready to merge

#4173 Fix return type in np.bincount with weights
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4095 Support ir.Global/FreeVar in find_const()
  numba/ir_utils.py
  numba/tests/test_analysis.py
  numba/tests/test_ir_utils.py
Labels: 5 - Ready to merge

#4088 Resolves #4075.
  numba/array_analysis.py
  numba/ir_utils.py
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/stencil.py
  numba/stencilparfor.py
  numba/tests/test_array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#3951 A guide to overloading
  docs/source/extending/index.rst
  docs/source/extending/mynorm.py
  docs/source/extending/overloading-guide.rst
  docs/source/extending/template.py
Labels: 5 - Ready to merge

#4166 Add tests for PR #4149
  numba/controlflow.py
  numba/tests/test_flow_control.py
Labels: 5 - Ready to merge

#4170 Clarify docs on accumulating into arrays in prange
  docs/source/user/parallel.rst
Labels: 5 - Ready to merge

#4153 Fix slice shape assignment in array analysis
  numba/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge, ParallelAccelerator

#4197 hyperlink repomap
  docs/source/_ext/ghfiles.py
  docs/source/conf.py
  docs/source/developer/repomap.rst
Labels: 5 - Ready to merge

#4205 Update return value order in normalize_signature docstring
  numba/sigutils.py
Labels: 5 - Ready to merge

#4209 Revert previous network tol patch and try with conda config
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge

#4216 Add dominator tree
  numba/controlflow.py
  numba/tests/test_flow_control.py
Labels: 5 - Ready to merge

#4222 Fix bad python path.
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge

#4232 Add unicodetype db, low level str functions and examples.
  LICENSES.third-party
  docs/source/reference/pysupported.rst
  numba/_helperlib.c
  numba/_helpermod.c
  numba/_unicodetype_db.h
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4237 Update doc links to point to latest not dev docs.
  numba/errors.py
  numba/targets/codegen.py
Labels: 5 - Ready to merge

#4157 Support for np.flatnonzero
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge

#3646 Log internal errors encountered in typeinfer
  docs/source/developer/contributing.rst
  numba/_runtests.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#4227 Include numba version in reportable error message
  numba/__init__.py
  numba/errors.py
Labels: 5 - Ready to merge
