Repository numba/numba, pull requests merged in 2019-11, with the labels that each got.

#4767 pin to 2.7.16 for py27 on osx
  azure-pipelines.yml
Labels: 5 - Ready to merge

#4734 prefer to import from collections.abc
  numba/six.py
  numba/types/containers.py
Labels: 5 - Ready to merge

#4651 Implement str.lower() and str.islower()
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4707 Added support for slice.indices
  numba/targets/slicing.py
  numba/tests/test_slices.py
  numba/typing/builtins.py
Labels: 5 - Ready to merge

#4781 WIP/runtest cf pytest
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  numba/testing/main.py
  numba/tests/test_runtests.py
Labels: 3 - Ready for Review

#4802 put git hash into build string
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge

#4794 Add setuptools as a dependency
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#4791 fix typos
  numba/types/containers.py
Labels: 5 - Ready to merge

#4789 fix typos in numba/targets/base.py
  numba/targets/base.py
Labels: 5 - Ready to merge

#4782 Fix issue with SVML (and knock-on function resolution effects).
  numba/__init__.py
  numba/charseq.py
  numba/tests/test_svml.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4776 Fix and enable idle tests from test_array_manipulation
  numba/tests/test_array_manipulation.py
  numba/typing/arraydecl.py
Labels: 5 - Ready to merge

#4777 Fix transpose output array layout
  numba/tests/test_array_manipulation.py
  numba/typing/arraydecl.py
Labels: 5 - Ready to merge

#4741 Update choosing the "CUDA_PATH" for windows
  numba/cuda/cuda_paths.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4629 Make numba.dummyarray.Array iterable
  numba/dummyarray.py
  numba/tests/test_dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4611 Implement method title() for unicode based on Cpython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4652 Implement str.rfind()
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4787 fix missing incref on flags
  numba/targets/arrayobj.py
  numba/tests/test_array_attr.py
Labels: 5 - Ready to merge

#4811 fix spelling in now-failing tests
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge

#4599 Permits closures to become functions, enables map(), filter()
  docs/source/reference/pysupported.rst
  numba/compiler.py
  numba/compiler_machinery.py
  numba/dataflow.py
  numba/datamodel/models.py
  numba/entrypoints.py
  numba/inline_closurecall.py
  numba/interpreter.py
  numba/ir_utils.py
  numba/parfor.py
  numba/targets/builtins.py
  numba/tests/test_closure.py
  numba/tests/test_dataflow.py
  numba/tests/test_errorhandling.py
  numba/tests/test_make_function_to_jit_function.py
  numba/tests/test_map_filter_reduce.py
  numba/tests/test_withlifting.py
  numba/typed_passes.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4718 Change get_call_table to support intermediate Vars.
  numba/ir_utils.py
  numba/stencilparfor.py
  numba/tests/test_stencils.py
Labels: 5 - Ready to merge

#4785 Treat 0d arrays like scalars.
  numba/array_analysis.py
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4851 Add graphviz output for FunctionIR
  numba/ir.py
Labels: 5 - Ready to merge

#4841 Implement str.rpartition() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4837 Implement str.isidentifier() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4835 Implement str.isspace() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4852 windowing test should check equality only up to double precision errors
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4874 Bump to llvmlite 0.31
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#4755 Python3.8 support
  .flake8
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  numba/bytecode.py
  numba/byteflow.py
  numba/controlflow.py
  numba/dataflow.py
  numba/interpreter.py
  numba/ir.py
  numba/npyufunc/parallel.py
  numba/targets/randomimpl.py
  numba/tests/support.py
  numba/tests/test_cfunc.py
  numba/tests/test_dispatcher.py
  numba/tests/test_flow_control.py
  numba/tests/test_hashing.py
  numba/tests/test_ir.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_jitmethod.py
  numba/tests/test_looplifting.py
  numba/tests/test_mathlib.py
  numba/tests/test_parfors.py
  numba/tests/test_random.py
  numba/tests/test_stencils.py
  numba/tests/test_typingerror.py
  numba/tests/test_warnings.py
  numba/transforms.py
Labels: 5 - Ready to merge

#4866 Support params start/end for str.find()
  numba/charseq.py
  numba/tests/test_unicode.py
  numba/tests/test_unicode_array.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4862 Addition of PyCon India 2019 talk on Numba
  docs/source/user/talks.rst
Labels: 5 - Ready to merge

#4847 Implement str.isascii() based on CPython
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4817 Typed list implement and expose allocation
  numba/_helpermod.c
  numba/cext/listobject.c
  numba/cext/listobject.h
  numba/listobject.py
  numba/tests/test_listimpl.py
  numba/tests/test_listobject.py
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#4803 Better compiler error messages for improperly used reduction variables.
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4779 Make slice constructor more similar to python.
  numba/targets/slicing.py
  numba/tests/test_slices.py
  numba/typing/builtins.py
Labels: 5 - Ready to merge

#4770 Update `np.arange` implementation with `@overload`
  numba/targets/arrayobj.py
  numba/tests/test_array_methods.py
  numba/tests/test_looplifting.py
  numba/typing/npydecl.py
Labels: 5 - Ready to merge

#4882 Fix return type in arange and zero step size handling.
  numba/targets/arrayobj.py
  numba/testing/main.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge

#4885 suppress spurious RuntimeWarning about ufunc sizes
  numba/tests/test_dataflow.py
Labels: 5 - Ready to merge, BuildFarm Passed
