Repository numba/numba, pull requests merged in 2019-02, with the labels that each got.

#3710 Set as non-hoistable if a mutable variable is passed to a function in a loop. Resolves #3699.
  numba/npyufunc/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#3718 Add location to ConstantInferenceError exceptions.
  .flake8
  numba/consts.py
  numba/errors.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge

#3734 Update changelog for 0.42.1
  CHANGE_LOG
Labels: 5 - Ready to merge

#3703 Implementations of type hashing.
  buildscripts/azure/azure-windows.yml
  docs/source/developer/hashing.rst
  docs/source/developer/index.rst
  docs/source/reference/pysupported.rst
  numba/_helperlib.c
  numba/dispatcher.py
  numba/pythonapi.py
  numba/targets/base.py
  numba/targets/boxing.py
  numba/targets/hashing.py
  numba/targets/numbers.py
  numba/targets/setobj.py
  numba/targets/tupleobj.py
  numba/tests/test_hashing.py
  numba/typing/builtins.py
  numba/unicode.py
  numba/unsafe/bytes.py
Labels: 5 - Ready to merge, BuildFarm Passed

#3740 add uintp as a valid type to the tuple operator.getitem
  numba/targets/tupleobj.py
  numba/tests/test_tuples.py
Labels: 5 - Ready to merge

#3755 Make cuda.to_device accept readonly host array
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/mviewbuf.c
Labels: 5 - Ready to merge, CUDA

#3715 Port CPython3.7 dictionary for numba internal use
  numba/_dictobject.c
  numba/_dictobject.h
  numba/_helperlib.c
  numba/_helpermod.c
  numba/tests/test_dictimpl.py
  setup.py
Labels: 5 - Ready to merge

#3760 Overloadable operator.setitem
  numba/lowering.py
  numba/targets/arrayobj.py
  numba/targets/builtins.py
  numba/targets/listobj.py
  numba/tests/test_comprehension.py
  numba/tests/test_extending.py
  numba/tests/test_typingerror.py
  numba/typing/arraydecl.py
  numba/typing/builtins.py
  numba/typing/collections.py
  numba/typing/context.py
Labels: 5 - Ready to merge

#3775 Support overloading operator.delitem
  numba/lowering.py
  numba/targets/listobj.py
  numba/tests/test_extending.py
  numba/typing/collections.py
  numba/typing/context.py
Labels: 5 - Ready to merge

#3773 Adapt library search to accommodate multiple locations
  numba/cuda/tests/cudadrv/test_cuda_libraries.py
  numba/findlib.py
Labels: 5 - Ready to merge, CUDA

#3696 Add intrinsic to help debug refcount
  .flake8
  numba/_helpermod.c
  numba/cgutils.py
  numba/cuda/testing.py
  numba/runtime/context.py
  numba/tests/support.py
  numba/tests/test_unsafe_intrinsics.py
  numba/unsafe/refcount.py
Labels: 5 - Ready to merge

#3754 Updates for llvmlite 0.28
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#3720 improve error msg about invalid signature
  numba/sigutils.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#3722 Fix #3705: slicing error with negative strides
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba/dummyarray.py
  numba/tests/test_dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#3758 Fix target definition update in inlining
  numba/inline_closurecall.py
  numba/tests/test_inlining.py
Labels: 5 - Ready to merge

#3749 DOC: Clarify when prange is different from range
  docs/source/user/parallel.rst
  examples/kernel-density-estimation/kernel_density_estimation.py
  examples/kernel-density-estimation/kernel_density_estimation_numba.py
  examples/kernel-density-estimation/kernel_density_estimation_pa.py
  examples/laplace2d/laplace2d-pa.py
  numba/special.py
Labels: 5 - Ready to merge, doc

#3771 fix a few typos
  docs/source/developer/contributing.rst
  docs/source/developer/generators.rst
  docs/source/developer/live_variable_analysis.rst
Labels: 5 - Ready to merge

#3678 Support for str.split and str.join
  .flake8
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/tests/test_unicode_literals.py
  numba/tests/test_unicode_names.py
  numba/tests/test_unsafe_intrinsics.py
  numba/unicode.py
  numba/unsafe/bytes.py
Labels: 5 - Ready to merge

#3808 Bump macro to include VS2014 to fix py3.5 build
  numba/_dictobject.c
Labels: 5 - Ready to merge, BuildFarm Passed

#3785 Clarify use of range as function only.
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge, doc

#3731 Support for heapq
  docs/source/reference/pysupported.rst
  numba/targets/base.py
  numba/targets/heapq.py
  numba/tests/test_heapq.py
Labels: 5 - Ready to merge

#3592 Add dead branch prune before type inference.
  .flake8
  numba/analysis.py
  numba/compiler.py
  numba/controlflow.py
  numba/tests/test_analysis.py
Labels: 5 - Ready to merge, R&D

#3777 Implement compiler support for dictionary
  numba/_dictobject.c
  numba/_dictobject.h
  numba/_helpermod.c
  numba/datamodel/models.py
  numba/dictobject.py
  numba/targets/boxing.py
  numba/targets/builtins.py
  numba/tests/test_dictimpl.py
  numba/tests/test_dictobject.py
  numba/types/abstract.py
  numba/types/containers.py
  numba/typing/builtins.py
  numba/typing/typeof.py
Labels: 5 - Ready to merge
