Repository numba/numba, pull requests merged in 2019-03, with the labels that each got.

#3791 Implement interpreter-side interface for numba dict
  numba/dictobject.py
  numba/pythonapi.py
  numba/runtime/_nrt_python.c
  numba/runtime/_nrt_pythonmod.c
  numba/runtime/nrt.py
  numba/targets/boxing.py
  numba/tests/test_dictobject.py
  numba/typeddict.py
  numba/typing/typeof.py
Labels: 4 - Waiting on reviewer

#3799 Support refcount'ed types in numba dict
  numba/_dictobject.c
  numba/_dictobject.h
  numba/_helpermod.c
  numba/dictobject.py
  numba/runtime/nrtopt.py
  numba/tests/test_dictobject.py
  numba/typed/__init__.py
  numba/typed/typeddict.py
  numba/types/containers.py
  numba/typing/typeof.py
Labels: 3 - Ready for Review, Pending BuildFarm

#3816 Fix array.sum(axis) 1d input return type.
  numba/targets/arraymath.py
  numba/tests/test_array_methods.py
  numba/typing/arraydecl.py
Labels: 5 - Ready to merge

#3800 Bugfix for np.interp
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 4 - Waiting on author

#3821 Replace PySys_WriteStdout with PySys_FormatStdout to ensure no truncation.
  numba/pythonapi.py
  numba/tests/test_print.py
Labels: 5 - Ready to merge

#3725 Fix invalid removal of dead empty list
  numba/inline_closurecall.py
  numba/tests/test_comprehension.py
Labels: 5 - Ready to merge

#3782 Raise typing error on yield optional.
  .flake8
  numba/tests/test_generators.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#3792 Fix non-module object used as the module of a function.
  numba/_dynfunc.c
Labels: 5 - Ready to merge

#3829 Add docs for typed-dict
  docs/source/reference/pysupported.rst
  examples/dict_usage.py
Labels: 5 - Ready to merge, doc

#3830 Getitem should not return optional type
  numba/dictobject.py
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge

#3832 Handle single string as path in find_file()
  .flake8
  numba/cuda/tests/cudadrv/test_detect.py
  numba/findlib.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#3809 Add debug guard to debug only C function.
  numba/_dictobject.c
Labels: 5 - Ready to merge

#3820 Min max on iterables
  numba/targets/builtins.py
  numba/targets/heapq.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge

#3842 Unicode type iteration
  numba/dictobject.py
  numba/runtime/nrt.c
  numba/targets/arrayobj.py
  numba/targets/imputils.py
  numba/targets/iterators.py
  numba/targets/listobj.py
  numba/targets/setobj.py
  numba/targets/tupleobj.py
  numba/tests/test_unicode.py
  numba/types/misc.py
  numba/unicode.py
Labels: 5 - Ready to merge

#3845 Fix mutable flag transmission in .astype
  numba/tests/test_array_methods.py
  numba/typing/arraydecl.py
Labels: 5 - Ready to merge

#3852 Continuation of PR #2894
  LICENSES.third-party
  buildscripts/remove_unwanted_files.py
  numba/jitclass/base.py
  numba/tests/jitclass_usecases.py
  numba/tests/test_jitclasses.py
  numba/typing/templates.py
  numba/utils.py
Labels: 5 - Ready to merge

#3853 Fix some minor issues in the C source.
  numba/_dynfunc.c
  numba/_helperlib.c
  numba/npyufunc/_internal.c
  numba/npyufunc/_ufunc.c
  numba/npyufunc/omppool.cpp
  numba/npyufunc/tbbpool.cpp
  numba/npyufunc/workqueue.c
  numba/runtime/_nrt_python.c
Labels: 5 - Ready to merge

#3861 Continuation of PR #3730
  .flake8
  numba/jitclass/base.py
  numba/jitclass/boxing.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#3862 Correct boolean reinterpretation of data
  numba/datamodel/models.py
  numba/tests/test_datamodel.py
Labels: 5 - Ready to merge

#3863 Comments out the appveyor badge
  README.rst
  appveyor.yml
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge

#3869 fixes flake8 after merge
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#3886 Use `safe_load` from pyyaml.
  .flake8
  numba/config.py
Labels: 5 - Ready to merge

#3883 Rewrite pruned conditionals as their evaluated constants.
  numba/analysis.py
  numba/tests/test_analysis.py
Labels: 5 - Ready to merge

#3881 fix preparfor dtype transform for datetime64
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#3850 Refactor np.interp
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3826 NumPy 1.16 support
  .flake8
  docs/source/reference/numpysupported.rst
  docs/source/user/installing.rst
  numba/npdatetime.py
  numba/targets/arraymath.py
  numba/targets/npdatetime.py
  numba/targets/ufunc_db.py
  numba/tests/support.py
  numba/tests/test_array_reductions.py
  numba/tests/test_np_functions.py
  numba/tests/test_npdatetime.py
  numba/tests/test_types.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#3892 Change log update for 0.43.1
  CHANGE_LOG
Labels: 5 - Ready to merge

#3903 xfail ediff1d test on windows + np1.16
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, BuildFarm Passed
