Repository numba/numba, pull requests merged in 2019-01, with the labels that each got.

#3612 Exact match flag in dispatcher
  numba/_dispatcher.c
  numba/_dispatcher.h
  numba/_dispatcherimpl.cpp
  numba/dispatcher.py
  numba/tests/test_dispatcher.py
  numba/tests/test_typeconv.py
  numba/typeconv/_typeconv.cpp
  numba/typeconv/typeconv.cpp
  numba/typeconv/typeconv.hpp
  numba/typeconv/typeconv.py
  numba/typing/context.py
  numba/typing/templates.py
Labels: 5 - Ready to merge

#3614 Resolve #3586
  numba/tests/test_unsafe_intrinsics.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#3572 Support for np.ptp
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#3618 Skip gdb tests on ARM.
  numba/tests/test_gdb.py
Labels: 5 - Ready to merge

#3598 Implement np.asarray()
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_errorhandling.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3563 Support for np.roll
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3607 Some simplication to lowering
  .flake8
  numba/datamodel/models.py
  numba/jitclass/base.py
  numba/lowering.py
  numba/targets/base.py
  numba/targets/codegen.py
  numba/types/functions.py
  numba/typing/context.py
  numba/typing/templates.py
Labels: 5 - Ready to merge

#3662 Replace six with numba.six
  numba/cuda/cudaimpl.py
Labels: 3 - Ready for Review, Pending BuildFarm

#3663 Removes coverage computation from travisci builds
  .travis.yml
Labels: 5 - Ready to merge

#3633 Support for np.extract
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3645 Enforce and fix that AbstractTemplate.generic must be returning a Sig…
  .flake8
  numba/typeinfer.py
  numba/typing/arraydecl.py
  numba/typing/builtins.py
  numba/typing/enumdecl.py
  numba/typing/templates.py
Labels: 5 - Ready to merge

#3661 Access C Struct as Numpy Structured Array
  docs/source/user/cfunc.rst
  examples/notebooks/Accessing C Struct Data.ipynb
  numba/numpy_support.py
  numba/tests/test_cfunc.py
  numba/tests/test_dyn_array.py
  numba/tests/test_record_dtype.py
  numba/types/npytypes.py
  numba/typing/cffi_utils.py
Labels: 5 - Ready to merge

#3692 Fix test failure due to overly strict test on floating point values.
  numba/cuda/tests/cudadrv/test_deallocations.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#3627 Support for np.trapz
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3676 Fixes constant string lowering inside tuples
  numba/cgutils.py
  numba/targets/arrayobj.py
  numba/targets/base.py
  numba/targets/tupleobj.py
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#3677 Ensure all referenced compiled functions are linked properly
  numba/_runtests.py
  numba/lowering.py
  numba/stencil.py
  numba/targets/base.py
  numba/targets/codegen.py
  numba/targets/iterators.py
Labels: 5 - Ready to merge

#3648 Fail on @overload signature mismatch.
  buildscripts/remove_unwanted_files.py
  numba/extending.py
  numba/targets/arraymath.py
  numba/targets/arrayobj.py
  numba/targets/builtins.py
  numba/targets/linalg.py
  numba/targets/randomimpl.py
  numba/tests/overload_usecases.py
  numba/tests/test_extending.py
  numba/typing/templates.py
  numba/unicode.py
  numba/utils.py
Labels: 5 - Ready to merge

#3693 Intercept failed import to help users.
  numba/errors.py
  numba/typeconv/typeconv.py
Labels: 5 - Ready to merge

#3672 Avoid leaking memory when iterating over uniform tuple
  numba/targets/tupleobj.py
  numba/tests/test_iteration.py
Labels: 5 - Ready to merge

#3604 Support for np.interp
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3697 Fix for issue #3687
  numba/npyufunc/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#3660 Added Ignore message to test numba.tests.test_lists.TestLists.test_mul_error…
  numba/tests/test_lists.py
Labels: 5 - Ready to merge

#3694 Fix memory leak in enumerate iterator
  numba/cgutils.py
  numba/targets/iterators.py
  numba/targets/tupleobj.py
  numba/tests/test_iteration.py
Labels: 5 - Ready to merge

#3695 Convert return of None from intrinsic implementation to dummy value
  numba/lowering.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge

#3701 Fix array.T analysis (fixes #3700)
  numba/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge

#3630 np.where with broadcasting
  numba/targets/arraymath.py
  numba/tests/test_array_methods.py
  numba/typing/npydecl.py
Labels: 5 - Ready to merge

#3657 np.max, np.min, np.nanmax, np.nanmin - support for complex dtypes
  numba/targets/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#3704 Fixes for overload_method
  numba/targets/callconv.py
  numba/tests/test_extending.py
  numba/typing/templates.py
  numba/utils.py
Labels: 5 - Ready to merge

#3712 parallel=True to use better builtin mechanism to resolve call types. Resolves issue #3671
  numba/ir_utils.py
  numba/parfor.py
  numba/stencilparfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#3716 Support inplace concat of strings
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge
