Repository numba/numba, pull requests merged in 2019-10, with the labels that each got.

#4606 Enable support for count() method for unicode string
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4623 Fix issue 4520 due to storage model mismatch
  numba/tests/test_dictobject.py
  numba/tests/test_typedlist.py
  numba/typedobjectutils.py
Labels: 5 - Ready to merge

#4601 Add triangular indices functions
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4609 Update CUDA Array Interface & Enforce Numba compliance
  docs/source/cuda/cuda_array_interface.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4595 Implement numba.cross2d
  docs/source/reference/numpysupported.rst
  numba/numpy_extensions.py
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4644 Updates for llvmlite 0.30.0
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#4646 Change Log update for 0.46
  CHANGE_LOG
Labels: 5 - Ready to merge

#4655 fix sphinx build warning
  CHANGE_LOG
Labels: 5 - Ready to merge

#4656 fix sphinx build warning
  CHANGE_LOG
Labels: 5 - Ready to merge

#4675 Bump cuda array interface to version 2
  docs/source/cuda/cuda_array_interface.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4680 Apply #4675 to on 0.46 release branch
  docs/source/cuda/cuda_array_interface.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 4 - Waiting on CI

#4682 Update changelog for 0.46 final release
  CHANGE_LOG
Labels: 4 - Waiting on reviewer

#4685 Apply #4682 to 0.46 release branch
  CHANGE_LOG
Labels: 3 - Ready for Review

#4501 Add pre-commit hooks
  .flake8
  .pre-commit-config.yaml
  docs/source/developer/contributing.rst
  docs/source/developer/repomap.rst
  numba/callwrapper.py
  numba/ccallback.py
  numba/cgutils.py
  numba/charseq.py
  numba/compiler.py
  numba/compiler_machinery.py
  numba/config.py
  numba/controlflow.py
  numba/cuda/cudaimpl.py
  numba/cuda/errors.py
  numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
  numba/cuda/tests/cudapy/test_debug.py
  numba/cuda/tests/cudapy/test_gufunc_scalar.py
  numba/dictobject.py
  numba/help/inspector.py
  numba/listobject.py
  numba/lowering.py
  numba/npdatetime.py
  numba/npyufunc/parallel.py
  numba/npyufunc/wrappers.py
  numba/numpy_support.py
  numba/object_mode_passes.py
  numba/roc/target.py
  numba/runtime/nrtopt.py
  numba/scripts/generate_lower_listing.py
  numba/targets/arraymath.py
  numba/targets/arrayobj.py
  numba/targets/gdb_hook.py
  numba/targets/hashing.py
  numba/tests/npyufunc/test_caching.py
  numba/tests/npyufunc/test_ufunc.py
  numba/tests/test_codegen.py
  numba/tests/test_dispatcher.py
  numba/tests/test_entrypoints.py
  numba/tests/test_gdb.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_jit_module.py
  numba/tests/test_np_functions.py
  numba/tests/test_numpy_support.py
  numba/tests/test_practical_lowering_issues.py
  numba/tests/test_record_dtype.py
  numba/tests/test_typedlist.py
  numba/tests/test_unicode.py
  numba/tests/test_unicode_array.py
  numba/typed_passes.py
  numba/typedobjectutils.py
  numba/typeinfer.py
  numba/typing/context.py
  numba/typing/templates.py
  numba/unicode.py
  numba/unicode_support.py
  numba/unsafe/bytes.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4418 Directed graph task roadmap
  LICENSES.third-party
  docs/dagmap/README.md
  docs/dagmap/dagmap.yaml
  docs/dagmap/jquery.graphviz.svg.js
  docs/dagmap/render.py
  docs/dagmap/template.html
Labels: 5 - Ready to merge

#4578 Clarify numba ufunc supported features
  docs/source/user/vectorize.rst
Labels: 5 - Ready to merge

#4669 Add link to ParallelAccelerator paper.
  docs/source/user/faq.rst
Labels: 5 - Ready to merge

#4703 Fix numba.jit parameter name signature_or_function
  numba/decorators.py
Labels: 5 - Ready to merge

#4536 Handle kw args in inliner when callee is a function
  numba/inline_closurecall.py
  numba/tests/test_ir_inlining.py
Labels: 5 - Ready to merge

#4582 Convert sub to add and div to mul when doing the reduction across the per-thread reduction array.
  docs/source/user/parallel.rst
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4645 Enable support for istitle() method for unicode string
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4660 Remove multiply defined variables from all blocks' equivalence sets.
  numba/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4667 Fix typo on urem implementation
  numba/targets/npyfuncs.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#4672 Fix pickling of dufunc
  .flake8
  numba/npyufunc/dufunc.py
  numba/npyufunc/ufuncbuilder.py
  numba/tests/npyufunc/test_dufunc.py
Labels: 5 - Ready to merge

#4710 BUG: Comparison for literal
  numba/array_analysis.py
Labels: 5 - Ready to merge

#4737 remove maxParallel from Azure Pipelines
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge

#4725 Requires llvmlite >=0.30.0
  README.rst
Labels: 5 - Ready to merge

#4736 fix flake8 errors
  numba/npyufunc/dufunc.py
  numba/npyufunc/ufuncbuilder.py
Labels: 5 - Ready to merge
