Repository numba/numba, pull requests merged in 2019-09, with the labels that each got.

#4493 Fix Overload Inliner wrt CUDA Intrinsics
  numba/ir_utils.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4345 Replace "import *" with explicit imports in numba/types
  numba/tests/test_types.py
  numba/types/common.py
  numba/types/containers.py
  numba/types/functions.py
  numba/types/iterators.py
  numba/types/misc.py
  numba/types/npytypes.py
  numba/types/scalars.py
Labels: 5 - Ready to merge

#4541 fix two typos in architecture.rst
  docs/source/developer/architecture.rst
Labels: 5 - Ready to merge

#4331 Automatic JIT of called functions
  docs/source/user/index.rst
  docs/source/user/jit-module.rst
  docs/source/user/jit.rst
  numba/__init__.py
  numba/decorators.py
  numba/tests/test_jit_module.py
Labels: 5 - Ready to merge

#4513 New compiler.
  .flake8
  docs/source/developer/custom_pipeline.rst
  numba/ccallback.py
  numba/compiler.py
  numba/compiler_machinery.py
  numba/config.py
  numba/decorators.py
  numba/dispatcher.py
  numba/inline_closurecall.py
  numba/ir_utils.py
  numba/npyufunc/array_exprs.py
  numba/object_mode_passes.py
  numba/rewrites/registry.py
  numba/stencil.py
  numba/stencilparfor.py
  numba/tests/test_analysis.py
  numba/tests/test_array_analysis.py
  numba/tests/test_array_exprs.py
  numba/tests/test_copy_propagate.py
  numba/tests/test_dyn_array.py
  numba/tests/test_errorhandling.py
  numba/tests/test_extending.py
  numba/tests/test_inlining.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_ir_utils.py
  numba/tests/test_nrt.py
  numba/tests/test_obj_lifetime.py
  numba/tests/test_parfors.py
  numba/tests/test_pipeline.py
  numba/tests/test_practical_lowering_issues.py
  numba/tests/test_remove_dead.py
  numba/typed_passes.py
  numba/typing/templates.py
  numba/untyped_passes.py
Labels: 3 - Ready for Review, 5 - Ready to merge

#4581 Prevent taking the GIL in ForAll
  numba/cuda/compiler.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4567 Add env var to disable performance warnings.
  docs/source/reference/envvars.rst
  numba/config.py
  numba/tests/error_usecases.py
  numba/tests/test_warnings.py
  numba/typed_passes.py
  numba/typing/npydecl.py
Labels: 5 - Ready to merge

#4547 Update to inliner cost model information.
  numba/tests/test_ir_inlining.py
  numba/typed_passes.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4467 Literal dispatch
  .flake8
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/conf.py
  docs/source/developer/contributing.rst
  docs/source/developer/index.rst
  docs/source/developer/literal.rst
  examples/literally_usage.py
  numba/__init__.py
  numba/analysis.py
  numba/compiler.py
  numba/dispatcher.py
  numba/errors.py
  numba/extending.py
  numba/ir_utils.py
  numba/special.py
  numba/targets/base.py
  numba/targets/boxing.py
  numba/targets/literal_dispatch.py
  numba/tests/test_literal_dispatch.py
  numba/typeinfer.py
  numba/types/abstract.py
  numba/types/functions.py
  numba/types/misc.py
  numba/typing/typeof.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4564 Skip unicode array tests on ppc64le that trigger an LLVM bug
  numba/tests/test_unicode_array.py
Labels: 5 - Ready to merge

#4386 Implement np.count_nonzero
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4512 Raise specific error at typing time for iteration on >1D array.
  numba/tests/test_iteration.py
  numba/typing/builtins.py
Labels: 5 - Ready to merge

#4128 Add np.cross support
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4565 Fix typo in jit-compilation docs
  docs/source/reference/jit-compilation.rst
Labels: 5 - Ready to merge

#4576 Replace use of `np.prod` with `functools.reduce` for computing size from shape
  numba/cuda/cudadrv/devicearray.py
  numba/dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4593 Enable Azure CI batching
  azure-pipelines.yml
Labels: 5 - Ready to merge

#4353 Inspection tool to check what numba supports
  docs/source/conf.py
  docs/source/developer/listings.rst
  numba/help/__init__.py
  numba/help/inspector.py
  numba/tests/test_help.py
  numba/typing/templates.py
Labels: 5 - Ready to merge

#4518 add support for np.append
  docs/source/reference/numpysupported.rst
  numba/numpy_support.py
  numba/targets/arraymath.py
  numba/targets/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4548 Document numba.extending.intrinsic and inlining.
  docs/source/developer/index.rst
  docs/source/developer/inline_example.py
  docs/source/developer/inline_overload_example.py
  docs/source/developer/inlining.rst
  docs/source/extending/high-level.rst
  numba/decorators.py
  numba/typed_passes.py
Labels: 5 - Ready to merge

#4554 Refactor NRT C-API
  docs/source/developer/numba-runtime.rst
  docs/source/developer/repomap.rst
  numba/_helperlib.c
  numba/_helpermod.c
  numba/cext/cext.h
  numba/cext/dictobject.c
  numba/cext/dictobject.h
  numba/cext/listobject.c
  numba/cext/listobject.h
  numba/cext/utils.c
  numba/extending.py
  numba/pycc/cc.py
  numba/runtime/_nrt_pythonmod.c
  numba/runtime/context.py
  numba/runtime/nrt.c
  numba/runtime/nrt.h
  numba/runtime/nrt_external.h
  numba/tests/compile_with_pycc.py
  numba/tests/test_nrt.py
  numba/tests/test_pycc.py
  numba/unsafe/nrt.py
  setup.py
Labels: 5 - Ready to merge

#4592 Fix #4589. Just pass NULL for b2d_func for constant dynamic sharedme…
  numba/cuda/compiler.py
  numba/cuda/cudadrv/driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4621 Fix packaging issue due to missing numba/cext
  numba/cext/__init__.py
  numba/pycc/cc.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4607 add dependency list to docs
  docs/source/user/installing.rst
Labels: 5 - Ready to merge

#4614 Add documentation for implementing new compiler passes.
  docs/source/developer/compiler_pass_example.py
  docs/source/developer/custom_pipeline.rst
  docs/source/reference/envvars.rst
  numba/compiler.py
  numba/compiler_machinery.py
Labels: 5 - Ready to merge

#4472 Allow dtype input argument in np.sum
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_array_methods.py
  numba/types/functions.py
  numba/typing/arraydecl.py
  numba/typing/npydecl.py
Labels: 5 - Ready to merge

#4568 add np.array_equal support
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4556 0.46 scheduled deprecations
  docs/source/cuda/memory.rst
  docs/source/cuda/overview.rst
  docs/source/developer/repomap.rst
  docs/source/reference/deprecation.rst
  docs/source/reference/pysupported.rst
  docs/source/user/installing.rst
  numba/__init__.py
  numba/array_analysis.py
  numba/cuda/compiler.py
  numba/cuda/cuda_paths.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/envvars.py
  numba/cuda/tests/cudadrv/test_detect.py
  numba/cuda/tests/cudapy/test_smart_array.py
  numba/cuda/tests/nocuda/test_library_lookup.py
  numba/datamodel/models.py
  numba/smartarray.py
  numba/targets/base.py
  numba/targets/boxing.py
  numba/targets/imputils.py
  numba/targets/smartarray.py
  numba/tests/test_deprecations.py
  numba/tests/test_smart_array.py
  numba/types/npytypes.py
  numba/typing/typeof.py
Labels: 5 - Ready to merge

#4510 Make List.__getitem__ accept unsigned parameters
  numba/listobject.py
  numba/tests/test_listobject.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#4619 Implement math.{degrees, radians} for the CUDA target.
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_math.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA
