Repository numba/numba, pull requests merged in 2019-07, with the labels that each got.

#4241 remove unused import
  numba/typeinfer.py
Labels: 3 - Ready for Review

#4200 Add signature parameter to inspect_types
  numba/dispatcher.py
  numba/pretty_annotate.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#4224 Fix #4223. Looplifting error due to StaticSetItem in objectmode
  numba/compiler.py
  numba/tests/test_looplifting.py
Labels: 5 - Ready to merge

#4229 Make hashing cacheable
  numba/targets/hashing.py
  numba/tests/support.py
  numba/tests/test_caching.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4233 Fixes issue revealed by #4215
  numba/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4234 Raise informative error for np.kron array order
  docs/source/reference/numpysupported.rst
  numba/targets/linalg.py
  numba/tests/test_linalg.py
Labels: 5 - Ready to merge

#4239 Support len() of multi-dim arrays in array analysis
  numba/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge

#4252 fix typo on repomap
  docs/source/developer/repomap.rst
Labels: 5 - Ready to merge

#4253 fix typo in pysupported docs
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge

#4262 Resolves #4251.
  numba/array_analysis.py
Labels: 5 - Ready to merge

#4296 Slacken window function testing tol on ppc64le
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4295 Alter deprecation schedules
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge

#4291 Fix pickling of jitclass type
  numba/jitclass/boxing.py
  numba/tests/test_dictobject.py
  numba/tests/test_jitclasses.py
  numba/types/misc.py
Labels: 5 - Ready to merge

#4273 pin to MKL BLAS for testing to get consistent results
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, BuildFarm Passed

#4199 Extend `__cuda_array_interface__` with optional mask attribute, bump version to 1
  docs/source/cuda/cuda_array_interface.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4155 Make Parfors cacheable
  .flake8
  numba/annotations/type_annotations.py
  numba/compiler.py
  numba/npyufunc/parallel.py
  numba/npyufunc/parfor.py
  numba/npyufunc/ufuncbuilder.py
  numba/npyufunc/wrappers.py
  numba/targets/codegen.py
  numba/tests/parfors_cache_usecases.py
  numba/tests/test_parallel_backend.py
  numba/tests/test_parfors.py
  numba/tests/test_parfors_caching.py
  numba/tests/threading_backend_usecases.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4211 Developer docs for caching
  docs/source/developer/caching.rst
  docs/source/developer/index.rst
  docs/source/reference/envvars.rst
Labels: 5 - Ready to merge, doc

#4254 Add reference counting to register_dispatcher
  numba/tests/test_dispatcher.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#3691 Make TypingError abort compiling earlier
  .flake8
  numba/dispatcher.py
  numba/tests/test_dispatcher.py
  numba/typeinfer.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4077 Add np select
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4151 typed-list
  docs/source/developer/repomap.rst
  docs/source/reference/deprecation.rst
  docs/source/reference/pysupported.rst
  examples/typed_list_usage.py
  numba/_helperlib.c
  numba/_helpermod.c
  numba/_listobject.c
  numba/_listobject.h
  numba/dictobject.py
  numba/listobject.py
  numba/six.py
  numba/tests/test_dictobject.py
  numba/tests/test_listimpl.py
  numba/tests/test_listobject.py
  numba/tests/test_typedlist.py
  numba/typed/__init__.py
  numba/typed/typedlist.py
  numba/typedobjectutils.py
  numba/types/containers.py
  numba/typing/templates.py
  numba/typing/typeof.py
  numba/unsafe/refcount.py
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4300 AArch64 has no faulthandler package
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, BuildFarm Passed

#4302 Fix flake8 issue on master
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#4301 Fix integer literal bug in np.select impl.
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4303 Work around scipy bug 10206
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge

#4297 Update for 0.45.0RC1 release changelog
  CHANGE_LOG
  docs/source/reference/pysupported.rst
Labels: 3 - Ready for Review

#4318 Add supported platforms to the docs. Closes #4316
  README.rst
Labels: 5 - Ready to merge

#4311 Avoid deprecated use of inspect.getargspec
  numba/npyufunc/_internal.c
  numba/npyufunc/ufuncbuilder.py
  numba/tracing.py
Labels: 5 - Ready to merge

#4317 Add docs for ARMv8/AArch64
  docs/source/user/installing.rst
Labels: 3 - Ready for Review, 5 - Ready to merge

#4328 Replace GC macro with function call
  numba/_dynfunc.c
  numba/generators.py
Labels: 5 - Ready to merge

#4334 Update 0.45.0 changelog
  CHANGE_LOG
Labels: 5 - Ready to merge

#4371 Fix nump1.17 random function non-aliasing
  numba/targets/randomimpl.py
  numba/typing/randomdecl.py
Labels: 5 - Ready to merge

#4363 Fix np.interp for np1.17 nan handling
  .flake8
  numba/targets/arraymath.py
Labels: 5 - Ready to merge

#4357 Fix np1.17 isnan, isinf, isfinite ufuncs
  numba/targets/mathimpl.py
  numba/targets/npyfuncs.py
  numba/targets/ufunc_db.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#4354 Try to fix #4352.
  numba/cuda/cudadrv/devices.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_context_stack.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4338 Fix #4299. Parfors reduction vars not deleted.
  numba/npyufunc/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4325 accept scalar/0d-arrays
  docs/source/extending/mynorm.py
Labels: 5 - Ready to merge

#4350 Use process level locks for fork() only.
  numba/npyufunc/parallel.py
  numba/tests/orphaned_semaphore_usecase.py
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4383 Change log update for 0.45.1
  CHANGE_LOG
Labels: 5 - Ready to merge
