Repository numba/numba, pull requests merged in 2019-12, with the labels that each got.

#4916 fix Azure test failure detection on windows
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge

#4896 Specialise arange dtype on arch + python version.
  numba/targets/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge, BuildFarm Passed

#4881 fix refining list by using extend on an iterator
  numba/listobject.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#4901 fix typed list equals
  numba/listobject.py
  numba/targets/builtins.py
  numba/tests/test_builtins.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#4909 Fix some spelling typos
  .binstar.yml
  CHANGE_LOG
  docs/dagmap/jquery.graphviz.svg.js
  docs/source/cuda/faq.rst
  docs/source/cuda/intrinsics.rst
  docs/source/proposals/integer-typing.rst
  numba/_numba_common.h
  numba/_runtests.py
  numba/analysis.py
  numba/cext/dictobject.c
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba/dummyarray.py
  numba/inline_closurecall.py
  numba/ir_utils.py
  numba/npyufunc/_internal.c
  numba/npyufunc/gufunc_scheduler.cpp
  numba/stencil.py
  numba/targets/arrayobj.py
  numba/targets/codegen.py
  numba/targets/linalg.py
  numba/targets/listobj.py
  numba/tests/test_array_methods.py
  numba/tests/test_dispatcher.py
  numba/tests/test_listobject.py
  numba/tests/test_parfors.py
  numba/tests/test_typedlist.py
  numba/tests/test_ufuncs.py
  numba/types/functions.py
  numba/types/npytypes.py
  numba/unsafe/__init__.py
  numba/withcontexts.py
  tutorials/Numpy and numba.ipynb
Labels: 5 - Ready to merge

#4911 np.interp bugfix for float32 handling
  numba/targets/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#4839 Implement str.isalnum() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4780 Implement np.gcd and math.gcd
  docs/source/reference/numpysupported.rst
  docs/source/reference/pysupported.rst
  numba/targets/mathimpl.py
  numba/targets/npyfuncs.py
  numba/targets/ufunc_db.py
  numba/tests/test_builtins.py
  numba/tests/test_mathlib.py
  numba/tests/test_ufuncs.py
  numba/tests/test_unsafe_intrinsics.py
  numba/typing/builtins.py
  numba/typing/mathdecl.py
  numba/typing/npydecl.py
  numba/unsafe/numbers.py
Labels: 5 - Ready to merge

#4860 Implement str.index() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4836 Implement str.isprintable() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4840 Implement str.isalpha() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4861 Implement str.rindex() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4904 Implement np.lcm
  docs/source/reference/numpysupported.rst
  numba/targets/npyfuncs.py
  numba/targets/ufunc_db.py
  numba/tests/test_ufuncs.py
  numba/typing/npydecl.py
Labels: 5 - Ready to merge

#4695 Refactor `overload*` and support `jit_options` and `inline`
  numba/cgutils.py
  numba/charseq.py
  numba/extending.py
  numba/inline_closurecall.py
  numba/numpy_support.py
  numba/targets/arrayobj.py
  numba/targets/builtins.py
  numba/tests/pdlike_usecase.py
  numba/tests/test_extending.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_unicode.py
  numba/typed_passes.py
  numba/typing/context.py
  numba/typing/templates.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4858 Implement str.expandtabs() based on CPython
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#4947 Document jitclass with numba.typed use.
  docs/source/user/jitclass.rst
Labels: 5 - Ready to merge

#4946 Improve the error message for `raise <string>`.
  .flake8
  numba/rewrites/static_raise.py
  numba/tests/test_exceptions.py
Labels: 5 - Ready to merge

#4938 Improve errors / warnings for cuda vectorize decorator
  numba/cuda/tests/cudapy/test_vectorize_decor.py
  numba/npyufunc/deviceufunc.py
  numba/tests/npyufunc/test_errors.py
  numba/tests/npyufunc/test_vectorize_decor.py
  numba/tests/support.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4934 Fix fails in TestCudaWarpOperations
  numba/cuda/tests/cudapy/test_warp_ops.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4931 Add physical limits for CC 7.0 / 7.5 to autotune
  AUTHORS
  numba/cuda/cudadrv/autotune.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4818 Typed list faster copy
  numba/listobject.py
Labels: 5 - Ready to merge

#4838 Permit ravel('A') for contig device arrays in CUDA target
  numba/cuda/tests/cudadrv/test_array_attr.py
  numba/dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4756 Add parfor support for ndarray.fill.
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4090 Update to LLVM8 memset/memcpy intrinsic
  numba/cgutils.py
Labels: 5 - Ready to merge

#4910 loop canonicalisation and type aware tuple unroller/loop body versioning passes
  docs/source/reference/envvars.rst
  docs/source/reference/pysupported.rst
  numba/__init__.py
  numba/array_analysis.py
  numba/compiler.py
  numba/compiler_machinery.py
  numba/config.py
  numba/controlflow.py
  numba/datamodel/models.py
  numba/inline_closurecall.py
  numba/interpreter.py
  numba/ir.py
  numba/ir_utils.py
  numba/lowering.py
  numba/special.py
  numba/targets/base.py
  numba/targets/builtins.py
  numba/targets/codegen.py
  numba/targets/tupleobj.py
  numba/tests/test_array_analysis.py
  numba/tests/test_builtins.py
  numba/tests/test_comprehension.py
  numba/tests/test_dictobject.py
  numba/tests/test_dyn_array.py
  numba/tests/test_flow_control.py
  numba/tests/test_ir_utils.py
  numba/tests/test_lists.py
  numba/tests/test_mixed_tuple_unroller.py
  numba/tests/test_np_functions.py
  numba/tests/test_tuples.py
  numba/tests/test_typingerror.py
  numba/tests/test_unicode.py
  numba/typed_passes.py
  numba/typeinfer.py
  numba/types/__init__.py
  numba/types/containers.py
  numba/unicode.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4902 basic support for try except
  numba/byteflow.py
  numba/controlflow.py
  numba/dataflow.py
  numba/interpreter.py
  numba/ir.py
  numba/lowering.py
  numba/rewrites/static_raise.py
  numba/runtime/context.py
  numba/targets/callconv.py
  numba/tests/support.py
  numba/tests/test_dataflow.py
  numba/tests/test_flow_control.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
  numba/typeinfer.py
  numba/typing/context.py
  numba/unsafe/eh.py
Labels: 5 - Ready to merge

#4955 Move overload of literal_unroll to avoid circular dependency that breaks Python 2.7
  numba/special.py
  numba/targets/base.py
  numba/targets/literal.py
Labels: 5 - Ready to merge

#4962 Fix test error on windows
  numba/tests/test_try_except.py
Labels: 5 - Ready to merge

#4958 Add docs for `try..except`
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge, doc

#4961 Update hash(tuple) for Python 3.8.
  numba/targets/hashing.py
  numba/tests/test_hashing.py
Labels: 5 - Ready to merge

#4648 Handle 0 correctly as slice parameter.
  numba/array_analysis.py
  numba/parfor.py
  numba/tests/test_array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4973 Fixes a bug in the relabelling logic in literal_unroll.
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4854 Python3.8 looplifting
  numba/analysis.py
  numba/compiler.py
  numba/ir.py
  numba/tests/test_dispatcher.py
  numba/tests/test_jitmethod.py
  numba/tests/test_looplifting.py
  numba/tests/test_warnings.py
  numba/transforms.py
  numba/untyped_passes.py
Labels: 5 - Ready to merge

#4432 Bounds checking
  docs/source/reference/envvars.rst
  docs/source/reference/jit-compilation.rst
  numba/cgutils.py
  numba/compiler.py
  numba/config.py
  numba/cuda/compiler.py
  numba/cuda/cudaimpl.py
  numba/cuda/decorators.py
  numba/cuda/simulator/api.py
  numba/cuda/target.py
  numba/decorators.py
  numba/npyufunc/ufuncbuilder.py
  numba/roc/hsaimpl.py
  numba/targets/arraymath.py
  numba/targets/arrayobj.py
  numba/targets/base.py
  numba/targets/cpu.py
  numba/targets/npyimpl.py
  numba/targets/options.py
  numba/tests/test_boundscheck.py
  numba/tests/test_jit_module.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4715 Add `bool` overload for several types
  numba/targets/base.py
  numba/targets/builtins.py
  numba/tests/test_array_methods.py
  numba/tests/test_dictobject.py
  numba/tests/test_listobject.py
  numba/tests/test_sets.py
  numba/tests/test_unicode.py
  numba/tests/test_unicode_array.py
Labels: 5 - Ready to merge

#4768 Update typeconv error message to ask for sys.executable.
  numba/typeconv/typeconv.py
Labels: 5 - Ready to merge

#4977 Implement sort/sorted with key.
  numba/targets/listobj.py
  numba/targets/quicksort.py
  numba/tests/test_sort.py
  numba/typing/listdecl.py
Labels: 5 - Ready to merge

#4978 Fix overload_method problem with stararg
  numba/datamodel/models.py
  numba/dispatcher.py
  numba/tests/test_extending.py
  numba/types/containers.py
  numba/typing/templates.py
Labels: 5 - Ready to merge

#4935 Better handling of prange with multiple reductions on the same variable.
  numba/npyufunc/parfor.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4981 Add ind_to_const to enable fewer equivalence classes.
  numba/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4987 Add `is_internal` property to all Type classes.
  .flake8
  numba/tests/test_types.py
  numba/types/abstract.py
  numba/unicode.py
Labels: 5 - Ready to merge

#4920 fix creating list with JIT disabled
  numba/listobject.py
  numba/tests/test_listobject.py
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#4921 fix creating dict with JIT disabled
  numba/dictobject.py
  numba/tests/test_dictobject.py
  numba/typed/typeddict.py
Labels: 5 - Ready to merge

#4993 Update deprecations for 0.47
  buildscripts/condarecipe.local/mandel.py
  buildscripts/condarecipe.local/meta.yaml
  docs/source/reference/deprecation.rst
  numba/__init__.py
  numba/decorators.py
  numba/tests/test_api.py
  numba/tests/test_deprecations.py
Labels: 5 - Ready to merge

#4729 Allow array construction with mixed type shape tuples
  numba/targets/arrayobj.py
  numba/tests/test_dyn_array.py
Labels: 5 - Ready to merge

#4990 Implement sort on typed list
  numba/listobject.py
  numba/targets/iterators.py
  numba/tests/test_iteration.py
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#4991 Continuation of #4588
  numba/inline_closurecall.py
  numba/ir_utils.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4994 Remove xfail for test which has since had underlying issue fixed.
  numba/tests/test_try_except.py
Labels: 5 - Ready to merge

#4995 Change log update for 0.47.0
  CHANGE_LOG
Labels: 3 - Ready for Review
