Repository numba/numba, pull requests merged in 2020-10, with the labels that each got.

#6027 Support operators inlining in InlineOverloads
  numba/core/inline_closurecall.py
  numba/core/ir.py
  numba/core/ir_utils.py
  numba/core/typed_passes.py
  numba/tests/test_ir_inlining.py
Labels: 5 - Ready to merge

#6129 Extend Cudasim to support most of the memory functionality.
  docs/source/cuda/simulator.rst
  numba/cuda/simulator/__init__.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/simulator/cudadrv/devices.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_cuda_memory.py
  numba/cuda/tests/cudadrv/test_host_alloc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6166 Remove Python 2 compatibility from numba.core.utils
  LICENSES.third-party
  numba/core/base.py
  numba/core/caching.py
  numba/core/cgutils.py
  numba/core/interpreter.py
  numba/core/itanium_mangler.py
  numba/core/pythonapi.py
  numba/core/typeinfer.py
  numba/core/typing/builtins.py
  numba/core/typing/typeof.py
  numba/core/utils.py
  numba/np/arrayobj.py
  numba/np/numpy_support.py
  numba/tests/support.py
  numba/tests/test_cfunc.py
  numba/tests/test_chained_assign.py
  numba/tests/test_hashing.py
  numba/tests/test_mangling.py
  numba/tests/test_operators.py
  numba/tests/test_range.py
Labels: 5 - Ready to merge

#6203 Make find_callname only lookup functions that are likely part of NumPy.
  numba/core/ir_utils.py
Labels: 5 - Ready to merge

#6231 Remove compatibility mode
  docs/source/reference/envvars.rst
  numba/_dispatcher.c
  numba/core/compiler.py
  numba/core/config.py
  numba/core/dispatcher.py
  numba/core/inline_closurecall.py
  numba/core/object_mode_passes.py
  numba/core/typed_passes.py
  numba/testing/__init__.py
  numba/testing/main.py
  numba/tests/test_closure.py
  numba/tests/test_del.py
  numba/tests/test_generators.py
  numba/tests/test_lists.py
Labels: 5 - Ready to merge

#6252 Show channel URLs
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge

#6271 Support `ndarray` contains
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#6289 Refactor atomic test cases to reduce code duplication
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6296 Fix flake8 violations in numba.cuda module
  .flake8
  numba/cuda/api.py
  numba/cuda/codegen.py
  numba/cuda/cudadecl.py
  numba/cuda/cudamath.py
  numba/cuda/device_init.py
  numba/cuda/dispatcher.py
  numba/cuda/initialize.py
  numba/cuda/libdevice.py
  numba/cuda/nvvmutils.py
  numba/cuda/printimpl.py
  numba/cuda/random.py
  numba/cuda/simulator_init.py
  numba/cuda/stubs.py
  numba/cuda/target.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6297 Fix flake8 violations in numba.cuda.tests.cudapy module
  .flake8
  numba/cuda/tests/cudapy/test_alignment.py
  numba/cuda/tests/cudapy/test_array.py
  numba/cuda/tests/cudapy/test_array_args.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/cuda/tests/cudapy/test_blackscholes.py
  numba/cuda/tests/cudapy/test_casting.py
  numba/cuda/tests/cudapy/test_complex.py
  numba/cuda/tests/cudapy/test_complex_kernel.py
  numba/cuda/tests/cudapy/test_const_string.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/cudapy/test_errors.py
  numba/cuda/tests/cudapy/test_exception.py
  numba/cuda/tests/cudapy/test_fastmath.py
  numba/cuda/tests/cudapy/test_freevar.py
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/tests/cudapy/test_idiv.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/cuda/tests/cudapy/test_laplace.py
  numba/cuda/tests/cudapy/test_mandel.py
  numba/cuda/tests/cudapy/test_math.py
  numba/cuda/tests/cudapy/test_montecarlo.py
  numba/cuda/tests/cudapy/test_multigpu.py
  numba/cuda/tests/cudapy/test_multithreads.py
  numba/cuda/tests/cudapy/test_nondet.py
  numba/cuda/tests/cudapy/test_powi.py
  numba/cuda/tests/cudapy/test_print.py
  numba/cuda/tests/cudapy/test_py2_div_issue.py
  numba/cuda/tests/cudapy/test_random.py
  numba/cuda/tests/cudapy/test_record_dtype.py
  numba/cuda/tests/cudapy/test_slicing.py
  numba/cuda/tests/cudapy/test_sm.py
  numba/cuda/tests/cudapy/test_sync.py
  numba/cuda/tests/cudapy/test_userexc.py
  numba/cuda/tests/cudapy/test_vectorize.py
  numba/cuda/tests/cudapy/test_vectorize_scalar_arg.py
  numba/cuda/tests/cudapy/test_warp_ops.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6300 Un-skip tests that were skipped because of #4026.
  numba/tests/support.py
  numba/tests/test_linalg.py
  numba/tests/test_np_functions.py
  numba/tests/test_parfors_passes.py
  numba/tests/test_unicode_array.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6306 Fix flake8 in cuda atomic test from merge.
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge

#6299 Fix flake8 violations in numba.cuda.simulator
  .flake8
  numba/cuda/decorators.py
  numba/cuda/kernels/transpose.py
  numba/cuda/simulator/api.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/simulator/cudadrv/devices.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/nvvm.py
  numba/cuda/simulator/kernel.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/simulator/reduction.py
  numba/cuda/tests/cudasim/test_cudasim_issues.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6292 Document support for structured array attribute access
  docs/source/cuda/simulator.rst
  docs/source/reference/numpysupported.rst
Labels: 5 - Ready to merge, CUDA, doc

#5699 Implement np.split and np.array_split
  docs/source/reference/numpysupported.rst
  numba/cpython/unsafe/tuple.py
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
  numba/tests/test_unsafe_intrinsics.py
Labels: 5 - Ready to merge

#5741 CUDA: Add two-argument implementation of round()
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_intrinsics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6290 CUDA: Add support for complex power
  docs/source/cuda/cudapysupported.rst
  numba/cuda/libdevice.py
  numba/cuda/tests/cudapy/test_powi.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6298 Fix flake8 violations in numba.cuda.tests.cudadrv
  .flake8
  numba/cuda/tests/cudadrv/test_cuda_auto_context.py
  numba/cuda/tests/cudadrv/test_cuda_devicerecord.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/cuda/tests/cudadrv/test_deallocations.py
  numba/cuda/tests/cudadrv/test_events.py
  numba/cuda/tests/cudadrv/test_inline_ptx.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudadrv/test_pinned.py
  numba/cuda/tests/cudadrv/test_profiler.py
  numba/cuda/tests/cudadrv/test_select_device.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6316 Make IR inliner tests not self mutating.
  numba/tests/test_ir_inlining.py
Labels: 5 - Ready to merge

#6304 Support NumPy 1.19
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6042 CUDA: Lower launch overhead by launching kernel directly
  numba/cuda/compiler.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6006 Resolves incorrectly hoisted list in parfor.
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, ParallelAccelerator

#5900 Enable CUDA Unified Memory
  docs/source/cuda-reference/memory.rst
  docs/source/cuda/memory.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/drvapi.py
  numba/cuda/cudadrv/enums.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/tests/cudadrv/test_cuda_memory.py
  numba/cuda/tests/cudadrv/test_deallocations.py
  numba/cuda/tests/cudadrv/test_managed_alloc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6329 Flake8 fix for a CUDA test
  numba/cuda/tests/cudadrv/test_cuda_driver.py
Labels: 5 - Ready to merge

#6127 Fix race in reduction kernels on Volta, require CUDA 9, add syncwarp with default mask
  buildscripts/condarecipe.local/meta.yaml
  docs/source/cuda-reference/kernel.rst
  docs/source/cuda/overview.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudaimpl.py
  numba/cuda/kernels/reduction.py
  numba/cuda/stubs.py
  numba/cuda/tests/__init__.py
  numba/cuda/tests/cudadrv/test_runtime.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_reduction.py
  numba/cuda/tests/cudapy/test_sync.py
  numba/cuda/tests/cudapy/test_warp_ops.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6224 Add support for tuple concatenation to array analysis. (#5396 continued)
  numba/parfors/array_analysis.py
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#6295 Enhance inspect_cfg
  numba/core/codegen.py
  numba/core/dispatcher.py
Labels: 5 - Ready to merge

#6309 Add suitable file search path for BSDs.
  numba/misc/findlib.py
Labels: 5 - Ready to merge

#6310 Declare unofficial *BSD support
  README.rst
  docs/source/user/installing.rst
Labels: 5 - Ready to merge

#6324 PR 6208 continued
  docs/source/user/threading-layer.rst
  numba/np/ufunc/tbbpool.cpp
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge

#5609 Jitclass Infer Spec from Type Annotations
  .flake8
  docs/source/developer/repomap.rst
  docs/source/extending/interval-example.rst
  docs/source/extending/low-level.rst
  docs/source/reference/types.rst
  docs/source/user/jitclass.rst
  numba/__init__.py
  numba/core/extending.py
  numba/core/typing/asnumbatype.py
  numba/core/typing/typeof.py
  numba/experimental/jitclass/base.py
  numba/experimental/jitclass/decorators.py
  numba/misc/special.py
  numba/tests/doc_examples/test_jitclass.py
  numba/tests/test_asnumbatype.py
  numba/tests/test_jitclasses.py
  numba/tests/test_typeof.py
  numba/tests/test_typingerror.py
Labels: 5 - Ready to merge

#6145 Patch to fingerprint namedtuples.
  numba/_typeof.c
Labels: 5 - Ready to merge, performance - run time

#6325 Refactor code for atomic operations
  numba/cuda/cudadecl.py
Labels: 5 - Ready to merge, CUDA

#6331 Explicitly state that NUMBA_ENABLE_CUDASIM needs to be set before import
  docs/source/cuda/simulator.rst
Labels: 5 - Ready to merge, CUDA, doc

#6342 Fix docs on literally usage.
  numba/tests/doc_examples/test_literally_usage.py
Labels: 5 - Ready to merge

#6212 Fix for objmode recompilation issue
  numba/core/dispatcher.py
Labels: 5 - Ready to merge

#6307 Remove restrictions on SVML version due to bug in LLVM SVML CC
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge

#6318 PR #5892 continued
  numba/core/ir_utils.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#6337 Implements `key` on `types.TypeRef`
  numba/core/types/abstract.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#6338 Direct user questions to Discourse instead of the Google Group.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 5 - Ready to merge

#6341 Re roll 6279
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#6348 doc: fix typo in jitclass.rst ("initilising" -> "initialising")
  docs/source/user/jitclass.rst
Labels: 5 - Ready to merge, doc

#5560 Record subtyping
  docs/source/reference/numpysupported.rst
  numba/_dispatcher.c
  numba/core/types/npytypes.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge

#6354 Bump llvmlite to 0.35. series.
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#6266 Use custom LLVM refcount pruning pass
  docs/source/reference/envvars.rst
  numba/core/callconv.py
  numba/core/codegen.py
  numba/core/config.py
  numba/core/errors.py
  numba/core/runtime/nrt.c
  numba/core/typed_passes.py
  numba/tests/test_refop_pruning.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#6357 Fix enumerate invalid decref
  numba/cpython/iterators.py
Labels: 5 - Ready to merge

#6335 Split optimisation passes.
  numba/core/codegen.py
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge

#6340 CUDA: Fix #6339, performance regression launching specialized kernels
  numba/cuda/compiler.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6152 CUDA: Provide wrappers for all libdevice functions, and fix typing of math function (#4618)
  .flake8
  docs/source/cuda-reference/index.rst
  docs/source/cuda-reference/libdevice.rst
  numba/cuda/cudaimpl.py
  numba/cuda/libdevice.py
  numba/cuda/libdevicedecl.py
  numba/cuda/libdevicefuncs.py
  numba/cuda/libdeviceimpl.py
  numba/cuda/mathimpl.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_libdevice.py
  numba/cuda/tests/cudapy/test_math.py
  numba/testing/main.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6278 Improve typed list performance.
  numba/_helpermod.c
  numba/cext/listobject.c
  numba/cext/listobject.h
  numba/tests/test_typedlist.py
  numba/typed/listobject.py
Labels: 5 - Ready to merge

#6294 Make return type propagate to all return variables
  numba/core/lowering.py
  numba/core/typeinfer.py
  numba/tests/test_typeinfer.py
Labels: 5 - Ready to merge

#6359 Fixes typed list indexing on 32bit
  numba/tests/test_listobject.py
  numba/typed/listobject.py
Labels: 5 - Ready to merge

#6275 Switch on SLP vectorize.
  docs/source/reference/envvars.rst
  numba/core/codegen.py
  numba/core/config.py
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge

#6319 Permit switching off boundschecking when debug is on.
  docs/source/user/troubleshoot.rst
  numba/core/cpu.py
  numba/core/decorators.py
  numba/core/options.py
  numba/tests/test_jit_module.py
Labels: 5 - Ready to merge

#6362 Move llvmlite support in README to 0.35
  README.rst
Labels: 5 - Ready to merge

#6363 Note that reference counted types are not permitted in set().
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge

#6364 Move deprecation schedules for 0.52
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge

#6365 Update CHANGE_LOG for 0.52.0
  CHANGE_LOG
Labels: 5 - Ready to merge

#6380 Only test managed allocations on Linux
  numba/cuda/api.py
  numba/cuda/tests/cudadrv/test_managed_alloc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6378 Fix incorrect CPU override in vectorization test.
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6379 Use O0 to enable inline and not affect loop-vectorization by later O3…
  numba/core/codegen.py
Labels: 5 - Ready to merge

#6384 Fix failing tests to match on platform invariant int spelling.
  numba/tests/test_dyn_array.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6390 Updates inspect_cfg
  numba/core/codegen.py
Labels: 5 - Ready to merge

#6408 Don't do array analysis for tuples that contain arrays.
  numba/parfors/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#6396 Remove hard dependency on tbb package.
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge

#6419 Update CHANGE_LOG for 0.52.0rc2
  CHANGE_LOG
Labels: 3 - Ready for Review

#6428 Cherrypicks for 0.52.0rc2
  CHANGE_LOG
  buildscripts/condarecipe.local/meta.yaml
  numba/core/codegen.py
  numba/cuda/api.py
  numba/cuda/tests/cudadrv/test_managed_alloc.py
  numba/parfors/array_analysis.py
  numba/tests/test_dyn_array.py
  numba/tests/test_parfors.py
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge
