Repository numba/numba, pull requests merged in 2020-07, with the labels that each got.

#5940 Add discourse badge
  README.rst
Labels: 5 - Ready to merge

#5956 Update numba_sysinfo.py
  numba/misc/numba_sysinfo.py
Labels: 5 - Ready to merge

#5935 Fix default arguments with multiprocessing
  numba/core/serialize.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#5925 Use np.inf and -np.inf for max and min float values respectively.
  numba/cpython/builtins.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5857 CUDA docs: Add notes on resetting the EMM plugin
  docs/source/cuda/external-memory.rst
Labels: 5 - Ready to merge, CUDA, doc

#5841 cleanup: Use PythonAPI.bool_from_bool in more places
  numba/core/boxing.py
  numba/core/pylowering.py
  numba/core/pythonapi.py
Labels: 5 - Ready to merge

#5972 fix flake8 for numba/runtests.py
  .flake8
  numba/runtests.py
Labels: 5 - Ready to merge

#5963 Fix broken link to numpy ufunc signature docs
  docs/source/reference/jit-compilation.rst
Labels: 5 - Ready to merge

#5952 Fix "Internal error ... local variable 'errstr' referenced before assignment during BoundFunction(...)"
  numba/core/types/functions.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge

#5946 Implement literal dictionaries and lists.
  docs/source/reference/pysupported.rst
  numba/core/analysis.py
  numba/core/boxing.py
  numba/core/datamodel/models.py
  numba/core/interpreter.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/typeinfer.py
  numba/core/types/abstract.py
  numba/core/types/containers.py
  numba/core/typing/builtins.py
  numba/cpython/listobj.py
  numba/cpython/tupleobj.py
  numba/misc/literal.py
  numba/tests/doc_examples/test_literal_container_usage.py
  numba/tests/test_dictobject.py
  numba/tests/test_dyn_array.py
  numba/tests/test_lists.py
  numba/tests/test_tuples.py
  numba/typed/dictobject.py
  numba/typed/typeddict.py
  numba/typed/typedobjectutils.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5978 Add structref as a mutable struct that is pass-by-ref
  .flake8
  docs/source/developer/repomap.rst
  numba/core/datamodel/models.py
  numba/core/types/containers.py
  numba/experimental/structref.py
  numba/tests/test_struct_ref.py
Labels: 5 - Ready to merge

#5995 Update setup.py with new llvmlite versions
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5674 Fix #3955. Allow `with objmode` to be cached
  .flake8
  LICENSES.third-party
  azure-pipelines.yml
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/developer/caching.rst
  docs/source/developer/repomap.rst
  docs/source/user/installing.rst
  numba/core/bytecode.py
  numba/core/caching.py
  numba/core/callwrapper.py
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/dispatcher.py
  numba/core/environment.py
  numba/core/extending.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/pythonapi.py
  numba/core/serialize.py
  numba/cuda/compiler.py
  numba/np/ufunc/dufunc.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/test_dispatcher.py
  numba/tests/test_extending.py
  numba/tests/test_withlifting.py
  numba/typed/typeddict.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#5993 Docs for structref
  docs/source/extending/high-level.rst
  numba/core/types/containers.py
  numba/experimental/structref.py
  numba/tests/doc_examples/test_structref_usage.py
Labels: 4 - Waiting on CI

#5996 Set lower bound for llvmlite to 0.33
  setup.py
Labels: 4 - Waiting on CI

#5619 Add support for multi-output ufuncs
  docs/source/reference/numpysupported.rst
  numba/core/typing/npydecl.py
  numba/np/npyfuncs.py
  numba/np/npyimpl.py
  numba/np/numpy_support.py
  numba/np/ufunc/array_exprs.py
  numba/np/ufunc/dufunc.py
  numba/np/ufunc_db.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#5834 Fix the is operator on Ellipsis
  numba/cpython/builtins.py
  numba/tests/test_operators.py
Labels: 5 - Ready to merge

#5893 Allocate 1D iteration space one at a time for more even distribution.
  numba/np/ufunc/gufunc_scheduler.cpp
Labels: 5 - Ready to merge

#5975 restructure communication section
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge, doc

#5526 Impl. np.asarray(literal)
  numba/np/arraymath.py
  numba/np/numpy_support.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#5879 Fix erroneous input mutation in linalg routines
  numba/np/linalg.py
  numba/tests/test_linalg.py
Labels: 5 - Ready to merge

#6004 Fix problem in branch pruning with LiteralStrKeyDict
  numba/core/types/abstract.py
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge

#6008 Small fix so bullet points are rendered by sphinx
  docs/source/reference/types.rst
Labels: 5 - Ready to merge

#5944 re-enable OpenMP in wheels
  setup.py
Labels: 5 - Ready to merge

#5960 Setting mypy on CI
  .gitignore
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
  docs/source/developer/contributing.rst
  mypy.ini
  numba/core/types/abstract.py
Labels: 5 - Ready to merge

#6016 Fixes change of list spelling in a cuda test.
  numba/cuda/tests/cudapy/test_sm_creation.py
Labels: 5 - Ready to merge, CUDA

#6013 emphasize cuda kernel functions are asynchronous
  docs/source/cuda/kernels.rst
Labels: 5 - Ready to merge, CUDA, doc

#6036 Update deprecation doc from numba.errors to numba.core.errors
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge

#6020 CUDA: Fix #5820, adding atomic nanmin / nanmax
  numba/cuda/cudadecl.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudaimpl.py
  numba/cuda/nvvmutils.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, CUDA

#5819 Add support for CUDA 11 and Ampere / CC 8.0
  docs/source/cuda-reference/host.rst
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/error.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudadrv/rtapi.py
  numba/cuda/cudadrv/runtime.py
  numba/cuda/device_init.py
  numba/cuda/simulator/__init__.py
  numba/cuda/simulator/cudadrv/runtime.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudadrv/test_runtime.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/cudapy/test_warp_ops.py
Labels: 5 - Ready to merge, CUDA

#5359 Remove special-casing of 0d arrays
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudaimpl.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/target.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/roc/hsaimpl.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5709 CUDA: Refactoring of cuda.jit and kernel / dispatcher abstractions
  docs/source/cuda-reference/kernel.rst
  numba/cuda/compiler.py
  numba/cuda/decorators.py
  numba/cuda/dispatcher.py
  numba/cuda/errors.py
  numba/cuda/initialize.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5851 CUDA EMM enhancements - add default get_ipc_handle implementation, skip a test conditionally
  docs/source/cuda/external-memory.rst
  numba/cuda/cudadrv/driver.py
  numba/cuda/device_init.py
  numba/cuda/tests/cudadrv/test_context_stack.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5761 Add implmentation for int types for isnan and isinf for CUDA
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_math.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5826 CUDA: Add function to get SASS for kernels
  docs/source/cuda-reference/kernel.rst
  numba/cuda/compiler.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_inspect.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5846 CUDA: Allow disabling NVVM optimizations, and fix debug issues
  numba/core/debuginfo.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/decorators.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_debuginfo.py
  numba/cuda/tests/cudapy/test_optimization.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5856 Add support for conversion of inplace_binop to parfor.
  numba/core/cpu_options.py
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#6030 CUDA: Don't optimize IR before sending it to NVVM
  numba/cuda/codegen.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/nocuda/test_nvvm.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6052 Fix dtype for atomic_add_double tests
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6057 fix aarch64/python_3.8 failure on master
  numba/tests/test_stencils.py
Labels: 5 - Ready to merge

#5980 Deprecate target kwarg for numba.jit.
  docs/source/reference/deprecation.rst
  numba/core/decorators.py
  numba/np/ufunc/dufunc.py
  numba/np/ufunc/ufuncbuilder.py
Labels: 5 - Ready to merge, BuildFarm Passed
