Repository numba/numba, pull requests merged in 2020-05, with the labels that each got.

#5653 Update doc with respect to try-finally case
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge

#5669 Update example in 5m guide WRT SSA type stability.
  docs/source/user/5minguide.rst
Labels: 5 - Ready to merge

#5676 Restore `numba.types` as public API
  numba/core/utils.py
  numba/tests/test_moved_modules.py
  numba/types/__init__.py
Labels: 5 - Ready to merge

#5682 Update CHANGE_LOG for 0.49.1
  CHANGE_LOG
Labels: 5 - Ready to merge

#5689 Fix bug in unified_function_type (issue 5685)
  numba/core/utils.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#5437 Fix #5429: Exception using `.get_ipc_handle(...)` on array from `as_cuda_array(...)
  numba/cuda/cudadrv/driver.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba/cuda/tests/cudapy/test_ipc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5478 Fix #5471. Issue with omitted type not recognized as literal value.
  numba/core/lowering.py
  numba/core/typeinfer.py
  numba/core/types/misc.py
  numba/core/typing/builtins.py
  numba/core/typing/context.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#5558 CUDA: Only release primary ctx if retained
  numba/cuda/cudadrv/driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5602 Fix segfault caused by pop from numba.typed.List
  numba/_helpermod.c
  numba/cext/listobject.c
  numba/cext/listobject.h
  numba/tests/test_listimpl.py
  numba/tests/test_typedlist.py
  numba/typed/listobject.py
Labels: 5 - Ready to merge

#5616 Simplify the ufunc kernel registration
  numba/np/npyimpl.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#5645 Fix SSA redundant CFG computation
  numba/core/ssa.py
Labels: 5 - Ready to merge

#5694 Skip part of slice array analysis if any part is not analyzable.
  numba/parfors/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5697 Fix usedef issue with parfor loopnest variables.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5704 CUDA Eager compilation: Fix max_registers kwarg
  numba/cuda/decorators.py
  numba/cuda/tests/cudadrv/test_linker.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5464 Jitclass drops annotations to avoid error
  numba/experimental/jitclass/base.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#5060 Enables np.sum for timedelta64
  numba/core/typing/builtins.py
  numba/core/typing/npydecl.py
  numba/np/npyimpl.py
  numba/np/numpy_support.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge

#5347 CUDA: Provide more stream constructors
  docs/source/cuda-reference/host.rst
  docs/source/cuda/memory.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/drvapi.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5481 CUDA: Replace macros with typing and lowering implementations
  numba/core/base.py
  numba/core/typing/arraydecl.py
  numba/core/typing/npydecl.py
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/initialize.py
  numba/cuda/models.py
  numba/cuda/stubs.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_macro.py
  numba/cuda/tests/cudapy/test_sm_creation.py
  numba/cuda/types.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5573 CUDA: Skip tests under cuda-memcheck that hang it
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_detect.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/cuda/tests/cudapy/test_multithreads.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5705 A fix for cases where SSA looks like a reduction variable.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5714 Fix bug in test
  numba/testing/main.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge

#5556 CUDA: Make atomic semantics match Python / NumPy, and fix #5458
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5686 Fix issue with SSA not minimal
  numba/core/ssa.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge

#5700 Make it easier to understand type inference: add SSA dump, use for DEBUG_TYPEINFER
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/core/ssa.py
  numba/core/untyped_passes.py
Labels: 5 - Ready to merge

#5718 CUDA lib path tests: unset CUDA_PATH when CUDA_HOME unset
  numba/cuda/tests/nocuda/test_library_lookup.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5225 Adjust interpreter to make conditionals predicates via bool() call.
  numba/core/analysis.py
  numba/core/interpreter.py
  numba/core/typeinfer.py
  numba/cpython/builtins.py
  numba/np/arrayobj.py
  numba/parfors/array_analysis.py
  numba/tests/test_analysis.py
  numba/tests/test_conditions_as_predicates.py
Labels: 5 - Ready to merge

#5549 Check type getitem
  numba/core/types/abstract.py
  numba/core/utils.py
  numba/stencils/stencil.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#5738 Unbreak master on buildfarm
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5591 Fix #5525 Add figure for total memory to `numba -s` output.
  numba/misc/numba_entry.py
  numba/misc/numba_sysinfo.py
  numba/tests/test_cli.py
  numba/tests/test_sysinfo.py
Labels: 5 - Ready to merge

#5764 fix flake8 errors
  numba/core/cgutils.py
  numba/core/extending.py
  numba/core/types/function_type.py
  numba/cpython/hashing.py
  numba/cpython/unicode.py
  numba/cpython/unicode_support.py
  numba/tests/error_usecases.py
  numba/tests/inlining_usecases.py
  numba/tests/npyufunc/test_dufunc.py
  numba/tests/pycc_distutils_usecase/nested/source_module.py
  numba/tests/test_conditions_as_predicates.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_listobject.py
  numba/tests/test_mixed_tuple_unroller.py
  numba/tests/test_num_threads.py
  numba/tests/test_numbers.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#5673 Fix inliners to run all passes on IR and clean up correctly.
  numba/core/compiler.py
  numba/core/inline_closurecall.py
  numba/core/ir.py
  numba/core/typed_passes.py
  numba/core/typing/templates.py
  numba/core/untyped_passes.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_mixed_tuple_unroller.py
Labels: 5 - Ready to merge

#5717 Initialise Numba extensions ahead of any compilation starting.
  numba/core/dispatcher.py
  numba/tests/test_entrypoints.py
Labels: 5 - Ready to merge

#5768 Interval example: fix import
  docs/source/extending/interval-example.rst
Labels: 5 - Ready to merge, doc
