Repository numba/numba, pull requests merged in 2020-06, with the labels that each got.

#5702 Fixes for LLVM 9
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  numba/core/codegen.py
  numba/core/runtime/nrtopt.py
  requirements.txt
  setup.py
Labels: 3 - Ready for Review

#5561 CUDA: Add function for compiling to PTX (+ other small fixes)
  .flake8
  docs/source/cuda-reference/host.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/__init__.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/simulator/compiler.py
  numba/cuda/tests/cudapy/test_compiler.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5721 Fix array iterator layout.
  numba/core/types/iterators.py
  numba/tests/test_array_iterators.py
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#5757 Force LLVM to use ZMM registers for vectorization.
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5758 Support NumPy 1.18
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  numba/np/arraymath.py
  numba/np/npdatetime.py
  numba/np/npyimpl.py
  numba/np/ufunc_db.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#5781 Moving record array examples to a test module
  docs/source/reference/numpysupported.rst
  numba/tests/doc_examples/test_rec_array.py
Labels: 5 - Ready to merge

#5791 Fix up no cgroups problem
  numba/misc/numba_sysinfo.py
Labels: 5 - Ready to merge

#5795 Restore refct removal pass and make it strict
  docs/source/developer/repomap.rst
  numba/core/callconv.py
  numba/core/lowering.py
  numba/core/removerefctpass.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#5800 Fix LLVM 9 IR for NVVM
  numba/cuda/cudadrv/nvvm.py
Labels: 5 - Ready to merge, CUDA

#5803 CUDA Update expected error messages to fix #5797
  numba/cuda/tests/cudapy/test_sm_creation.py
Labels: 5 - Ready to merge, CUDA

#5506 Jitclass static methods
  docs/source/user/jitclass.rst
  numba/core/types/misc.py
  numba/experimental/jitclass/base.py
  numba/experimental/jitclass/boxing.py
  numba/tests/doc_examples/test_jitclass.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#5807 Skip failing test on POWER8 due to PPC CTR Loop problem.
  numba/tests/test_linalg.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5810 Update CHANGE_LOG for 0.50
  CHANGE_LOG
Labels: 5 - Ready to merge

#5815 Pin llvmlite to 0.33
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, BuildFarm Passed

#5732 CUDA Docs: document `forall` method of kernels
  docs/source/cuda-reference/kernel.rst
  numba/cuda/compiler.py
Labels: 5 - Ready to merge, CUDA, doc

#5763 Support minlength argument to np.bincount
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#5779 Return zero array from np.dot when the arguments are empty.
  numba/np/linalg.py
  numba/tests/test_linalg.py
Labels: 5 - Ready to merge

#5782 Host docs on Read the Docs
  .readthedocs.yml
  docs/requirements.txt
Labels: 5 - Ready to merge

#5783 Make np.divide and np.remainder code more similar
  numba/np/npyfuncs.py
Labels: 5 - Ready to merge

#5796 Add implementation for np.positive
  numba/core/typing/npydecl.py
  numba/np/ufunc_db.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#5830 doc: Mention that caching uses pickle
  docs/source/developer/caching.rst
Labels: 5 - Ready to merge

#5838 Ensure `Dispatcher.__eq__` always returns a bool
  numba/core/types/functions.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#5852 CUDA: Fix `cuda.test()`
  numba/cuda/__init__.py
Labels: 5 - Ready to merge, CUDA

#5859 CUDA: Fix reduce docs and style improvements
  docs/source/cuda/reduction.rst
  numba/cuda/kernels/reduction.py
Labels: 5 - Ready to merge, CUDA, doc

#5862 Do not leak loop iteration variables into the numba.np.npyimpl namespace
  numba/np/npyimpl.py
Labels: 5 - Ready to merge

#5711 Division with timedelta input
  numba/np/numpy_support.py
  numba/tests/test_array_exprs.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge

#5808 Fix 5665 Block jit(nopython=True, forceobj=True) and suppress njit(forceobj=True)
  numba/core/decorators.py
  numba/tests/test_api.py
Labels: 5 - Ready to merge

#5861 Added except for possible Windows get_terminal_size exception
  numba/core/types/functions.py
Labels: 5 - Ready to merge

#5869 Update repomap
  docs/source/developer/repomap.rst
Labels: 5 - Ready to merge

#5882 Type check function in jit decorator
  numba/core/decorators.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#5876 Improve undefined variable error message
  numba/core/typeinfer.py
  numba/tests/test_errorhandling.py
  numba/tests/test_typingerror.py
Labels: 5 - Ready to merge

#5884 Update the deprecation notices for 0.50.1
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge

#5850 Updates the "New Issue" behaviour to better redirect users.
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 5 - Ready to merge

#5912 Fix bad attr access on certain typing templates breaking exceptions.
  .flake8
  numba/core/types/functions.py
  numba/core/typing/templates.py
  numba/cuda/compiler.py
  numba/cuda/tests/cudapy/test_errors.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge

#5889 Fixes literally not forcing re-dispatch for inline='always'
  numba/core/typing/templates.py
  numba/tests/test_ir_inlining.py
Labels: 5 - Ready to merge

#5914 Update change_log for 0.50.1
  CHANGE_LOG
Labels: 5 - Ready to merge

#5913 Update change_log for 0.50.1
  CHANGE_LOG
Labels: 5 - Ready to merge

#5918 Fix cuda test due to #5876
  numba/core/typeinfer.py
Labels: 3 - Ready for Review, CUDA, Pending BuildFarm

#5919 Update changelog 0.50.1
  CHANGE_LOG
Labels: 3 - Ready for Review

#5920 Update master changelog for latest change in 0.50.1
  CHANGE_LOG
Labels: 5 - Ready to merge
