Repository numba/numba, pull requests merged in 2020-04, with the labels that each got.

#5455 Move to llvmlite 0.32.*
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  requirements.txt
  setup.py
Labels: 2 - In Progress

#5450 Docs: remove numbers and add titles to TOC
  docs/source/index.rst
Labels: 5 - Ready to merge

#5453 fix building docs on windows
  docs/make.bat
Labels: 5 - Ready to merge

#5454 Don't warn for numba.experimental.jitclass
  numba/__init__.py
  numba/experimental/jitclass/decorators.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#5480 Fix for #5477, literal_unroll KeyError searching for getitems
  numba/core/untyped_passes.py
  numba/tests/test_mixed_tuple_unroller.py
Labels: 5 - Ready to merge

#5485 Show the offending module in "no direct replacement" error message
  numba/core/errors.py
  numba/tests/test_refactor_moves.py
Labels: 5 - Ready to merge

#5488 Add missing `numba.config` shim
  numba/config.py
  numba/tests/test_refactor_moves.py
Labels: 5 - Ready to merge

#5489 docs: fix rendering of nested bulleted list
  docs/source/developer/environment.rst
Labels: 5 - Ready to merge

#5495 Fix missing null initializer for variable after phi strip
  numba/core/config.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/pylowering.py
  numba/core/ssa.py
  numba/core/typed_passes.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge

#5498 Make the shim deprecation warnings work on python 3.6 too
  numba/analysis.py
  numba/array_analysis.py
  numba/cgutils.py
  numba/compiler.py
  numba/compiler_machinery.py
  numba/config.py
  numba/core/errors.py
  numba/datamodel/__init__.py
  numba/datamodel/models.py
  numba/decorators.py
  numba/dictobject.py
  numba/dispatcher.py
  numba/errors.py
  numba/inline_closurecall.py
  numba/ir.py
  numba/ir_utils.py
  numba/lowering.py
  numba/npdatetime.py
  numba/numpy_support.py
  numba/parfor.py
  numba/pythonapi.py
  numba/rewrites/__init__.py
  numba/runtime/__init__.py
  numba/runtime/nrt.py
  numba/stencil.py
  numba/stencilparfor.py
  numba/targets/__init__.py
  numba/targets/arraymath.py
  numba/targets/arrayobj.py
  numba/targets/boxing.py
  numba/targets/builtins.py
  numba/targets/callconv.py
  numba/targets/cpu.py
  numba/targets/hashing.py
  numba/targets/imputils.py
  numba/targets/listobj.py
  numba/targets/npdatetime.py
  numba/targets/options.py
  numba/targets/registry.py
  numba/targets/setobj.py
  numba/targets/slicing.py
  numba/targets/ufunc_db.py
  numba/tests/test_refactor_moves.py
  numba/typeconv.py
  numba/typed_passes.py
  numba/typedobjectutils.py
  numba/typeinfer.py
  numba/types/__init__.py
  numba/typing/__init__.py
  numba/typing/arraydecl.py
  numba/typing/builtins.py
  numba/typing/collections.py
  numba/typing/ctypes_utils.py
  numba/typing/npydecl.py
  numba/typing/templates.py
  numba/typing/typeof.py
  numba/unicode.py
  numba/unsafe/ndarray.py
  numba/untyped_passes.py
  numba/utils.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5527 Attempt to fix #5518
  numba/core/typeinfer.py
  numba/tests/test_globals.py
Labels: 5 - Ready to merge

#5529 PR #5473 continued
  docs/source/reference/types.rst
  numba/core/types/containers.py
  numba/core/types/functions.py
  numba/core/utils.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#5532 Make `numba.<mod>` available without an import
  numba/__init__.py
  numba/annotations.py
  numba/appdirs.py
  numba/bytecode.py
  numba/byteflow.py
  numba/caching.py
  numba/callwrapper.py
  numba/charseq.py
  numba/compiler_lock.py
  numba/consts.py
  numba/controlflow.py
  numba/core/errors.py
  numba/dataflow.py
  numba/debuginfo.py
  numba/entrypoints.py
  numba/funcdesc.py
  numba/generators.py
  numba/interpreter.py
  numba/itanium_mangler.py
  numba/listobject.py
  numba/object_mode_passes.py
  numba/postproc.py
  numba/pylowering.py
  numba/serialize.py
  numba/sigutils.py
  numba/special.py
  numba/targets/__init__.py
  numba/tests/test_refactor_moves.py
  numba/tracing.py
  numba/transforms.py
  numba/unicode_support.py
  numba/withcontexts.py
Labels: 5 - Ready to merge

#5538 Update CHANGE_LOG for 0.49.0rc2
  CHANGE_LOG
Labels: 3 - Ready for Review

#5436 Fix #5408: test_set_registers_57 fails on Maxwell
  numba/cuda/tests/cudadrv/test_linker.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5457 implement repr for untyped lists
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#5505 Better error message if __init__ returns value
  numba/experimental/jitclass/base.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#5542 Fixes RC2 module shim bug
  numba/postproc.py
  numba/tests/test_refactor_moves.py
Labels: 5 - Ready to merge

#5548 Fix #5537 Removed reference to `platform.linux_distribution`
  numba/misc/numba_entry.py
Labels: 5 - Ready to merge

#5519 CUDA: Silence the test suite - Fix #4809, remove autojit, delete prints
  numba/cuda/decorators.py
  numba/cuda/device_init.py
  numba/cuda/dispatcher.py
  numba/cuda/random.py
  numba/cuda/simulator/api.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
  numba/cuda/tests/cudapy/test_autojit.py
  numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
  numba/cuda/tests/cudapy/test_errors.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/cuda/tests/cudapy/test_serialize.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5459 Fixes issue 5448
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#5555 Fix #5515 by reverting changes to ArrayAnalysis
  numba/parfors/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge

#5557 First-class function call cannot use keyword arguments
  numba/core/types/function_type.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#5568 Add skip to entrypoint test on windows
  numba/tests/test_entrypoints.py
Labels: 5 - Ready to merge

#5567 Fixes to the change log post 0.49.0rc2
  CHANGE_LOG
Labels: 3 - Ready for Review

#5569 Fix RewriteConstGetitems not registering calltype for new expr
  .flake8
  numba/core/rewrites/static_getitem.py
  numba/tests/test_extending_types.py
Labels: 5 - Ready to merge

#5574 Update CHANGELOG for 0.49 wrt final patches
  CHANGE_LOG
Labels: 3 - Ready for Review

#5546 DOC: Add documentation about cost model to inlining notes.
  docs/source/developer/inlining.rst
Labels: 5 - Ready to merge

#5581 Revert #5568
  numba/tests/test_entrypoints.py
Labels: 5 - Ready to merge

#5578 Implement math.modf for CUDA target
  docs/source/cuda/cudapysupported.rst
  numba/cuda/cudamath.py
  numba/cuda/libdevice.py
  numba/cuda/tests/cudapy/test_math.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5388 CUDA: Fix OOB write in test_round{f4,f8}
  numba/cuda/tests/cudapy/test_intrinsics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5517 Fix numba.typed.List extend for singleton and empty iterable
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#5390 add error handling for lookup_module
  numba/core/funcdesc.py
  numba/tests/test_funcdesc.py
Labels: 5 - Ready to merge

#5587 Fixed #5586 Threading Implementation Typos
  docs/source/developer/threading_implementation.rst
Labels: 5 - Ready to merge

#5614 Fix invalid type in resolve for comparison expr in parfors.
  numba/parfors/parfor.py
Labels: 5 - Ready to merge

#5627 Fixes #5623, SSA local def scan based on invalid equality assumption.
  numba/core/ssa.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge

#5629 Fixes naming error in array_exprs
  numba/np/ufunc/array_exprs.py
  numba/tests/test_array_exprs.py
Labels: 5 - Ready to merge

#5624 Fix erroneous rewrite of predicate to bit const on prune.
  numba/core/analysis.py
  numba/tests/test_analysis.py
Labels: 5 - Ready to merge

#5592 Fixes #5583 Remove references to cffi_support from docs and examples
  .flake8
  docs/source/reference/pysupported.rst
  docs/source/user/cfunc.rst
  examples/notebooks/Accessing C Struct Data.ipynb
Labels: 5 - Ready to merge

#5638 Make literal_unroll function work as a freevar.
  numba/core/untyped_passes.py
  numba/tests/test_mixed_tuple_unroller.py
Labels: 5 - Ready to merge

#5648 Unset the memory manager after EMM Plugin tests
  numba/cuda/tests/cudadrv/test_emm_plugins.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5652 Pin to sphinx=2.4.4 to avoid problem with C declaration
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge

#5630 Fix #5570. Incorrect race variable detection due to SSA naming.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5651 Fix some SSA issues
  numba/core/interpreter.py
  numba/core/ssa.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge

#5658 Explicit bail out in `unified_function_type`
  numba/core/utils.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#5626 Fix unifying undefined first class function types issue.
  numba/core/utils.py
  numba/tests/test_function_type.py
Labels: 4 - Waiting on author

#5657 Update CHANGE_LOG for 0.49.1
  CHANGE_LOG
Labels: 5 - Ready to merge
