Repository numba/numba, pull requests merged in 2020-11, with the labels that each got.

#6358 Add log2 and remainder implementations for cuda
  docs/source/cuda/cudapysupported.rst
  numba/cuda/cudamath.py
  numba/cuda/mathimpl.py
  numba/cuda/tests/cudapy/test_math.py
  numba/tests/support.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6373 Allow Dispatchers to be cached
  numba/core/types/functions.py
  numba/tests/cache_usecases.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#6377 CUDA: Fix various issues in test suite
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_blackscholes.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/cudapy/test_idiv.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_matmul.py
  numba/cuda/tests/cudapy/test_nondet.py
  numba/cuda/tests/cudapy/test_optimization.py
  numba/cuda/tests/cudapy/test_powi.py
  numba/cuda/tests/cudapy/test_py2_div_issue.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6403 Add `types.ListType.key`
  numba/core/types/containers.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#6437 Don't pass reduction variables known in an outer parfor to inner parfors when analyzing reductions.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#6442 Fix array analysis regression in 0.52 RC2 for tuple of 1D arrays
  numba/parfors/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge

#6376 Added a fixed seed in test_atomics.py for issue #6370
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6441 Fix ASCII flag in Unicode slicing (0.52.0rc2 regression)
  numba/cpython/unicode.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge

#6457 Link to read the docs instead of numba homepage
  README.rst
Labels: 5 - Ready to merge

#6463 Bump llvmlite to 0.36 series
  buildscripts/condarecipe.local/meta.yaml
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#5740 Add FAQ entry on how to create a MWR.
  docs/source/user/faq.rst
Labels: 5 - Ready to merge, doc

#6446 Fix #6444: pruner issues with reference stealing functions
  docs/source/developer/numba-runtime.rst
  numba/core/boxing.py
  numba/core/pythonapi.py
  numba/core/runtime/_nrt_python.c
  numba/core/runtime/_nrt_pythonmod.c
Labels: 5 - Ready to merge

#6245 CUDA Cooperative grid groups
  .flake8
  docs/source/cuda-reference/kernel.rst
  docs/source/cuda/cooperative_groups.rst
  docs/source/cuda/index.rst
  docs/source/cuda/simulator.rst
  numba/cuda/compiler.py
  numba/cuda/cudadecl.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/drvapi.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudaimpl.py
  numba/cuda/device_init.py
  numba/cuda/models.py
  numba/cuda/nvvmutils.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/libs.py
  numba/cuda/simulator/kernel.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba/cuda/tests/doc_examples/__init__.py
  numba/cuda/tests/doc_examples/test_cg.py
  numba/cuda/types.py
  numba/misc/findlib.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6450 Fix asfarray kwarg default handling.
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#6454 FIX: Fixes for literals
  numba/core/annotations/type_annotations.py
  numba/core/codegen.py
  numba/core/ir.py
  numba/misc/appdirs.py
Labels: 5 - Ready to merge

#6455 Fix refprune on obfuscated refs and stabilize optimisation WRT wrappers.
  numba/core/callconv.py
  numba/core/callwrapper.py
  numba/core/codegen.py
  numba/core/cpu.py
  numba/tests/test_codegen.py
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge

#6466 Remove the misspelling of finalize_dynamic_globals
  numba/core/codegen.py
Labels: 5 - Ready to merge

#6470 Adding PyCon Sweden 2020 talk on numba
  docs/source/user/talks.rst
Labels: 5 - Ready to merge

#6472 Document numba.extending.is_jitted
  docs/source/extending/high-level.rst
Labels: 5 - Ready to merge

#6474 Add skip on PPC64LE for tests causing SIGABRT in LLVM.
  numba/tests/support.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6477 Preparing for 0.52.0rc3
  CHANGE_LOG
  buildscripts/condarecipe.local/meta.yaml
  docs/source/developer/numba-runtime.rst
  numba/core/boxing.py
  numba/core/callconv.py
  numba/core/callwrapper.py
  numba/core/codegen.py
  numba/core/cpu.py
  numba/core/pythonapi.py
  numba/core/runtime/_nrt_python.c
  numba/core/runtime/_nrt_pythonmod.c
  numba/cpython/unicode.py
  numba/np/arraymath.py
  numba/parfors/array_analysis.py
  numba/tests/support.py
  numba/tests/test_array_analysis.py
  numba/tests/test_codegen.py
  numba/tests/test_np_functions.py
  numba/tests/test_record_dtype.py
  numba/tests/test_unicode.py
  numba/tests/test_vectorization.py
  requirements.txt
  setup.py
Labels: 5 - Ready to merge

#6486 fix abstract base class import
  numba/core/callconv.py
Labels: 5 - Ready to merge

#6487 Restrict maximum version of python
  setup.py
Labels: 5 - Ready to merge

#6498 Update changelog for 0.52.0rc3
  CHANGE_LOG
Labels: 5 - Ready to merge

#6489 Improve the error message for unsupported Buffer in Buffer situation.
  numba/core/types/common.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge

#6495 Fix typo in literal list docs.
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge

#6497 Finalizing 0.52rc3
  CHANGE_LOG
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/core/callconv.py
  setup.py
Labels: 5 - Ready to merge

#6503 Add test to ensure Numba imports without warnings.
  .flake8
  numba/tests/test_import.py
Labels: 5 - Ready to merge

#6506 Fix requirements.txt pinning
  requirements.txt
Labels: 5 - Ready to merge

#6501 Add doc entry on Numba's limited resources and how to help.
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge

#6500 Update bug and feature request templates.
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 5 - Ready to merge

#6458 Enable typeguard in CI
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  docs/source/developer/contributing.rst
  docs/source/user/installing.rst
  numba/core/codegen.py
  numba/tests/support.py
  numba/tests/test_typeguard.py
  runtests.py
Labels: 5 - Ready to merge

#6349 Refactor Dispatcher to remove unnecessary indirection
  docs/source/developer/repomap.rst
  numba/_dispatcher.cpp
  numba/_dispatcher.h
  numba/_dispatcherimpl.cpp
  numba/_typeof.h
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6516 Fix RTD build by using conda.
  .readthedocs.yml
  docs/environment.yml
Labels: 5 - Ready to merge

#6508 Defer requirements to setup.py
  requirements.txt
Labels: 5 - Ready to merge

#6510 CUDA: Make device array assignment synchronous where necessary
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6447 CUDA: Add get_regs_per_thread method to Dispatcher
  docs/source/cuda-reference/kernel.rst
  numba/cuda/compiler.py
  numba/cuda/decorators.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6430 CUDA docs: Add RNG example with 3D grid and strided loops
  .flake8
  docs/source/cuda/random.rst
  numba/cuda/tests/doc_examples/test_random.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, doc

#6343 CUDA: Add support for passing tuples and namedtuples to kernels
  numba/cuda/compiler.py
  numba/cuda/tests/cudapy/test_array_args.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5162 Specify synchronization semantics of CUDA Array Interface
  docs/source/cuda/cuda_array_interface.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/core/typing/context.py
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6519 Avoid unnecessary ir.Del generation and removal
  numba/core/ir_utils.py
  numba/core/typed_passes.py
  numba/parfors/parfor.py
Labels: 5 - Ready to merge

#6517 CUDA: Add NVVM test of all 8-bit characters
  numba/cuda/tests/nocuda/test_nvvm.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6527 setup.py: fix py version guard
  setup.py
Labels: 5 - Ready to merge

#6528 Update changelog for 0.52.0 final
  CHANGE_LOG
Labels: 4 - Waiting on CI

#6529 Preparing 0.52.0 final
  CHANGE_LOG
  setup.py
Labels: 5 - Ready to merge

#6499 Testhound/cuda atomic
  docs/source/cuda-reference/kernel.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudaimpl.py
  numba/cuda/nvvmutils.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6530 Update llvmlite dependency
  buildscripts/condarecipe.local/meta.yaml
  requirements.txt
  setup.py
Labels: 5 - Ready to merge
