Repository numba/numba, pull requests merged in 2020-09, with the labels that each got.

#6200 Workaround #5973
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge

#6195 PR 6187 Continue. Don't visit already checked successors
  numba/core/controlflow.py
  numba/tests/test_flow_control.py
Labels: 5 - Ready to merge

#6201 Update CHANGE_LOG for 0.51.2
  CHANGE_LOG
Labels: 5 - Ready to merge

#6150 CUDA: Turn on flake8 for cudadrv and fix errors
  .flake8
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/drvapi.py
  numba/cuda/cudadrv/enums.py
  numba/cuda/cudadrv/nvvm.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5465 Remove macro expansion and replace uses with FE typing + BE lowering
  docs/source/developer/architecture.rst
  docs/source/developer/repomap.rst
  numba/core/datamodel/models.py
  numba/core/errors.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/rewrites/__init__.py
  numba/core/rewrites/macros.py
  numba/core/typeinfer.py
  numba/core/types/misc.py
  numba/core/typing/templates.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_freevar.py
  numba/cuda/tests/cudapy/test_lang.py
  numba/cuda/tests/cudapy/test_localmem.py
  numba/cuda/tests/cudapy/test_sm_creation.py
  numba/roc/hsadecl.py
  numba/roc/hsaimpl.py
  numba/roc/stubs.py
  numba/tests/test_ir.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, ROC

#6015 Adding BooleanLiteral type
  numba/core/boxing.py
  numba/core/datamodel/models.py
  numba/core/types/scalars.py
  numba/core/typing/builtins.py
  numba/cpython/builtins.py
  numba/cpython/numbers.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_operators.py
Labels: 5 - Ready to merge

#6092 CUDA: Add mapped_array_like and pinned_array_like
  docs/source/cuda-reference/memory.rst
  docs/source/cuda/memory.rst
  numba/cuda/api.py
  numba/cuda/simulator/__init__.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_array.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6038 Closes #6037, fixing FreeBSD compilation
  numba/np/ufunc/workqueue.c
Labels: 5 - Ready to merge

#6213 Fix #6177. Remove AOT dependency on the Numba package
  numba/_helperlib.c
  numba/pycc/modulemixin.c
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge

#6227 Raise exception when no supported architectures are found
  numba/cuda/cudadrv/nvvm.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6194 Remove recursion from traverse_types
  numba/core/datamodel/models.py
  numba/tests/test_struct_ref.py
Labels: 5 - Ready to merge

#6254 Fix win-32 hashing bug (from Stuart Archibald)
  numba/cpython/hashing.py
Labels: 5 - Ready to merge

#6248 Add support for CUDA atomic subtract operations
  docs/source/cuda-reference/kernel.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudaimpl.py
  numba/cuda/nvvmutils.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, CUDA

#6064 Lower math.frexp and math.ldexp in numba.cuda
  docs/source/cuda/cudapysupported.rst
  numba/cuda/cudamath.py
  numba/cuda/libdevice.py
  numba/cuda/tests/cudapy/test_frexp_ldexp.py
Labels: 5 - Ready to merge, CUDA

#6185 Better error message on NotDefinedError
  numba/core/errors.py
Labels: 5 - Ready to merge

#6206 Build all extension modules with -g -Wall -Werror on Linux x86, provide -O0 flag option
  buildscripts/condarecipe.local/build.sh
  buildscripts/incremental/build.sh
  docs/source/developer/contributing.rst
  numba/_dispatcher.c
  numba/_dynfunc.c
  numba/_pymodule.h
  numba/_typeof.c
  numba/mviewbuf.c
  numba/np/ufunc/omppool.cpp
  numba/np/ufunc/workqueue.c
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6244 CUDA Docs: Make workflow using simulator more explicit
  docs/source/cuda/simulator.rst
Labels: 5 - Ready to merge, CUDA, doc

#6261 Add np.ndarray.ptp() support.
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#6267 speed up a couple of really slow unittests
  numba/np/linalg.py
  numba/tests/test_linalg.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge

#6265 Fix #6260
  numba/core/ir_utils.py
  numba/tests/test_comprehension.py
Labels: 5 - Ready to merge

#6262 Support dtype from str literal.
  numba/core/typing/npydecl.py
  numba/np/arrayobj.py
  numba/tests/support.py
  numba/tests/test_array_methods.py
  numba/tests/test_dyn_array.py
Labels: 5 - Ready to merge

#6202 Speed up str(int)
  numba/cpython/unicode.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge

#6277 fix: cross2d wrong doc. reference (issue #6276)
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#6204 Fix unicode kind selection for getitem.
  numba/cpython/unicode.py
  numba/tests/test_dictobject.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge

#6281 Remove numba.jitclass shim as per deprecation schedule.
  docs/source/reference/deprecation.rst
  numba/__init__.py
  numba/experimental/jitclass/decorators.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#6282 Remove docs on Python 2(.7) EOL.
  docs/source/reference/index.rst
  docs/source/reference/python27-eol.rst
Labels: 5 - Ready to merge

#5639 Make UnicodeType inherit from Hashable
  numba/core/types/misc.py
  numba/cpython/setobj.py
  numba/tests/test_sets.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge

#6283 Add note on how public CI is impl and what users can do to help.
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge
