Repository numba/numba, pull requests merged in 2020-01, with the labels that each got.

#5018 Fix #5011.
  numba/tests/test_literal_dispatch.py
  numba/typeinfer.py
Labels: 5 - Ready to merge

#5019 skip pycc test on Python 3.8 + macOS because of distutils issue
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge

#5021 Update change log with fixes from 0.47.0 RC period.
  CHANGE_LOG
Labels: 5 - Ready to merge

#4997 State that CUDA Toolkit 8.0 required in docs
  buildscripts/condarecipe.local/meta.yaml
  docs/source/cuda/overview.rst
Labels: 5 - Ready to merge

#4998 Fix more spelling typos
  .binstar.yml
  docs/source/cuda/cuda_array_interface.rst
  docs/source/glossary.rst
  docs/source/proposals/type-inference.rst
  docs/source/reference/pysemantics.rst
  docs/source/reference/pysupported.rst
  docs/source/user/cli.rst
  examples/stack.py
  numba/_dispatcher.c
  numba/_lapack.c
  numba/annotations/type_annotations.py
  numba/appdirs.py
  numba/caching.py
  numba/cext/dictobject.h
  numba/cgutils.py
  numba/config.py
  numba/cuda/cudadrv/autotune.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/decorators.py
  numba/cuda/kernels/reduction.py
  numba/cuda/random.py
  numba/cuda/tests/cudapy/test_gufunc_scalar.py
  numba/debuginfo.py
  numba/dummyarray.py
  numba/help/inspector.py
  numba/inline_closurecall.py
  numba/ir_utils.py
  numba/jitclass/base.py
  numba/lowering.py
  numba/npyufunc/gufunc_scheduler.cpp
  numba/roc/compiler.py
  numba/roc/hsadrv/driver.py
  numba/roc/mathimpl.py
  numba/roc/tests/hsadrv/test_driver.py
  numba/roc/tests/hsapy/test_scan.py
  numba/stencil.py
  numba/targets/base.py
  numba/targets/externals.py
  numba/targets/iterators.py
  numba/targets/linalg.py
  numba/testing/__init__.py
  numba/tests/test_dispatcher.py
  numba/tests/test_listimpl.py
  numba/tests/test_looplifting.py
  numba/tests/test_np_functions.py
  numba/tests/test_typedlist.py
  numba/types/abstract.py
  numba/types/functions.py
  numba/typing/context.py
  numba/typing/templates.py
  numba/withcontexts.py
Labels: 5 - Ready to merge

#5007 test_consuming_strides: Keep dev array alive
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge

#5010 merge string prs
  docs/source/reference/pysupported.rst
  numba/tests/test_unicode.py
  numba/unicode.py
  numba/unicode_support.py
Labels: 5 - Ready to merge

#5024 Propagate semantic constants ahead of static rewrites.
  numba/compiler.py
  numba/tests/test_analysis.py
Labels: 5 - Ready to merge

#5040 Drop Py2.7 and Py3.5 from public CI
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge

#5039 Disable help messages.
  docs/source/reference/envvars.rst
  numba/config.py
Labels: 5 - Ready to merge

#5029 Install optional dependencies for Python 3.8 tests
  buildscripts/incremental/setup_conda_environment.sh
  numba/tests/test_annotations.py
Labels: 5 - Ready to merge

#5027 Add Python 3.8 classifier to setup.py
  setup.py
Labels: 5 - Ready to merge

#5048 Fix CI py38
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge

#4964 Fix #4628: Add more appropriate typing for CUDA device arrays
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/cuda/tests/cudapy/test_array.py
Labels: 5 - Ready to merge, BuildFarm Passed

#5014 Enable use of records and bools for shared memory, remove ddt, add additional transpose tests
  docs/source/developer/repomap.rst
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_sm.py
  numba/cuda/tests/cudapy/test_transpose.py
  numba/testing/ddt.py
  numba/tests/__init__.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5016 Fix various issues in CUDA library search (Fixes #4979)
  numba/cuda/cuda_paths.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/tests/nocuda/test_library_lookup.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5023 Don't launch ForAll kernels with 0 elements (Fixes #5017)
  numba/cuda/compiler.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/simulator/kernel.py
  numba/cuda/tests/cudapy/test_forall.py
  numba/cuda/tests/cudapy/test_slicing.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5049 Clarify what dictionary means
  docs/source/cuda/cuda_array_interface.rst
Labels: 5 - Ready to merge

#5012 Fix IndexError when accessing the "-1" element of dummyarray
  numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
  numba/dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#4975 Make `device_array_like` create contiguous arrays (Fixes #4832)
  numba/cuda/api.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_array.py
  numba/cuda/tests/cudapy/test_transpose.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5058 Permit mixed int types in wrap_index
  numba/array_analysis.py
  numba/tests/test_array_analysis.py
Labels: 5 - Ready to merge

#5046 Update setup.py and buildscripts for dependency requirements
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  numba/tests/test_parallel_backend.py
  setup.py
Labels: 5 - Ready to merge

#4724 Only use lives (and not aliases) to create post parfor live set.
  numba/ir_utils.py
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5053 Convert from arrays to names in define() and don't invalidate for multiple consistent defines.
  numba/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#5062 Update docs for updated version requirements
  README.rst
  docs/source/cuda/cudapysupported.rst
  docs/source/cuda/kernels.rst
  docs/source/developer/hashing.rst
  docs/source/reference/fpsemantics.rst
  docs/source/reference/numpysupported.rst
  docs/source/reference/pysupported.rst
  docs/source/user/5minguide.rst
  docs/source/user/installing.rst
  docs/source/user/threading-layer.rst
Labels: 5 - Ready to merge, doc

#5068 Remove Python 3.4 backports from utils
  numba/cuda/cudadrv/driver.py
  numba/dispatcher.py
  numba/roc/hlc/libhlc.py
  numba/roc/hsadrv/driver.py
  numba/runtime/nrt.py
  numba/targets/codegen.py
  numba/tests/test_boundscheck.py
  numba/tests/test_runtests.py
  numba/tests/test_utils.py
  numba/typeconv/castgraph.py
  numba/types/scalars.py
  numba/utils.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#5078 Catch the use of global typed-list in JITed functions
  numba/ir_utils.py
  numba/tests/test_typedlist.py
Labels: 5 - Ready to merge

#4617 Add coverage for `np.argwhere`
  docs/source/reference/numpysupported.rst
  numba/targets/arraymath.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge

#4760 Make type_callable return the decorated function
  numba/extending.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge

#5090 Update deprecation notices for 0.48.0
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge

#5091 Change log update for 0.48.0
  CHANGE_LOG
Labels: 5 - Ready to merge

#4942 Prevent some parfor aliasing. Rename copied function var to prevent recursive type locking.
  numba/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#4957 Add notes on overwriting gufunc inputs to docs
  docs/source/reference/jit-compilation.rst
  docs/source/user/vectorize.rst
Labels: 5 - Ready to merge

#5059 Docs: Explain how to use Memcheck with Numba, fixups in CUDA documentation
  contrib/valgrind-numba.supp
  docs/source/cuda/cudapysupported.rst
  docs/source/cuda/device-management.rst
  docs/source/cuda/intrinsics.rst
  docs/source/developer/debugging.rst
  docs/source/developer/index.rst
  docs/source/user/troubleshoot.rst
  numba/cuda/decorators.py
Labels: 5 - Ready to merge

#5106 Add SciPy 2019 talks to docs
  docs/source/user/talks.rst
Labels: 5 - Ready to merge

#5092 Fix 5087
  numba/byteflow.py
  numba/tests/test_byteflow.py
Labels: 5 - Ready to merge

#5146 Update 0.48 branch
  CHANGE_LOG
  numba/byteflow.py
  numba/tests/test_byteflow.py
Labels: 4 - Waiting on CI

#5147 Update master for 0.48.0 updates
  CHANGE_LOG
Labels: 5 - Ready to merge

#5151 implement None-typed typed-list
  numba/listobject.py
  numba/tests/test_typedlist.py
  numba/types/containers.py
Labels: 5 - Ready to merge
