Repository numba/numba, pull requests merged in 2021-11, with the labels that each got.

#7395 Fix #7394 and #6550 & Added test & improved error message
  numba/core/inline_closurecall.py
  numba/cpython/rangeobj.py
  numba/tests/test_comprehension.py
  numba/tests/test_range.py
Labels: 5 - Ready to merge, Effort - short

#7442 Add some diagnostics to SVML test failures.
  numba/tests/test_svml.py
Labels: 5 - Ready to merge, Effort - short

#7479 CUDA: Print format string and warn for > 32 print() args
  docs/source/cuda/cudapysupported.rst
  numba/cuda/printimpl.py
  numba/cuda/tests/cudapy/test_print.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#7525 Make sure` demangle()` returns `str` type.
  numba/core/targetconfig.py
  numba/tests/test_compiler_flags.py
Labels: 5 - Ready to merge, Effort - short

#7496 CUDA: Use a single dispatcher class for all kinds of functions
  docs/source/reference/deprecation.rst
  numba/core/base.py
  numba/core/dispatcher.py
  numba/cuda/compiler.py
  numba/cuda/cudaimpl.py
  numba/cuda/decorators.py
  numba/cuda/models.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_device_func.py
  numba/cuda/tests/cudapy/test_errors.py
  numba/cuda/tests/cudapy/test_inspect.py
  numba/cuda/tests/cudapy/test_optimization.py
  numba/cuda/types.py
  numba/cuda/vectorizers.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7539 Fix str decode issue from merge #7525/#7506
  numba/tests/test_compiler_flags.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#7547 Remove 32bit linux scipy installation.
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#7548 Correct evaluation order in assert statement
  numba/_dispatcher.cpp
Labels: 5 - Ready to merge, Effort - short

#7561 fix a typo
  docs/source/user/stencil.rst
Labels: 5 - Ready to merge, Effort - short

#7567 Update docs to note meetings are public.
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge, Effort - short

#7309 Update MapConstraint to handle type coercion for typed.Dict correctly.
  numba/core/typeinfer.py
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge, Effort - short

#7441 Permit any string as a key in literalstrkeydict type.
  numba/core/types/containers.py
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge, Effort - short

#7538 Fix `@overload_glue` performance regression.
  numba/core/cpu.py
  numba/core/options.py
  numba/core/overload_glue.py
Labels: 5 - Ready to merge, Effort - short

#7546 Fix handling of missing const key in LiteralStrKeyDict
  numba/core/typing/builtins.py
  numba/tests/test_dictobject.py
Labels: 5 - Ready to merge, Effort - short

#7057 Fix #7041: Add charseq registry to CUDA target
  docs/source/cuda/cudapysupported.rst
  numba/cuda/compiler.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_const_string.py
  numba/cuda/tests/cudapy/test_record_dtype.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - long

#7265 Fix linspace to use np.divide and clamp to stop.
  numba/np/arrayobj.py
  numba/tests/test_dyn_array.py
Labels: 5 - Ready to merge, Effort - short

#7552 Prepend the inlined function name to inlined variables.
  numba/core/inline_closurecall.py
  numba/core/ir_utils.py
  numba/tests/support.py
  numba/tests/test_closure.py
  numba/tests/test_copy_propagate.py
  numba/tests/test_ir_inlining.py
Labels: 5 - Ready to merge, Effort - medium

#7570 Update the docs and error message for errors when importing Numba.
  .flake8
  docs/source/user/faq.rst
  numba/core/typeconv/typeconv.py
Labels: 5 - Ready to merge, Effort - medium

#7583 Make numba.types.Optional __str__ less verbose.
  numba/core/types/misc.py
Labels: 5 - Ready to merge, Effort - short

#7588 Fix casting of start/stop in linspace
  numba/np/arrayobj.py
Labels: 3 - Ready for Review, Pending BuildFarm, Effort - short

#7483 NumPy 1.21 support
  README.rst
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/5minguide.rst
  docs/source/user/installing.rst
  numba/__init__.py
  numba/np/ufunc/_internal.c
  numba/tests/test_array_reductions.py
  setup.py
Labels: 5 - Ready to merge

#7185 Add get_impl_key as abstract method to types.Callable
  numba/core/base.py
  numba/core/types/abstract.py
  numba/core/types/functions.py
  numba/core/types/misc.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge, Effort - medium

#7307 Prevent mutation of arrays in global tuples.
  numba/core/typeinfer.py
  numba/core/typing/arraydecl.py
  numba/tests/test_globals.py
  numba/tests/test_indexing.py
Labels: 5 - Ready to merge, Effort - short

#7315 Link ELF obj as DSO for radare2 disassembly CFG
  numba/core/codegen.py
  numba/core/dispatcher.py
  numba/misc/inspection.py
Labels: 5 - Ready to merge, Effort - medium

#7403 Fix for issue 7402: implement missing numpy ufunc interface
  numba/np/ufunc/gufunc.py
  numba/tests/npyufunc/test_gufunc.py
Labels: 5 - Ready to merge, Effort - medium

#7422 Update Omitted Type to use Hashable Values as Keys for Caching
  numba/core/types/abstract.py
  numba/core/types/misc.py
  numba/core/utils.py
  numba/tests/test_caching.py
Labels: 5 - Ready to merge, Effort - medium

#7461 Support NVIDIA's CUDA Python bindings
  buildscripts/gpuci/build.sh
  docs/source/cuda/bindings.rst
  docs/source/cuda/index.rst
  docs/source/cuda/overview.rst
  docs/source/reference/envvars.rst
  docs/source/user/installing.rst
  numba/core/config.py
  numba/cuda/api.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/cudadrv/devices.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/enums.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_context_stack.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
  numba/cuda/tests/cudadrv/test_cuda_memory.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudadrv/test_managed_alloc.py
  numba/cuda/tests/cudadrv/test_profiler.py
  numba/cuda/tests/cudadrv/test_ptds.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/cuda/tests/cudapy/test_transpose.py
  numba/misc/numba_sysinfo.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - long

#7580 Fix #7507. catch `NotImplementedError ` in `.get_function()`
  numba/core/base.py
  numba/tests/test_practical_lowering_issues.py
Labels: 5 - Ready to merge, Effort - medium

#7498 refactor with-detection logic
  numba/core/byteflow.py
  numba/core/interpreter.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/pylowering.py
  numba/core/transforms.py
  numba/core/typeinfer.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - long

#7597 Update gdb docs for new DWARF enhancements.
  docs/source/reference/envvars.rst
  docs/source/user/troubleshoot.rst
Labels: 5 - Ready to merge, Effort - medium

#7247 Solve memory leak to fix issue #7210
  numba/_pymodule.h
  numba/np/ufunc/_num_threads.c
  numba/np/ufunc/omppool.cpp
  numba/np/ufunc/tbbpool.cpp
  numba/np/ufunc/workqueue.c
Labels: 5 - Ready to merge, Effort - short

#7581 Add support for casting from int enums
  numba/core/typing/builtins.py
  numba/tests/test_enums.py
Labels: 5 - Ready to merge, Effort - short

#7596 Fix max symbol match length for r2
  numba/misc/inspection.py
Labels: 5 - Ready to merge, Effort - short
