Repository numba/numba, pull requests merged in 2021-03, with the labels that each got.

#6776 Fix issue with TBB interface causing warnings and parfors counting them
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#6760 Fix scheduler bug where it rounds to 0 divisions for a chunk.
  numba/np/ufunc/gufunc_scheduler.cpp
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#6789 Fix warnings struct ref typeguard
  azure-pipelines.yml
  buildscripts/incremental/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/tests/test_parfors.py
  numba/tests/test_struct_ref.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6786 Fix gufunc kwargs support
  numba/np/ufunc/gufunc.py
  numba/tests/npyufunc/test_gufunc.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6753 The check for internal types in RewriteArrayExprs
  numba/np/ufunc/array_exprs.py
  numba/tests/test_array_exprs.py
Labels: 5 - Ready to merge, Review Effort - short

#6779 Fix wrap_index type unification.
  numba/parfors/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, ParallelAccelerator

#6792 Update changelog for 0.53.0rc3
  CHANGE_LOG
Labels: 5 - Ready to merge

#6791 Preparing for 0.53.0rc3
  numba/np/ufunc/gufunc.py
  numba/tests/npyufunc/test_gufunc.py
Labels: 5 - Ready to merge

#6766 Fix DeviceNDArray null shape issue
  numba/cuda/api.py
  numba/cuda/tests/cudapy/test_array.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6788 Add support for fastmath 32-bit floating point divide
  numba/cuda/mathimpl.py
  numba/cuda/tests/cudapy/test_fastmath.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6794 refactor and move create_temp_module into numba.tests.support
  numba/tests/support.py
  numba/tests/test_array_exprs.py
  numba/tests/test_jit_module.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge, Review Effort - short

#6798 CUDA: Add optional Driver API argument logging
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/cudadrv/driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6804 added runtime version to `numba -s`
  numba/misc/numba_sysinfo.py
Labels: 5 - Ready to merge, Review Effort - short

#6800 Make a common standard API for querying ufunc impl
  numba/core/base.py
  numba/core/cpu.py
  numba/np/npyimpl.py
  numba/np/numpy_support.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge, Review Effort - short

#6467 Access `ufunc_db` via context
  numba/np/npyimpl.py
Labels: discussion, dpPy

#6810 Fix tiny formatting error in ROC kernel docs
  docs/source/roc/kernels.rst
Labels: 5 - Ready to merge, Review Effort - short

#6735 CUDA: Don't parse IR for modules with llvmlite
  numba/core/codegen.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/target.py
  numba/roc/codegen.py
  numba/tests/support.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6809 #3203 additional info in cuda detect
  numba/cuda/api.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6811 CUDA: Remove test of runtime being a supported version
  numba/cuda/tests/cudadrv/test_runtime.py
Labels: 5 - Ready to merge, CUDA, Review Effort - short

#6816 Update changelog for 0.53.0 final
  CHANGE_LOG
Labels: 5 - Ready to merge

#6795 CUDA: Lazily add libdevice to compilation units
  buildscripts/condarecipe.local/meta.yaml
  docs/source/cuda/overview.rst
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudadrv/runtime.py
  numba/cuda/tests/cudadrv/test_runtime.py
  numba/cuda/tests/cudapy/test_constmem.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6799 Print Numba and llvmlite versions in sysinfo
  numba/misc/numba_sysinfo.py
Labels: 5 - Ready to merge, Review Effort - short

#6813 Mostly CUDA: Replace llvmpy API usage with llvmlite APIs
  numba/core/base.py
  numba/core/callwrapper.py
  numba/core/cgutils.py
  numba/core/codegen.py
  numba/core/cpu.py
  numba/core/debuginfo.py
  numba/core/generators.py
  numba/core/pythonapi.py
  numba/core/runtime/context.py
  numba/core/runtime/nrtdynmod.py
  numba/cpython/builtins.py
  numba/cpython/listobj.py
  numba/cpython/mathimpl.py
  numba/cpython/numbers.py
  numba/cpython/randomimpl.py
  numba/cpython/unicode_support.py
  numba/cuda/codegen.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudaimpl.py
  numba/cuda/libdeviceimpl.py
  numba/cuda/nvvmutils.py
  numba/cuda/printimpl.py
  numba/cuda/target.py
  numba/cuda/tests/cudadrv/test_inline_ptx.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudapy/test_const_string.py
  numba/experimental/jitclass/base.py
  numba/misc/gdb_hook.py
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/linalg.py
  numba/np/npyfuncs.py
  numba/np/ufunc/dufunc.py
  numba/np/ufunc/parallel.py
  numba/np/ufunc/wrappers.py
  numba/parfors/parfor_lowering.py
  numba/pycc/compiler.py
  numba/roc/codegen.py
  numba/roc/hsaimpl.py
  numba/roc/target.py
  numba/tests/test_cgutils.py
  numba/tests/test_compile_cache.py
  numba/typed/dictobject.py
  numba/typed/listobject.py
  numba/typed/typedobjectutils.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6836 CUDA: Documentation updates
  docs/source/cuda/cuda_array_interface.rst
  numba/cuda/stubs.py
Labels: 5 - Ready to merge, CUDA, doc

#6830 CUDA: Use relaxed strides checking to compute contiguity
  docs/source/reference/deprecation.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/misc/dummyarray.py
  numba/tests/test_dummyarray.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6829 Fix accuracy of np.arange and np.linspace
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
  numba/tests/test_dyn_array.py
Labels: 5 - Ready to merge, Review Effort - short

#6828 Fix regression in CUDA: Set stream in mapped and managed array device_setup
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6769 CUDA: Replace `CachedPTX` and `CachedCUFunction` with `CUDACodeLibrary` functionality
  numba/core/codegen.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba/cuda/tests/nocuda/test_nvvm.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6469 Add address space in pointer type
  numba/core/types/misc.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge, dpPy

#6837 Ignore warnings from packaging module when testing import behaviour.
  numba/tests/test_import.py
Labels: 5 - Ready to merge

#6818 CUDA: Support IPC on Windows
  docs/source/cuda/ipc.rst
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudapy/test_ipc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6848 Ignore .ycm_extra_conf.py
  .gitignore
Labels: 5 - Ready to merge, Review Effort - short

#6849 Add __hash__ for IntEnum
  numba/cpython/enumimpl.py
  numba/tests/enum_usecases.py
  numba/tests/test_enums.py
Labels: 5 - Ready to merge, Review Effort - short

#6850 Fix up more internal warnings
  numba/tests/support.py
  numba/tests/test_warnings.py
Labels: 5 - Ready to merge, Review Effort - short

#6801 ParallelAccelerator no long will convert StaticSetItem to SetItem because record arrays require StaticSetItems.
  numba/parfors/array_analysis.py
  numba/parfors/parfor.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#6822 Add support for np.rot90
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Review Effort - medium

#6826 Fix regression on gufunc serialization
  numba/np/ufunc/gufunc.py
  numba/tests/npyufunc/test_gufunc.py
Labels: 5 - Ready to merge, Review Effort - short

#6843 cross-referenced Array type in docs
  docs/source/reference/types.rst
Labels: 5 - Ready to merge, Review Effort - short

#6851 set non-reported llvm timing values to 0.0
  numba/misc/llvm_pass_timings.py
  numba/tests/test_llvm_pass_timings.py
Labels: 5 - Ready to merge

#6861 updated reference to hsa with roc
  numba/roc/hsadrv/devicearray.py
Labels: 5 - Ready to merge, Review Effort - short

#6844 CUDA: Remove NUMBAPRO env var warnings, envvars.py + other small tidy-ups
  docs/source/reference/envvars.rst
  numba/core/bytecode.py
  numba/core/config.py
  numba/cuda/cuda_paths.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/envvars.py
  numba/cuda/tests/cudapy/test_blackscholes.py
  numba/cuda/tests/cudapy/test_vectorize_decor.py
  numba/cuda/tests/nocuda/test_library_lookup.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6854 PR 6096 continued
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/user/installing.rst
  numba/np/ufunc/parallel.py
  numba/np/ufunc/tbbpool.cpp
Labels: 5 - Ready to merge, BuildFarm Passed, Review Effort - medium

#6867 Update changelog for 0.53.1
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - short

#6762 Glue wrappers to create @overload from split typing and lowering.
  docs/source/developer/repomap.rst
  numba/core/base.py
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/ir_utils.py
  numba/core/options.py
  numba/core/overload_glue.py
  numba/core/typing/builtins.py
  numba/core/typing/npydecl.py
  numba/core/typing/templates.py
  numba/core/utils.py
  numba/cpython/builtins.py
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/linalg.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_array_methods.py
  numba/tests/test_errorhandling.py
  numba/tests/test_typeinfer.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6871 Force text-align:left when using Annotate
  numba/core/annotations/pretty_annotate.py
Labels: 5 - Ready to merge, Review Effort - short

#6873 docs: Update reference to @jitclass location
  docs/source/user/jitclass.rst
Labels: 5 - Ready to merge, Review Effort - short

#6468 Access `replace_functions_map` via PreParforPass instance
  numba/parfors/parfor.py
  numba/tests/test_parfors_passes.py
Labels: 5 - Ready to merge, Review Effort - short, dpPy

#6833 Raise TypeError exception if numpy array is cast to scalar
  numba/core/typing/builtins.py
  numba/tests/test_casting.py
Labels: 5 - Ready to merge, Review Effort - short

#6876 Add trailing slashes to dir paths in CODEOWNERS
  .github/CODEOWNERS
Labels: 5 - Ready to merge, Review Effort - short
