Repository numba/numba, pull requests merged in 2021-05, with the labels that each got.

#6989 update threading docs for function loading
  docs/source/developer/threading_implementation.rst
Labels: 5 - Ready to merge, Review Effort - short

#6999 Fix errors introduced by the cloudpickle patch
  numba/core/serialize.py
  numba/core/utils.py
  numba/types/__init__.py
Labels: 5 - Ready to merge

#7003 More mainline fixes
  .flake8
  azure-pipelines.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/core/cpu.py
  numba/core/overload_glue.py
  numba/core/utils.py
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge

#6878 CUDA: Support passing tuples to ufuncs
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/tests/cudapy/test_vectorize.py
  numba/np/ufunc/deviceufunc.py
Labels: 5 - Ready to merge, CUDA, Review Effort - medium

#6990 Refactor hardware extension API to refer to "target" instead.
  numba/__init__.py
  numba/core/base.py
  numba/core/decorators.py
  numba/core/extending.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/registry.py
  numba/core/target_extension.py
  numba/core/types/functions.py
  numba/core/typing/templates.py
  numba/cuda/initialize.py
  numba/cuda/tests/cudapy/test_overload.py
  numba/np/ufunc/decorators.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/test_serialize.py
  numba/tests/test_target_extension.py
Labels: 5 - Ready to merge, BuildFarm Passed

#6995 Resolve issue where nan was being assigned to int type numpy array
  numba/cuda/tests/cudapy/test_atomics.py
Labels: 5 - Ready to merge, CUDA, Review Effort - short

#7004 Test extending the CUDA target
  numba/cuda/tests/cudapy/test_extending.py
Labels: 5 - Ready to merge, CUDA, Review Effort - medium

#7007 Made stencil compilation not fail for arrays of conflicting types.
  numba/stencils/stencil.py
  numba/tests/test_stencils.py
Labels: 5 - Ready to merge, Review Effort - short

#7020 Fix #7017. Adds util class PickleCallableByPath
  numba/core/serialize.py
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge, BuildFarm Passed, Review Effort - short

#6742 Do not add overload function definitions to index.
  numba/misc/help/inspector.py
Labels: 5 - Ready to merge, Review Effort - short

#7016 Docs: Add DALI to list of CAI-supporting libraries
  docs/source/cuda/cuda_array_interface.rst
Labels: 5 - Ready to merge, CUDA, Review Effort - short, doc

#7018 Remove cu{blas,sparse,rand,fft} from library checks
  numba/cuda/cudadrv/libs.py
  numba/cuda/tests/cudadrv/test_cuda_libraries.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6808 #3468 continued: Add support for `np.clip`
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge, Review Effort - medium

#6997 CUDA: Remove catch of NotImplementedError in target.py
  numba/core/cpu.py
  numba/cuda/target.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#7027 Fix nrt debug print
  numba/core/config.py
  numba/core/runtime/nrtdynmod.py
Labels: 5 - Ready to merge

#7052 Fix string support in CUDA target
  numba/cuda/target.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#6840 CUDA: Remove items deprecated in 0.53 + simulator test fixes
  docs/source/cuda/cooperative_groups.rst
  docs/source/cuda/simulator.rst
  docs/source/reference/deprecation.rst
  numba/cuda/compiler.py
  numba/cuda/simulator/kernel.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_array.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba/cuda/tests/cudapy/test_dispatcher.py
  numba/cuda/tests/cudapy/test_fastmath.py
  numba/cuda/tests/cudapy/test_inspect.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_localmem.py
  numba/cuda/tests/cudapy/test_optimization.py
  numba/cuda/tests/cudapy/test_sync.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6888 Get overload to consider compiler flags in cache lookup
  numba/core/typing/templates.py
  numba/core/utils.py
  numba/tests/test_compiler_flags.py
Labels: 5 - Ready to merge, Review Effort - short

#7049 Make NumPy random module use @overload_glue
  numba/core/overload_glue.py
  numba/core/typing/randomdecl.py
  numba/cpython/randomimpl.py
Labels: 5 - Ready to merge, Review Effort - medium

#6802 Add lineinfo flag to PTX and SASS compilation
  numba/cuda/compiler.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/decorators.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_lineinfo.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#6889 Address guvectorize too slow for cuda target
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/compiler.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_context_stack.py
  numba/cuda/tests/cudadrv/test_cuda_devicerecord.py
  numba/cuda/tests/cudadrv/test_cuda_driver.py
  numba/cuda/tests/cudadrv/test_cuda_memory.py
  numba/cuda/tests/cudadrv/test_emm_plugins.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/tests/cudapy/test_record_dtype.py
  numba/cuda/tests/cudapy/test_retrieve_autoconverted_arrays.py
  numba/cuda/tests/cudapy/test_warning.py
  numba/tests/test_config.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#7031 Fix inliner to use a single scope for all blocks
  numba/core/compiler_machinery.py
  numba/core/errors.py
  numba/core/inline_closurecall.py
  numba/core/ir_utils.py
  numba/core/ssa.py
  numba/core/untyped_passes.py
  numba/parfors/parfor.py
  numba/parfors/parfor_lowering.py
  numba/stencils/stencil.py
Labels: 5 - Ready to merge, Review Effort - medium

#7025 Add missing vars into scope during SSA rewrite
  numba/core/ssa.py
Labels: 2 - In Progress

#6983 Support Optional types in ufuncs.
  numba/core/typing/npydecl.py
  numba/np/npyimpl.py
  numba/tests/npyufunc/test_ufunc.py
Labels: 5 - Ready to merge, Review Effort - short

#7008 Added support for np.random.dirichlet with all size arguments
  docs/source/reference/numpysupported.rst
  numba/cpython/randomimpl.py
  numba/tests/test_random.py
Labels: 5 - Ready to merge, Review Effort - medium

#7050 Add overload_classmethod
  docs/source/extending/high-level.rst
  numba/core/consts.py
  numba/core/extending.py
  numba/core/typeinfer.py
  numba/core/typing/templates.py
  numba/core/typing/typeof.py
  numba/tests/test_extending.py
  numba/typed/typeddict.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge, Review Effort - short
