Repository numba/numba, pull requests merged in 2021-08, with the labels that each got.

#7256 Fix link to the discourse forum in README
  README.rst
Labels: 5 - Ready to merge

#7257 Use normal list constructor in List.__new__()
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#7263 Updated issue URL for error messages #7261
  numba/core/errors.py
Labels: 5 - Ready to merge, Review Effort - short

#7129 Add support for axis keyword argument to np.argmin()
  docs/source/reference/numpysupported.rst
  numba/core/typing/arraydecl.py
  numba/core/typing/npydecl.py
  numba/np/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge, Review Effort - medium

#7241 Set aliasing information for inplace_binops..
  numba/core/ir_utils.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#7260 Support typed lists in `heapq`
  numba/cpython/heapq.py
  numba/tests/test_heapq.py
Labels: 5 - Ready to merge, Review Effort - medium

#7267 Fix #7258. Bug in SROA optimization
  numba/core/lowering.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge, Review Effort - medium

#7271 Update 3rd party license text.
  LICENSES.third-party
Labels: 5 - Ready to merge, Review Effort - short

#7273 Update CHANGE_LOG for 0.54.0rc3.
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - short

#7275 Cherrypicks for 0.54.0rc3
  CHANGE_LOG
  LICENSES.third-party
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/core/errors.py
  numba/core/interpreter.py
  numba/core/lowering.py
  numba/core/ssa.py
  numba/core/typing/arraydecl.py
  numba/cuda/api.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_managed_alloc.py
  numba/cuda/tests/cudadrv/test_pinned.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_ir.py
  numba/tests/test_parfors.py
  numba/tests/test_sort.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge

#7285 CUDA: Fix OOB in test_kernel_arg
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Review Effort - short

#7283 Added NPM to Glossary and linked to mentions
  docs/source/developer/numba-runtime.rst
  docs/source/glossary.rst
Labels: 5 - Ready to merge, Review Effort - short

#7298 Use CBC to pin GCC to 7 on most linux and 9 on aarch64.
  buildscripts/condarecipe.local/conda_build_config.yaml
Labels: 5 - Ready to merge, Review Effort - short

#7266 CUDA: Skip multi-GPU copy test with peer access disabled
  numba/cuda/tests/cudapy/test_multigpu.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Review Effort - short

#7222 CUDA: Warn when debug=True and opt=True
  numba/cuda/compiler.py
  numba/cuda/decorators.py
  numba/cuda/tests/cudapy/test_debuginfo.py
  numba/cuda/tests/cudapy/test_warning.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Review Effort - short

#7186 Add support for np.logspace.
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Review Effort - medium

#7294 Continuation of PR #7280, fixing lifetime of TBB task_scheduler_handle
  numba/np/ufunc/tbbpool.cpp
  numba/tests/support.py
  numba/tests/test_parallel_backend.py
  numba/tests/test_pycc.py
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - medium

#7312 Fix #7302. Workaround missing pthread problem on ppc64le
  buildscripts/condarecipe.local/build.sh
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - short

#7317 In TBB tsh test switch os.fork for mp fork ctx
  numba/tests/test_parallel_backend.py
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - short

#7316 Use float64 for consistent typing in heapq tests.
  numba/tests/test_heapq.py
Labels: BuildFarm Passed, 5 - Ready to merge

#7319 Update CHANGE_LOG for 0.54.0 final.
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - short

#7320 Release 0.54.0 final patches
  CHANGE_LOG
  buildscripts/condarecipe.local/build.sh
  buildscripts/condarecipe.local/conda_build_config.yaml
  buildscripts/condarecipe.local/meta.yaml
  numba/cuda/tests/cudapy/test_cuda_array_interface.py
  numba/np/ufunc/tbbpool.cpp
  numba/tests/support.py
  numba/tests/test_parallel_backend.py
  numba/tests/test_pycc.py
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - short

#7119 Add support for `np.broadcast_to`
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge, Review Effort - medium

#7288 Handle cval as a np attr in stencil generation.
  numba/stencils/stencil.py
  numba/tests/test_stencils.py
Labels: 5 - Ready to merge, Review Effort - short

#7296 Fix generator lowering not casting to the actual yielded type
  numba/core/lowering.py
  numba/tests/test_generators.py
Labels: 5 - Ready to merge, Review Effort - short

#7304 Continue PR#3655: add support for np.average
  numba/np/arraymath.py
  numba/tests/test_array_methods.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#3655 support numpy.average
  numba/np/arraymath.py
  numba/tests/test_array_methods.py
  numba/tests/test_np_functions.py
Labels: 4 - Waiting on author

#7347 fix:updated url for error report and feature rquest using issue template
  numba/core/errors.py
Labels: 5 - Ready to merge

#7348 test_inspect_cli: Decode exception with default (utf-8) codec
  numba/tests/test_help.py
Labels: 5 - Ready to merge, Review Effort - short
