Repository numba/numba, pull requests merged in 2021-09, with the labels that each got.

#7329 Improve documentation in reference to CUDA local memory
  docs/source/cuda/memory.rst
Labels: doc, CUDA, 5 - Ready to merge

#7330 Cuda matmul docs
  .flake8
  docs/source/cuda/examples.rst
  docs/source/user/troubleshoot.rst
  numba/cuda/tests/doc_examples/test_matmul.py
Labels: CUDA, 5 - Ready to merge

#7340 Add size_t and ssize_t types
  docs/source/reference/types.rst
  numba/core/types/__init__.py
  numba/tests/test_ctypes.py
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - short

#7349 Allow arbitrary walk-back in reduction nodes to find inplace_binop.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - medium

#7393 skip azure pipeline test if file not present
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge, Review Effort - short

#7202 Initial implementation of np.take_along_axis
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/numpy_support.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Review Effort - medium

#7226 Add support for structured types in Device Arrays
  numba/cuda/api.py
  numba/cuda/api_util.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudadrv/test_cuda_devicerecord.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#7375 CUDA: Run doctests as part of numba.cuda.tests and fix test_cg
  numba/cuda/tests/__init__.py
  numba/cuda/tests/doc_examples/test_cg.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Review Effort - short

#7386 Ensure the NRT is initialized prior to use in external NRT tests.
  docs/source/developer/numba-runtime.rst
  numba/tests/test_nrt.py
Labels: BuildFarm Passed, 5 - Ready to merge, Review Effort - short

#7404 fix typo in literal_unroll docs
  docs/source/reference/pysupported.rst
Labels: doc, 5 - Ready to merge, Review Effort - short

#7419 insert missing backtick in comment
  numba/core/untyped_passes.py
Labels: doc, 5 - Ready to merge, Review Effort - short

#7388 Patch cloudpickle to not reset dynamic class each time it is unpickled
  numba/cloudpickle/cloudpickle.py
  numba/cloudpickle/cloudpickle_fast.py
  numba/tests/cloudpickle_main_class.py
  numba/tests/test_serialize.py
Labels: 5 - Ready to merge, Review Effort - medium

#7360 CUDA: Fix potential leaks when initialization fails
  numba/cuda/cudadrv/driver.py
  numba/cuda/device_init.py
  numba/cuda/simulator/__init__.py
  numba/cuda/simulator/cudadrv/__init__.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/error.py
  numba/cuda/tests/cudadrv/test_init.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Review Effort - medium

#7428 Fix regression #7355: cannot set items in structured array data types
  numba/core/types/npytypes.py
  numba/tests/test_ndarray_subclasses.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge, Review Effort - short

#7429 Update CHANGE_LOG for 0.54.1
  CHANGE_LOG
Labels: 3 - Ready for Review, Review Effort - short

#7430 Cherrypicks for release 0.54.1
  CHANGE_LOG
  docs/source/developer/numba-runtime.rst
  numba/cloudpickle/cloudpickle.py
  numba/cloudpickle/cloudpickle_fast.py
  numba/core/types/npytypes.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/device_init.py
  numba/cuda/simulator/__init__.py
  numba/cuda/simulator/cudadrv/__init__.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/error.py
  numba/cuda/tests/cudadrv/test_init.py
  numba/tests/cloudpickle_main_class.py
  numba/tests/test_help.py
  numba/tests/test_ndarray_subclasses.py
  numba/tests/test_nrt.py
  numba/tests/test_record_dtype.py
  numba/tests/test_runtests.py
  numba/tests/test_serialize.py
Labels: 5 - Ready to merge, Review Effort - short

#7432 add github release task to checklist
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Review Effort - short
