Repository numba/numba, pull requests merged in 2021-12, with the labels that each got.

#7610 Fix #7609. Type should not be mutated.
  numba/core/typeinfer.py
Labels: highpriority, 5 - Ready to merge, Effort - medium

#7618 Fix the doc build: docutils 0.18 not compatible with pinned sphinx
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#7591 Remove deprecations
  docs/source/reference/deprecation.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/core/decorators.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/misc/dummyarray.py
Labels: doc, BuildFarm Passed, CUDA, 5 - Ready to merge

#7345 Add check for ipykernel file in IPython cache locator
  buildscripts/incremental/setup_conda_environment.sh
  numba/core/caching.py
  numba/tests/test_dispatcher.py
Labels: 5 - Ready to merge, Effort - medium

#7359 Extend support for nested arrays inside numpy records
  numba/core/base.py
  numba/core/datamodel/models.py
  numba/core/typing/arraydecl.py
  numba/cuda/tests/cudapy/test_record_dtype.py
  numba/np/arrayobj.py
  numba/tests/test_record_dtype.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7605 Fix TBB 2021 DSO names on OSX/Win and make TBB reporting consistent
  numba/misc/numba_sysinfo.py
  numba/np/ufunc/parallel.py
Labels: 5 - Ready to merge, Effort - short

#7560 Refactor with detection py310
  numba/core/bytecode.py
  numba/core/ir_utils.py
  numba/core/transforms.py
  numba/core/withcontexts.py
  numba/tests/test_flow_control.py
  numba/tests/test_looplifting.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge, Effort - long

#7637 Increase the timeout on the SVML tests for loaded machines.
  numba/tests/test_svml.py
Labels: 3 - Ready for Review, Effort - short

#7557 Python3.10 v2
  README.rst
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/user/installing.rst
  numba/_dispatcher.cpp
  numba/_helpermod.c
  numba/_random.c
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/generators.py
  numba/core/interpreter.py
  numba/core/pylowering.py
  numba/core/untyped_passes.py
  numba/cpython/hashing.py
  numba/cpython/randomimpl.py
  numba/tests/support.py
  numba/tests/test_analysis.py
  numba/tests/test_debuginfo.py
  numba/tests/test_dictobject.py
  numba/tests/test_dicts.py
  numba/tests/test_hashing.py
  numba/tests/test_ir_utils.py
  numba/tests/test_lists.py
  numba/tests/test_tuples.py
  setup.py
Labels: 4 - Waiting on CI, Effort - long

#7244 Implement partial literal propagation pass (support 'isinstance')
  docs/source/reference/pysupported.rst
  numba/core/analysis.py
  numba/core/compiler.py
  numba/core/compiler_machinery.py
  numba/core/untyped_passes.py
  numba/cpython/builtins.py
  numba/tests/test_analysis.py
  numba/tests/test_builtins.py
  numba/tests/test_debuginfo.py
  numba/tests/test_jitclasses.py
  numba/tests/test_parfors.py
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge, Effort - long

#7627 PR 7321 continued
  numba/__init__.py
  numba/core/config.py
Labels: 5 - Ready to merge, Effort - short

#7606 Ensure a prescribed threading layer can load in CI.
  azure-pipelines.yml
  buildscripts/incremental/test.sh
Labels: 5 - Ready to merge, Effort - short

#7626 Fix issues with package dependencies.
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#7628 Move to using windows-2019 images in Azure
  azure-pipelines.yml
Labels: 5 - Ready to merge, Effort - short

#7650 Move Azure builds to OSX 10.15
  azure-pipelines.yml
  buildscripts/incremental/MacOSX10.10.sdk.checksum
  buildscripts/incremental/build.sh
  buildscripts/incremental/test.sh
Labels: 5 - Ready to merge, Effort - short

#7645 In debuginfo, do not add noinline to functions marked alwaysinline
  numba/core/debuginfo.py
  numba/tests/test_debuginfo.py
Labels: 5 - Ready to merge, Effort - medium

#7460 Testhound/fp16 support
  docs/source/cuda-reference/kernel.rst
  numba/core/itanium_mangler.py
  numba/core/typeconv/rules.py
  numba/core/types/__init__.py
  numba/cuda/compiler.py
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/device_init.py
  numba/cuda/errors.py
  numba/cuda/models.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_casting.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/np/numpy_support.py
  numba/tests/test_typeconv.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7603 Fix list.insert() for refcounted values
  numba/cpython/listobj.py
  numba/tests/test_lists.py
Labels: 5 - Ready to merge, Effort - short

#7636 Copy prange loop header to after the parfor.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: ParallelAccelerator, 5 - Ready to merge, Effort - short

#7082 Added Add/Sub between datetime64 array and timedelta64 scalar
  numba/core/ir_utils.py
  numba/np/numpy_support.py
  numba/tests/test_npdatetime.py
  numba/tests/test_numpy_support.py
Labels: 5 - Ready to merge, Effort - medium

#7644 initial CHANGE_LOG for 0.55
  CHANGE_LOG
Labels: 3 - Ready for Review, Effort - medium

#7661 Pin packages for release 0.55 branch
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge
