Repository numba/numba, pull requests merged in 2021-07, with the labels that each got.

#7173 Fix typo in change log
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - short

#7047 Support __hash__ for numpy.datetime64
  numba/core/typing/builtins.py
  numba/np/npdatetime.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge, Review Effort - medium

#7197 don't post to python announce on the first RC
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
Labels: 5 - Ready to merge, Review Effort - short

#7196 Fixes for lineinfo emission
  numba/core/lowering.py
  numba/core/typed_passes.py
  numba/tests/support.py
  numba/tests/test_debuginfo.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - medium

#7216 Update CHANGE_LOG for 0.54.0rc2
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - short

#7209 Clamp numpy
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge

#7211 RC2 patches for release0.54 branch
  CHANGE_LOG
  numba/core/lowering.py
  numba/core/typed_passes.py
  numba/tests/support.py
  numba/tests/test_debuginfo.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#6075 add np.float_power and np.cbrt
  docs/source/reference/numpysupported.rst
  numba/_helperlib.c
  numba/core/typing/npydecl.py
  numba/np/npyfuncs.py
  numba/np/ufunc_db.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge, Review Effort - medium

#7203 remove duplicate changelog entries
  CHANGE_LOG
Labels: 5 - Ready to merge, Review Effort - medium

#7219 bump llvmlite dependency to 0.38.0dev0 for Numba 0.55.0dev0
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge, Review Effort - short

#7220 update release checklist post 0.54rc1+2
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Review Effort - short

#7221 Show GPU UUIDs in cuda.detect() output
  numba/cuda/api.py
Labels: 5 - Ready to merge, CUDA, Review Effort - short

#7192 Fix missing import in array.argsort impl and add more tests.
  numba/core/typing/arraydecl.py
  numba/tests/test_sort.py
Labels: 5 - Ready to merge, Review Effort - short

#7227 FIX: Typo
  docs/source/developer/hashing.rst
Labels: 5 - Ready to merge, Review Effort - short, doc

#7230 PR #7171 bugfix only
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#7235 replace wordings of WIP by draft PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 5 - Ready to merge, Review Effort - short

#7237 fix a typo in a string
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge

#7242 FIX: typo
  docs/source/extending/interval-example.rst
Labels: 5 - Ready to merge

#7251 Fix #6001: typed.List ignores ctor arguments with JIT disabled
  numba/tests/test_listobject.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge, Review Effort - short

#7189 CUDA: Skip IPC tests on ARM
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_ipc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#7190 CUDA: Fix test_pinned on Jetson
  numba/cuda/tests/cudadrv/test_pinned.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#7223 Replace assertion errors on IR assumption violation
  numba/core/errors.py
  numba/core/ssa.py
  numba/tests/test_ir.py
Labels: 5 - Ready to merge, Review Effort - short
