Repository numba/numba, pull requests merged in 2021-06, with the labels that each got.

#7066 Fix #7065: Add expected exception messages for NumPy 1.20 to tests
  numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
Labels: 5 - Ready to merge, CUDA, Review Effort - short

#7068 Enhancing docs about PRNG seeding
  docs/source/reference/numpysupported.rst
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge, Review Effort - short

#7080 Fix `__eq__` for Flags and cpu_options classes
  numba/core/cpu_options.py
  numba/core/targetconfig.py
  numba/stencils/stencilparfor.py
Labels: 5 - Ready to merge, Review Effort - short

#4610 Implement np.is* functions
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Review Effort - long

#7087 Add note to docs about zero-initialization of variables.
  docs/source/reference/pysemantics.rst
Labels: 5 - Ready to merge, Review Effort - short

#7113 Temporarily disable debug env export.
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Review Effort - short

#7088 Initialize NUMBA_DEFAULT_NUM_THREADS with a batch scheduler aware value
  docs/source/user/threading-layer.rst
  numba/core/config.py
Labels: 5 - Ready to merge, Review Effort - short

#7118 Remove print to stdout
  numba/core/untyped_passes.py
Labels: 5 - Ready to merge, Review Effort - short

#6986 document release checklist
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
  docs/source/developer/index.rst
  docs/source/developer/release.rst
Labels: 5 - Ready to merge, Review Effort - long, doc

#4516 Make setitem accept 0d np-arrays
  numba/core/types/npytypes.py
  numba/core/typing/arraydecl.py
  numba/core/typing/builtins.py
  numba/np/arrayobj.py
  numba/tests/test_casting.py
  numba/tests/test_fancy_indexing.py
Labels: 5 - Ready to merge, Review Effort - long

#6720 Faster compile
  numba/core/controlflow.py
  numba/core/lowering.py
  numba/core/ssa.py
  numba/core/transforms.py
  numba/tests/test_debug.py
Labels: 5 - Ready to merge, Review Effort - medium

#6928 Add support for axis keyword arg to numpy.argmax()
  docs/source/reference/numpysupported.rst
  numba/core/ir_utils.py
  numba/core/typing/arraydecl.py
  numba/core/typing/npydecl.py
  numba/np/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge, Review Effort - medium

#7019 Support NumPy 1.20
  CHANGE_LOG
  README.rst
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/reference/numpysupported.rst
  docs/source/user/5minguide.rst
  docs/source/user/installing.rst
  numba/np/arraymath.py
  numba/tests/test_array_reductions.py
  setup.py
Labels: 5 - Ready to merge, BuildFarm Passed, Review Effort - medium

#7056 Change prange conversion approach to reuse header block.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, ParallelAccelerator, Review Effort - medium

#7070 Improve the issue templates and pull request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 5 - Ready to merge, Review Effort - medium

#5984 Handle idx and size unification in wrap_index manually.
  numba/parfors/array_analysis.py
Labels: 5 - Ready to merge, Review Effort - medium

#7122 Rtd/sphinx compat
  docs/source/conf.py
Labels: 5 - Ready to merge, Review Effort - short

#6936 CUDA: Implement support for PTDS globally
  docs/source/cuda-reference/host.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_ptds.py
  numba/cuda/tests/cudapy/test_ipc.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#6981 Fix LLVM IR parsing error on use of np.bool_ in globals
  numba/cpython/numbers.py
  numba/tests/test_globals.py
Labels: 5 - Ready to merge, Review Effort - short

#7044 Fixes for LLVM 11
  numba/core/codegen.py
Labels: 5 - Ready to merge, Review Effort - short

#7100 Replace deprecated call to cuDeviceComputeCapability
  numba/cuda/cudadrv/driver.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#7114 CUDA: Deprecate eager compilation of device functions
  docs/source/reference/deprecation.rst
  numba/cuda/decorators.py
  numba/cuda/tests/cudapy/test_device_func.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#7138 Update the Azure default linux image to Ubuntu 18.04
  azure-pipelines.yml
Labels: 5 - Ready to merge, Review Effort - short

#7137 skip pycc test on Python 3.7 + macOS because of distutils issue
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge

#7134 Move minimum LLVM version to 11.
  numba/__init__.py
Labels: 5 - Ready to merge, Review Effort - short

#6870 Add support for dispatcher retargeting using with-context
  docs/source/developer/repomap.rst
  numba/_dispatcher.cpp
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/decorators.py
  numba/core/dispatcher.py
  numba/core/options.py
  numba/core/retarget.py
  numba/core/types/functions.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/test_retargeting.py
Labels: 5 - Ready to merge, Review Effort - long

#6841 CUDA: Fix source location on kernel entry and enable breakpoints to be set on kernels by mangled name
  numba/core/debuginfo.py
  numba/core/lowering.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_debuginfo.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - medium

#7145 Fix mainline
  azure-pipelines.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/tests/test_dispatcher.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge

#6996 Add constant lowering support for `SliceType`s
  numba/core/datamodel/models.py
  numba/core/types/misc.py
  numba/cpython/slicing.py
  numba/tests/test_parfors.py
  numba/tests/test_slices.py
Labels: 5 - Ready to merge, Review Effort - medium

#7024 fixed llvmir usage in create_module method
  numba/core/base.py
Labels: 5 - Ready to merge, Review Effort - short

#7141 Require llvmlite 0.37 as minimum supported.
  numba/__init__.py
Labels: 5 - Ready to merge, Review Effort - short

#7143 Update version checks in __init__ for np 1.17
  numba/__init__.py
Labels: 5 - Ready to merge, Review Effort - short

#7146 Fix `inline_closurecall` may not be imported
  numba/core/ir_utils.py
Labels: 5 - Ready to merge, Review Effort - short

#6985 Implement static set/get items on records with integer index
  numba/core/typing/arraydecl.py
  numba/np/arrayobj.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge, Review Effort - medium

#6917 Add type conversion for StringLiteral to unicode_type and test.
  numba/core/types/misc.py
  numba/tests/test_conversion.py
Labels: 5 - Ready to merge, Review Effort - short

#7061 Add ndarray allocator classmethod
  .flake8
  numba/core/cpu.py
  numba/core/errors.py
  numba/core/extending.py
  numba/core/target_extension.py
  numba/core/types/functions.py
  numba/core/typing/context.py
  numba/core/typing/templates.py
  numba/np/arrayobj.py
  numba/np/ufunc/array_exprs.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/test_array_exprs.py
  numba/tests/test_blackscholes.py
  numba/tests/test_compile_cache.py
  numba/tests/test_errorhandling.py
  numba/tests/test_looplifting.py
  numba/tests/test_svml.py
  numba/tests/test_target_extension.py
Labels: 5 - Ready to merge, Review Effort - long, highpriority

#7064 Testhound/host array performance warning
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/api.py
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_multithreads.py
  numba/cuda/tests/cudapy/test_warning.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#7147 Revert "Workaround gitpython 3.1.18 dependency issue"
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Review Effort - short

#7149 Fix issue in bytecode analysis where target and next are same.
  numba/core/byteflow.py
  numba/tests/test_byteflow.py
Labels: 5 - Ready to merge, Review Effort - short

#7152 Fix iterators in CUDA
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_iterators.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA, Review Effort - short

#7116 Fix various issues with dwarf emission:
  docs/source/user/troubleshoot.rst
  numba/core/cgutils.py
  numba/core/codegen.py
  numba/core/debuginfo.py
  numba/core/lowering.py
  numba/tests/test_debuginfo.py
Labels: 5 - Ready to merge, Review Effort - medium, highpriority

#7163 Split legalization pass to consider IR and features separately.
  numba/core/compiler.py
  numba/core/typed_passes.py
  numba/tests/test_withlifting.py
Labels: 4 - Waiting on reviewer, Review Effort - short

#7160 Split parfors tests
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - long

#7156 Fix `ir_utils._max_label` being updated incorrectly
  numba/core/inline_closurecall.py
  numba/core/ir_utils.py
  numba/parfors/parfor.py
  numba/stencils/stencilparfor.py
  numba/tests/parfors_max_label_error.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Review Effort - short

#6869 Implement builtin sum()
  docs/source/reference/pysupported.rst
  numba/cpython/builtins.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge, Review Effort - medium

#7121 Continue work on numpy subclasses
  numba/_typeof.c
  numba/core/ir_utils.py
  numba/core/pythonapi.py
  numba/core/runtime/_nrt_python.c
  numba/core/runtime/_nrt_pythonmod.c
  numba/core/runtime/nrt.c
  numba/core/runtime/nrt.h
  numba/core/runtime/nrt.py
  numba/core/runtime/nrt_external.h
  numba/core/types/npytypes.py
  numba/core/typing/npydecl.py
  numba/parfors/parfor.py
  numba/tests/test_ndarray_subclasses.py
Labels: 5 - Ready to merge, Review Effort - long

#7161 Update README for 0.54
  README.rst
Labels: 5 - Ready to merge, Review Effort - short

#7165 Fix use of np.clip where out is not provided.
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge, Review Effort - short

#7162 CUDA: Fix linkage of device functions when compiling for debug
  numba/cuda/codegen.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_debuginfo.py
Labels: 5 - Ready to merge, BuildFarm Passed, CUDA

#7154 adding experimental change-log for 0.54.0dev0
  CHANGE_LOG
  docs/environment.yml
Labels: 5 - Ready to merge, Review Effort - medium
