Repository numba/numba, pull requests merged in 2022-05, with the labels that each got.

#8016 [Docs] [Very Minor] Make `numba.jit` boundscheck doc line consistent
  docs/source/reference/jit-compilation.rst
Labels: 5 - Ready to merge, Effort - short

#8017 Update FAQ to include details about using debug-only option
  docs/source/user/faq.rst
Labels: 5 - Ready to merge

#7996 Fix binding logic in `@overload_glue`.
  numba/core/overload_glue.py
  numba/core/typing/npydecl.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge, Effort - medium

#7994 Supporting multidimensional arrays in quick sort
  docs/source/reference/numpysupported.rst
  numba/core/typing/arraydecl.py
  numba/core/typing/npydecl.py
  numba/misc/quicksort.py
  numba/np/arrayobj.py
  numba/tests/test_sort.py
Labels: 5 - Ready to merge, Effort - medium

#7537 Add chrome tracing
  docs/source/reference/envvars.rst
  numba/core/compiler_machinery.py
  numba/core/config.py
  numba/core/event.py
  numba/tests/test_chrome_trace.py
Labels: 5 - Ready to merge, Effort - medium

#7866 Support for large numbers of args/kws with Python 3.10
  numba/core/byteflow.py
  numba/core/interpreter.py
  numba/core/ir.py
  numba/tests/support.py
  numba/tests/test_interpreter.py
Labels: 5 - Ready to merge, Effort - long

#7621 Add support for linking CUDA C / C++ with `@cuda.jit` kernels
  docs/source/cuda/cuda_ffi.rst
  docs/source/cuda/index.rst
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/decorators.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/data/cuda_include.cu
  numba/cuda/tests/cudadrv/data/error.cu
  numba/cuda/tests/cudadrv/data/warn.cu
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/doc_examples/ffi/functions.cu
  numba/cuda/tests/doc_examples/test_ffi.py
  setup.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7878 CUDA: Remove some deprecated support, add CC 8.6 and 8.7
  buildscripts/gpuci/axis.yaml
  buildscripts/gpuci/build.sh
  docs/source/cuda/overview.rst
  docs/source/reference/deprecation.rst
  docs/source/user/installing.rst
  numba/core/config.py
  numba/cuda/api.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cuda_paths.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/cudadrv/runtime.py
  numba/cuda/cudaimpl.py
  numba/cuda/cudamath.py
  numba/cuda/mathimpl.py
  numba/cuda/simulator/api.py
  numba/cuda/target.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudadrv/test_streams.py
  numba/cuda/tests/cudapy/test_atomics.py
  numba/misc/numba_sysinfo.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8035 Fix a couple of typos RE implementation
  numba/core/typing/templates.py
  numba/cpython/builtins.py
Labels: 5 - Ready to merge, Effort - short

#8044 Make Python 3.10 kwarg peephole less restrictive
  numba/core/interpreter.py
Labels: 5 - Ready to merge

#8046 Fix caching test failures
  numba/core/caching.py
  numba/tests/test_extending.py
Labels: 5 - Ready to merge, Effort - short

#8049 support str(bool) syntax
  numba/cpython/unicode.py
  numba/tests/test_operators.py
Labels: 5 - Ready to merge

#8052 Ensure pthread is linked in when building for ppc64le.
  buildscripts/condarecipe.local/build.sh
  numba/pycc/cc.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#8003 Add np.broadcast_shapes
  docs/source/reference/numpysupported.rst
  numba/core/analysis.py
  numba/core/untyped_passes.py
  numba/np/arrayobj.py
  numba/tests/test_analysis.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge, Effort - medium

#7950 mission statement
  docs/source/developer/index.rst
  docs/source/developer/mission.rst
Labels: doc, 5 - Ready to merge, Effort - long

#8056 Move caching tests from test_dispatcher to test_caching
  numba/tests/npyufunc/test_caching.py
  numba/tests/test_caching.py
  numba/tests/test_cfunc.py
  numba/tests/test_dispatcher.py
  numba/tests/test_parfors_caching.py
Labels: 5 - Ready to merge, Effort - medium

#8057 Fix coverage checking
  docs/source/developer/contributing.rst
  docs/source/developer/repomap.rst
  run_coverage.py
Labels: 5 - Ready to merge, Effort - short

#7556 Testhound/fp16 comparison
  docs/source/cuda-reference/kernel.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_intrinsics.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7918 Add JIT examples to CUDA docs
  docs/source/cuda/examples.rst
  docs/source/cuda/laplace_final.svg
  docs/source/cuda/laplace_initial.svg
  numba/cuda/tests/doc_examples/test_cpu_gpu_compat.py
  numba/cuda/tests/doc_examples/test_laplace.py
  numba/cuda/tests/doc_examples/test_montecarlo.py
  numba/cuda/tests/doc_examples/test_reduction.py
  numba/cuda/tests/doc_examples/test_sessionize.py
  numba/cuda/tests/doc_examples/test_vecadd.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8069 Install llvmlite 0.38 for Numba 0.55.*
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge

#8080 Fix windows test failure due to timeout when the machine is slow poss…
  numba/tests/test_serialize.py
Labels: 5 - Ready to merge, Effort - short

#8082 Backport #8080: fix windows failure due to timeout
  numba/tests/test_serialize.py
Labels: 5 - Ready to merge, Effort - short

#8093 Backport #7904: Support m1
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/core/config.py
  numba/tests/npyufunc/test_errors.py
  numba/tests/support.py
Labels: 5 - Ready to merge, Effort - short

#8094 Backport #8052 Ensure pthread is linked in when building for ppc64le.
  buildscripts/condarecipe.local/build.sh
  numba/pycc/cc.py
Labels: 5 - Ready to merge, Effort - short

#8097 Exclude libopenblas 0.3.20 on osx-arm64
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, Effort - short

#8099 Fix Py_DECREF use in case of error state (for devicearray).
  numba/_devicearray.cpp
Labels: 5 - Ready to merge, Effort - short

#8100 Backport #7786 for 0.55.2: Remove dependency on intel-openmp for OSX
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/developer/contributing.rst
  docs/source/user/installing.rst
  docs/source/user/threading-layer.rst
Labels: 5 - Ready to merge, Effort - short

#8078 Backport #7804: update local references from master -> main
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.rst
  docs/source/_ext/ghfiles.py
  docs/source/developer/contributing.rst
  docs/source/developer/live_variable_analysis.rst
  docs/source/developer/numba-runtime.rst
  numba/misc/help/inspector.py
  numba/testing/main.py
Labels: 5 - Ready to merge

#8067 Backport #8027: Support for NumPy 1.22
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/condarecipe.local/run_test.sh
  buildscripts/incremental/test.sh
  numba/misc/numba_sysinfo.py
  numba/np/arraymath.py
  numba/np/ufunc_db.py
  numba/tests/support.py
  numba/tests/test_dataflow.py
  numba/tests/test_np_functions.py
  numba/tests/test_sysinfo.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#8075 update max NumPy for 0.55.2
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge

#8084 Pin meta.yaml to llvmlite 0.38 series
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, Effort - short

#8098 Backport #8097: Exclude libopenblas 0.3.20 on osx-arm64
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, Effort - short

#8103 Backport #8102 to fix numpy requirements
  buildscripts/condarecipe.local/meta.yaml
Labels: Pending BuildFarm, 4 - Waiting on CI, Effort - short

#8114 Backport #8109 Pin TBB support with respect to incompatible 2021.6 API.
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/np/ufunc/tbbpool.cpp
Labels: 3 - Ready for Review, Effort - short

#8068 update changelog for 0.55.2
  CHANGE_LOG
Labels: 3 - Ready for Review

#7836 min() and max() support for np.datetime and np.timedelta
  numba/core/typing/builtins.py
  numba/core/typing/npdatetime.py
  numba/cpython/builtins.py
  numba/np/npdatetime.py
  numba/np/npdatetime_helpers.py
  numba/parfors/parfor.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge, Effort - medium

#8109 Pin TBB support with respect to incompatible 2021.6 API.
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/np/ufunc/tbbpool.cpp
Labels: 5 - Ready to merge, Effort - short
