Repository numba/numba, pull requests merged in 2022-03, with the labels that each got.

#7837 Initial refactoring of parfor reduction lowering
  numba/core/lowering.py
  numba/parfors/parfor.py
  numba/parfors/parfor_lowering.py
Labels: 5 - Ready to merge, Effort - long

#7865 Remove add_user_function
  docs/source/reference/deprecation.rst
  numba/core/base.py
Labels: 5 - Ready to merge, Effort - short

#7780 Fix sets with reference counted items
  numba/core/boxing.py
  numba/cpython/setobj.py
  numba/tests/test_sets.py
Labels: 5 - Ready to merge, Effort - medium

#7664 Flatten mangling dicts into a single dict
  numba/core/itanium_mangler.py
Labels: 5 - Ready to merge, Effort - short

#7895 Remove use of `llvmlite.llvmpy`
  numba/core/base.py
  numba/core/callwrapper.py
  numba/core/cgutils.py
  numba/core/codegen.py
  numba/core/cpu.py
  numba/core/generators.py
  numba/core/llvm_bindings.py
  numba/core/lowering.py
  numba/core/pylowering.py
  numba/core/pythonapi.py
  numba/cpython/builtins.py
  numba/cpython/cmathimpl.py
  numba/cpython/hashing.py
  numba/cpython/mathimpl.py
  numba/cpython/numbers.py
  numba/cpython/printimpl.py
  numba/cpython/rangeobj.py
  numba/cpython/tupleobj.py
  numba/cpython/unicode_support.py
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/npdatetime.py
  numba/np/npyfuncs.py
  numba/np/npyimpl.py
  numba/np/ufunc/parallel.py
  numba/np/ufunc/wrappers.py
  numba/parfors/array_analysis.py
  numba/parfors/parfor_lowering.py
  numba/pycc/compiler.py
  numba/pycc/llvm_types.py
  numba/tests/test_builtins.py
  numba/tests/test_cgutils.py
  numba/typed/typedobjectutils.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#7898 Skip test_ptds under cuda-memcheck
  numba/cuda/tests/cudadrv/test_ptds.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#7901 Pyston compatibility for the test suite
  numba/tests/test_nrt.py
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge, Effort - short

#7911 added sys import
  numba/parfors/parfor_lowering.py
Labels: 5 - Ready to merge, Effort - short

#7915 CUDA: Fix test checking debug info rendering.
  numba/cuda/tests/cudapy/test_debuginfo.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#7703 Ignore unsupported types in `ShapeEquivSet._getnames()`
  numba/parfors/array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - medium

#7858 CUDA: Deprecate `ptx` Attribute and Update Tests
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_constmem.py
  numba/cuda/tests/cudapy/test_dispatcher.py
  numba/cuda/tests/cudapy/test_localmem.py
  numba/cuda/tests/cudapy/test_sync.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#7685 Don't convert setitems that have dimension mismatches to parfors.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - medium

#7893 Use uuid.uuid4() as the key in serialization.
  numba/core/dispatcher.py
  numba/tests/support.py
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge, Effort - medium

#7924 Retain non-modified index tuple components.
  numba/parfors/array_analysis.py
  numba/tests/test_parfors.py
Labels: ParallelAccelerator, 5 - Ready to merge

#7850 CUDA: Pass `fastmath` compiler flag down to `compile_ptx` and `compile_device`; Improve `fastmath` tests
  numba/cuda/compiler.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_fastmath.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7904 Support m1
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/core/config.py
  numba/tests/npyufunc/test_errors.py
  numba/tests/support.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#7919 Disallow //= reductions in pranges.
  docs/source/user/parallel.rst
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - medium

#7939 Fix rendering in feature request template.
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: 5 - Ready to merge, Effort - short

#7941 Remove debug dump output from closure inlining pass.
  numba/core/untyped_passes.py
Labels: 5 - Ready to merge, Effort - short
