Repository numba/numba, pull requests merged in 2022-11, with the labels that each got.

#8415 Refactor `numba.np.arraymath` methods from lower_builtins to overloads
  docs/source/reference/numpysupported.rst
  numba/core/typing/arraydecl.py
  numba/core/typing/npydecl.py
  numba/np/arraymath.py
  numba/tests/test_errorhandling.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - long

#8537 Make ol_compatible_view accessible on all targets
  numba/np/arrayobj.py
Labels: CUDA, 5 - Ready to merge

#8552 Update version support table for 0.56.4.
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8553 Update CHANGE_LOG for 0.56.4
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#8562 Cherry picks 0.56.4
  CHANGE_LOG
  docs/source/user/installing.rst
  numba/np/arrayobj.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#8571 Additional update to CHANGE_LOG for 0.56.4
  CHANGE_LOG
Labels: 3 - Ready for Review

#8573 Additional cherry-picks for 0.56.4
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#8570 Release 0.56 branch: Fix overloads with `target="generic"` for CUDA
  numba/cuda/compiler.py
Labels: 5 - Ready to merge, Effort - short

#8517 make some typedlist C-APIs public
  numba/_numba_common.h
  numba/cext/cext.h
  numba/cext/listobject.h
Labels: 5 - Ready to merge, Effort - medium

#8547 [Unicode] Add more string view usages for unicode operations
  numba/cpython/unicode.py
Labels: 5 - Ready to merge, Effort - short

#8554 Make target for `@overload` have 'generic' as default.
  numba/core/extending.py
  numba/core/typing/templates.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#8557 [Unicode] support startswith with args, start and end.
  numba/cpython/unicode.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge, Effort - medium

#8572 CUDA: Reduce memory pressure from local memory tests
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8580 adding note about doing a wheel test build prior to tagging
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#8001 CUDA fp16 math functions
  docs/source/cuda-reference/kernel.rst
  numba/cuda/compiler.py
  numba/cuda/cpp_function_wrappers.cu
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/dispatcher.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_operator.py
  setup.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8439 Update the contributing docs to include a policy on formatting changes.
  CONTRIBUTING.md
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge, Effort - short

#8494 Remove `context.compile_internal` where easy on `numba/cpython/cmathimpl.py`
  numba/core/typing/cmathdecl.py
  numba/cpython/cmathimpl.py
Labels: 5 - Ready to merge, Effort - medium

#8520 Added noncentral-chisquared, noncentral-f and logseries distributions
  docs/source/reference/numpysupported.rst
  numba/np/random/distributions.py
  numba/np/random/generator_methods.py
  numba/tests/test_np_randomgen.py
Labels: 5 - Ready to merge, Effort - long

#8566 Update workqueue abort message on concurrent access.
  numba/np/ufunc/workqueue.c
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge, Effort - short

#8583 Skip tests that contribute to M1 RuntimeDyLd Assertion error
  numba/tests/support.py
  numba/tests/test_array_constants.py
  numba/tests/test_stencils.py
Labels: BuildFarm Passed, 5 - Ready to merge

#8587 Remove unused refcount removal code, clean `core/cpu.py` module.
  .flake8
  numba/core/cpu.py
Labels: 5 - Ready to merge, Effort - short

#8588 Remove lowering extension hooks, replace with pass infrastructure.
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/lowering.py
  numba/core/typed_passes.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_inlining.py
Labels: ParallelAccelerator, 5 - Ready to merge, Effort - medium

#8592 fix failure of test_cache_invalidate due to read-only install
  numba/tests/test_caching.py
Labels: 5 - Ready to merge, installation

#8593 Adjusted ULP precesion for noncentral distribution test
  numba/tests/test_np_randomgen.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#8499 Deprecate numba.generated_jit
  docs/source/reference/deprecation.rst
  numba/core/decorators.py
  numba/tests/test_deprecations.py
Labels: highpriority, 5 - Ready to merge, Effort - medium

#8597 Prevent use of NumPy's MaskedArray.
  docs/source/reference/numpysupported.rst
  numba/core/typing/typeof.py
  numba/tests/test_typeof.py
Labels: 5 - Ready to merge, Effort - short

#8598 Setup Azure CI to test py3.11
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/build.cmd
  buildscripts/incremental/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge, Effort - short, Python 3.11

#8496 Rewrite most of the set API to use overloads
  numba/core/typing/setdecl.py
  numba/cpython/setobj.py
  numba/tests/test_sets.py
Labels: highpriority, 5 - Ready to merge, Effort - long

#8602 Throw error for unsupported dunder methods
  numba/experimental/jitclass/boxing.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge, Effort - short

#8600 Chrome trace timestamp should be in microseconds not seconds.
  numba/core/event.py
Labels: 5 - Ready to merge, Effort - short

#8606 [Doc] Make the RewriteArrayExprs doc more precise
  docs/source/developer/rewrites.rst
Labels: 5 - Ready to merge

#7622 Support fortran loop ordering for ufunc generation
  numba/np/npyimpl.py
Labels: 5 - Ready to merge, performance - run time, Effort - medium

#8605 Support for CUDA fp16 math functions (part 1)
  numba/cuda/cudaimpl.py
  numba/cuda/cudamath.py
  numba/cuda/mathimpl.py
  numba/cuda/tests/cudapy/test_math.py
Labels: CUDA, 5 - Ready to merge

#8619 Added flat iteration logic for random distributions
  numba/np/random/generator_methods.py
Labels: 5 - Ready to merge, Effort - short

#8625 Refactor `test_ufuncs`
  .flake8
  numba/tests/test_ufuncs.py
Labels: highpriority, 5 - Ready to merge, Effort - medium, test suite
