Repository numba/numba, pull requests merged in 2022-02, with the labels that each got.

#7804 update local references from master -> main
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.rst
  docs/source/_ext/ghfiles.py
  docs/source/developer/contributing.rst
  docs/source/developer/live_variable_analysis.rst
  docs/source/developer/numba-runtime.rst
  numba/misc/help/inspector.py
  numba/testing/main.py
Labels: 5 - Ready to merge

#7809 Updates the gdb configuration to accept a binary name or a path.
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/misc/numba_gdbinfo.py
  numba/tests/gdb/test_pretty_print.py
  numba/tests/gdb_support.py
  numba/tests/test_cli.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#5209 Use importlib to load numba extensions
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/user/installing.rst
  numba/core/entrypoints.py
  numba/tests/test_entrypoints.py
  setup.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - long

#7813 Extend parfors test timeout for aarch64.
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - short

#7814 CUDA Dispatcher refactor
  docs/source/cuda-reference/kernel.rst
  docs/source/cuda/cooperative_groups.rst
  docs/source/cuda/simulator.rst
  numba/cuda/compiler.py
  numba/cuda/decorators.py
  numba/cuda/dispatcher.py
  numba/cuda/initialize.py
  numba/cuda/simulator/compiler.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_errors.py
  numba/cuda/vectorizers.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#7817 Update intersphinx URLs for NumPy and llvmlite.
  docs/source/conf.py
Labels: 5 - Ready to merge, Effort - short

#7786 Remove dependency on intel-openmp for OSX
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/developer/contributing.rst
  docs/source/user/installing.rst
  docs/source/user/threading-layer.rst
Labels: 5 - Ready to merge, Effort - medium

#7772 CUDA: Add Support to Creating `StructModel` Array
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/extensions_usecases.py
  numba/cuda/tests/cudapy/test_localmem.py
  numba/cuda/tests/cudapy/test_sm.py
  numba/cuda/tests/cudapy/test_sm_creation.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7801 add sdist command and umask reminder
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#7829 CUDA: Support `Enum/IntEnum` in Kernel
  docs/source/cuda/cudapysupported.rst
  numba/cuda/dispatcher.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_enums.py
  numba/np/ufunc/deviceufunc.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#7797 prune README
  README.rst
Labels: 5 - Ready to merge, Effort - short

#7846 Fix CUDA enum vectorize test on Windows
  numba/cuda/tests/cudapy/test_enums.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#7848 Support for int * list
  numba/core/typing/listdecl.py
  numba/cpython/listobj.py
  numba/tests/test_lists.py
Labels: 5 - Ready to merge, Effort - short

#7815 CUDA Dispatcher refactor 2: inherit from `dispatcher.Dispatcher`
  docs/source/cuda-reference/kernel.rst
  numba/core/compiler.py
  numba/cuda/compiler.py
  numba/cuda/decorators.py
  numba/cuda/dispatcher.py
  numba/cuda/initialize.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_dispatcher.py
  numba/cuda/tests/cudapy/test_errors.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#7845 change time.time() to time.perf_counter() in docs
  docs/source/user/5minguide.rst
Labels: doc, 5 - Ready to merge, Effort - short

#7690 Implemented np.random.noncentral_chisquare for all size arguments
  docs/source/reference/numpysupported.rst
  numba/cpython/randomimpl.py
  numba/tests/test_random.py
Labels: 5 - Ready to merge

#7833 Add version support information table to docs.
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - medium

#7855 Ensure np.argmin/no.argmax return type is intp
  numba/np/arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge, Effort - short

#7861 Fix a spelling mistake in README
  README.rst
Labels: 5 - Ready to merge, Effort - short
