Repository numba/numba, pull requests merged in 2022-07, with the labels that each got.

#8212 release checklist: include a note to ping @RC_testers on discourse
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#8038 Support for Numpy BitGenerators PR#2: Standard Distributions support
  docs/source/reference/numpysupported.rst
  numba/np/random/_constants.py
  numba/np/random/distributions.py
  numba/np/random/generator_core.py
  numba/np/random/generator_methods.py
  numba/tests/test_np_randomgen.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - long

#8221 CUDA stubs docstring: Replace illegal escape sequence
  buildscripts/gpuci/build.sh
  numba/cuda/stubs.py
Labels: 5 - Ready to merge, Effort - short

#8217 Fix syntax in docs
  docs/source/user/5minguide.rst
Labels: 5 - Ready to merge, Effort - short

#8200 Make the NRT use the "unsafe" allocation API by default.
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/core/runtime/_nrt_pythonmod.c
  numba/core/runtime/context.py
  numba/core/runtime/nrt.c
  numba/core/runtime/nrt.h
Labels: 5 - Ready to merge, Effort - medium

#8228 Fix typo in @vectorize docstring and a NumPy spelling.
  numba/np/ufunc/decorators.py
Labels: 5 - Ready to merge, Effort - short

#8040 Support for Numpy BitGenerators PR#3: Advanced Distributions Support.
  docs/source/reference/numpysupported.rst
  numba/np/random/distributions.py
  numba/np/random/generator_methods.py
  numba/tests/test_np_randomgen.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8106 Remove injection of atomic JIT functions into NRT memsys.
  numba/core/runtime/_nrt_pythonmod.c
  numba/core/runtime/nrt.cpp
  numba/core/runtime/nrt.h
  numba/core/runtime/nrt.py
  numba/pycc/cc.py
  numba/pycc/modulemixin.c
  setup.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8245 Fix links in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: 5 - Ready to merge

#7733 fix for /tmp/tmp access issues
  numba/pycc/platform.py
Labels: 5 - Ready to merge, Effort - medium

#8239 Add decorator to run a test in a subprocess.
  numba/tests/support.py
  numba/tests/test_builtins.py
  numba/tests/test_debuginfo.py
  numba/tests/test_np_functions.py
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge, Effort - medium

#8255 CUDA: Make numba.cuda.tests.doc_examples.ffi a module to fix #8252
  numba/cuda/tests/doc_examples/ffi/__init__.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#8269 Cherry pick #8255
  numba/cuda/tests/doc_examples/ffi/__init__.py
Labels: 5 - Ready to merge

#8274 Update version support table doc for 0.56.
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8279 Cherry pick for 0.56 release
  CHANGE_LOG
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8264 remove `mk_unique_var` from `parfor_lowering_utils.py`
  numba/parfors/parfor_lowering_utils.py
Labels: 5 - Ready to merge, Effort - short

#8265 Remove `mk_unique_var` from `array_analysis.py`
  numba/parfors/array_analysis.py
Labels: 5 - Ready to merge, Effort - short

#8276 Move Azure to use macos-11.
  azure-pipelines.yml
Labels: 5 - Ready to merge, Effort - short

#8289 Revert #8265.
  numba/parfors/array_analysis.py
Labels: 5 - Ready to merge

#8010 Add support for fp16 comparison native operators
  numba/core/typeconv/rules.py
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/tests/cudapy/test_operator.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8220 Added the interval example as doctest
  docs/source/extending/interval-example.rst
  numba/tests/doc_examples/test_interval_example.py
Labels: 5 - Ready to merge, Effort - short

#8240 Add get_shared_mem_per_block method to Dispatcher
  docs/source/cuda-reference/kernel.rst
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8253 CUDA: Verify NVVM IR prior to compilation
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/tests/cudadrv/test_inline_ptx.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/nocuda/test_nvvm.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#8292 update checklist
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#8235 Make the NRT stats counters optional.
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/core/runtime/_nrt_pythonmod.c
  numba/core/runtime/nrt.cpp
  numba/core/runtime/nrt.h
  numba/core/runtime/nrt.py
  numba/tests/support.py
  numba/tests/test_linalg.py
  numba/tests/test_nrt.py
  numba/tests/test_nrt_refct.py
  numba/tests/test_polynomial.py
  numba/tests/test_print.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8283 Clean up / remove support for old NumPy versions
  numba/core/typing/npydecl.py
  numba/np/arraymath.py
  numba/np/npdatetime.py
Labels: 5 - Ready to merge, Effort - short
