Repository numba/numba, pull requests merged in 2022-10, with the labels that each got.

#8446 add version info in ImportError's
  numba/__init__.py
Labels: 5 - Ready to merge, Effort - short

#8469 Correctly handle optional types in parfors lowering
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - short

#8486 Restrict the TBB development package to supported version in Azure.
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#8468 Reference test suite in installation documentation
  docs/source/developer/contributing.rst
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8475 Remove setuptools version pin
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/gpuci/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/environment.yml
  docs/source/user/installing.rst
  setup.py
Labels: BuildFarm Passed, 5 - Ready to merge

#8490 Restore installing SciPy from defaults instead of conda-forge on public CI
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#8259 Add `np.broadcast_to(scalar_array, ())`
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/numpy_support.py
  numba/tests/test_array_manipulation.py
  numba/tests/test_np_functions.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8482 Fix #8477: Allow copies with different strides for 0-length data
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8503 Update version support table for 0.56.3
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8504 Update CHANGE_LOG for 0.56.3
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#8508 This updates the release checklists to capture some more checks.
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#8435 Migrate `np.atleast_?` functions from `glue_lowering` to `overload`
  numba/core/typing/npydecl.py
  numba/np/arrayobj.py
Labels: 5 - Ready to merge, Effort - medium

#7067 Implement np.isclose
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Effort - medium

#8267 Fix segfault for invalid axes in np.split
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#8315 Add get_local_mem_per_thread method to Dispatcher
  docs/source/cuda-reference/kernel.rst
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#8495 Removes context.compile_internal where easy on `numba/cpython/listobj.py`
  numba/core/typing/listdecl.py
  numba/cpython/listobj.py
  numba/tests/test_lists.py
Labels: 5 - Ready to merge, Effort - medium

#8518 Adjust stencil tests to use hardcoded python source opposed to AST.
  .flake8
  numba/tests/test_stencils.py
Labels: 5 - Ready to merge, Effort - long

#8522 Import jitclass from numba.experimental in jitclass documentation
  docs/source/user/jitclass.rst
Labels: 5 - Ready to merge, Effort - short

#8524 Fix grammar in stencil.rst
  docs/source/user/stencil.rst
Labels: 5 - Ready to merge, Effort - short

#8532 Vary NumPy version on gpuCI
  buildscripts/gpuci/build.sh
Labels: CUDA, 5 - Ready to merge, Effort - short

#8526 Fix broken url
  docs/source/user/pycc.rst
Labels: 5 - Ready to merge, Effort - short

#8527 Fix grammar in troubleshoot.rst
  docs/source/user/troubleshoot.rst
Labels: 5 - Ready to merge, Effort - short

#8539 Fix #8534, np.broadcast_to should update array size attr.
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge, Effort - short

#8541 Remove restoration of "free" channel in Azure CI windows builds.
  buildscripts/incremental/setup_conda_environment.cmd
Labels: 5 - Ready to merge, Effort - short

#8536 Fix fusion bug.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - medium

#8542 CUDA: Make arg optional for Stream.add_callback()
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_streams.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#8549 Fix rstcheck in Azure CI builds, update sphinx dep and docs to match
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/extending/low-level.rst
  docs/source/reference/pysupported.rst
Labels: 5 - Ready to merge, Effort - short
