Repository numba/numba, pull requests merged in 2022-04, with the labels that each got.

#7660 Add support for np.broadcast_arrays
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
Labels: 5 - Ready to merge, Effort - medium

#7946 instructions for creating a build environment were outdated
  docs/source/developer/contributing.rst
Labels: doc, 5 - Ready to merge, Effort - short

#7956 Stop using pip for 3.10 on public ci (Revert "start testing Python 3.10 on public CI")
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#7957 Use cloudpickle for disk caches
  numba/core/caching.py
  numba/tests/test_caching.py
Labels: 5 - Ready to merge, Effort - short

#7959 Permit a new array model to have a super set of array model fields.
  numba/np/arrayobj.py
  numba/tests/test_ndarray_subclasses.py
Labels: 5 - Ready to merge, Effort - short

#7961 `numba.typed.typeddict.Dict.get` uses `castedkey` to avoid returning default value even if the key is present
  numba/tests/test_dictobject.py
  numba/typed/dictobject.py
Labels: 5 - Ready to merge, Effort - short

#7963 remove the roadmap from the sphinx based docs
  docs/source/developer/index.rst
  docs/source/developer/roadmap.rst
Labels: 5 - Ready to merge

#7965 Use uuid4 instead of PID in cache temp name to prevent collisions.
  numba/core/caching.py
Labels: 5 - Ready to merge, Effort - short

#7971 lru cache for configure call
  numba/cuda/dispatcher.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#7783 remove upper limit on Python version
  setup.py
Labels: 5 - Ready to merge, Effort - short

#7958 `numpy.clip` accept `numpy.array` for `a_min`, `a_max`
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge

#7986 Small caching refactor to support target cache implementations
  numba/core/base.py
  numba/core/caching.py
  numba/core/compiler.py
Labels: 5 - Ready to merge, Effort - short

#7940 Implemented `np.allclose` in `numba/np/arraymath.py`
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Effort - medium

#8004 CUDA fixes for Windows
  docs/source/cuda/ipc.rst
  numba/cuda/codegen.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudapy/test_ipc.py
  numba/tests/support.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#8014 Fix support for {real,imag} array attrs in Parfors.
  numba/parfors/array_analysis.py
  numba/tests/test_array_analysis.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - short
