Repository numba/numba, pull requests merged in 2022-01, with the labels that each got.

#7586 Support for len on dict.keys, dict.values, and dict.items
  numba/tests/test_dictobject.py
  numba/typed/dictobject.py
Labels: 5 - Ready to merge, Effort - short

#7651 DOC: pypi and conda-forge badges
  README.rst
Labels: doc, 5 - Ready to merge, Effort - short

#7684 DOC: remove incorrect warning in np.random reference
  docs/source/reference/numpysupported.rst
Labels: doc, 5 - Ready to merge, Effort - short

#7695 `IntEnumMember` support for `np.empty`, `np.zeros`, and `np.ones`
  numba/core/typing/npydecl.py
  numba/tests/test_enums.py
Labels: 5 - Ready to merge, Effort - short

#7704 Move the type annotation pass to post legalization.
  .flake8
  numba/core/compiler.py
  numba/core/typed_passes.py
  numba/tests/test_annotations.py
  numba/tests/test_array_analysis.py
  numba/tests/test_inlining.py
  numba/tests/test_remove_dead.py
Labels: 5 - Ready to merge, Effort - medium

#7709 CUDA: Fixes missing type annotation pass following #7704
  buildscripts/gpuci/build.sh
  numba/cuda/compiler.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#7718 Bump llvmlite dependency to 0.39.0dev0 for Numba 0.56.0dev0
  README.rst
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge, Effort - short

#7732 update release checklist following 0.55.0 RC1
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
Labels: 3 - Ready for Review

#7736 Update CHANGE_LOG for 0.55.0 final.
  CHANGE_LOG
Labels: 4 - Waiting on reviewer

#7680 CUDA Docs: include example calling slow matmul
  docs/source/cuda/examples.rst
  numba/cuda/tests/doc_examples/test_matmul.py
Labels: doc, CUDA, 5 - Ready to merge, Effort - short

#7724 Update URLs in error messages to refer to RTD docs.
  numba/core/codegen.py
  numba/core/errors.py
  numba/core/ir_utils.py
  numba/core/object_mode_passes.py
  numba/core/typed_passes.py
  numba/core/typeinfer.py
  numba/cuda/errors.py
  numba/misc/gdb_hook.py
  numba/tests/test_deprecations.py
Labels: 5 - Ready to merge, Effort - short

#7745 Fix the release year for Numba 0.55 change log entry.
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#7748 Fix #7713: Ensure _prng_random_hash return has correct bitwidth
  numba/cpython/hashing.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#7700 Support for scalar arguments in Np.ascontiguousarray
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge, Effort - medium

#7619 CUDA: Fix linking with PTX when compiling lazily
  numba/cuda/decorators.py
  numba/cuda/tests/cudadrv/test_linker.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#7682 performance improvements to np.full and np.ones
  numba/np/arrayobj.py
Labels: 5 - Ready to merge, Effort - short

#7752 Fix #7751: Use original filename for array exprs
  numba/np/ufunc/array_exprs.py
Labels: 5 - Ready to merge, Effort - short

#7763 Update Read the Docs configuration (automatic)
  .readthedocs.yml
Labels: 5 - Ready to merge, Effort - medium

#7776 Updates coverage.py config
  .coveragerc
Labels: 5 - Ready to merge, Effort - short

#7777 Remove reference existing issue from GH template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 5 - Ready to merge, Effort - short

#7778 Remove long deprecated flags from the CLI.
  docs/source/user/cli.rst
  numba/misc/numba_entry.py
Labels: 5 - Ready to merge, Effort - short

#7699 CUDA: Provide helpful error if the return type is missing for `declare_device`
  numba/cuda/decorators.py
  numba/cuda/tests/cudapy/test_device_func.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#7728 Document that AOT-compiled functions do not check arg types
  docs/source/user/pycc.rst
Labels: doc, 5 - Ready to merge, Effort - short

#7740 CUDA Python 11.6 support
  buildscripts/condarecipe.local/meta.yaml
  docs/source/cuda/bindings.rst
  docs/source/cuda/overview.rst
  docs/source/reference/envvars.rst
  docs/source/user/installing.rst
  numba/core/config.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_profiler.py
  numba/cuda/tests/cudadrv/test_ptds.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - short

#7788 Avoid issue with DI gen for arrayexprs.
  numba/tests/gdb/test_array_arg.py
  numba/tests/test_gdb_dwarf.py
Labels: 5 - Ready to merge, Effort - short

#7729 Handle Omitted/OmittedArgDataModel in DI generation.
  numba/core/datamodel/models.py
  numba/core/debuginfo.py
  numba/tests/test_debuginfo.py
Labels: 5 - Ready to merge, Effort - medium

#7712 Fixing issue 7693
  numba/cuda/simulator/kernel.py
  numba/cuda/tests/cudapy/test_record_dtype.py
  numba/np/arrayobj.py
  numba/tests/test_record_dtype.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#7744 Fix issues with locating/parsing source during DebugInfo emission.
  numba/core/errors.py
  numba/core/lowering.py
  numba/tests/test_debuginfo.py
Labels: 5 - Ready to merge, Effort - medium

#7749 Refactor threading layer priority tests to not use stdout/stderr
  numba/tests/test_parallel_backend.py
Labels: 5 - Ready to merge, Effort - short

#7755 CUDA: Deprecate support for CC < 5.3 and CTK < 10.2
  docs/source/cuda/overview.rst
  docs/source/reference/deprecation.rst
  docs/source/user/installing.rst
  numba/cuda/api.py
Labels: doc, CUDA, 5 - Ready to merge, Effort - short

#7782 adding reminder to check on deprecations
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short

#7796 update change-log for 0.55.1
  CHANGE_LOG
Labels: 3 - Ready for Review, Effort - short

#7764 Add dbg_optnone and dbg_extend_lifetimes flags
  docs/source/user/troubleshoot.rst
  numba/core/base.py
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/ir_utils.py
  numba/core/lowering.py
  numba/core/options.py
  numba/core/postproc.py
  numba/core/typed_passes.py
  numba/tests/test_debuginfo.py
  numba/tests/test_obj_lifetime.py
Labels: 5 - Ready to merge, Effort - long

#7771 Move function unique ID to abi-tags
  numba/core/base.py
  numba/core/bytecode.py
  numba/core/funcdesc.py
  numba/core/itanium_mangler.py
  numba/core/lowering.py
  numba/core/typeinfer.py
  numba/core/types/functions.py
  numba/cuda/target.py
  numba/tests/gdb/test_break_on_symbol.py
  numba/tests/gdb/test_break_on_symbol_version.py
  numba/tests/test_gdb_dwarf.py
Labels: 5 - Ready to merge, Effort - medium

#7799 update the release checklist post 0.55.1
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, Effort - short
