Repository numba/numba, pull requests merged in 2022-08, with the labels that each got.

#7884 Implement getattr builtin.
  docs/source/reference/pysupported.rst
  numba/cpython/builtins.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge, Effort - medium

#8041 Support for Numpy BitGenerators PR#4: Generator().integers() Support.
  docs/source/reference/numpysupported.rst
  numba/np/random/generator_methods.py
  numba/np/random/random_methods.py
  numba/tests/test_np_randomgen.py
Labels: 5 - Ready to merge, Effort - long

#8297 Add __name__ attribute to CUDAUFuncDispatcher and test case
  numba/cuda/tests/cudapy/test_vectorize.py
  numba/cuda/vectorizers.py
Labels: 5 - Ready to merge, Effort - short

#8302 CUDA: Revert numba_nvvm intrinsic name workaround
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/nvvmutils.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8247 Fix issue 8127
  numba/np/arrayobj.py
  numba/tests/test_boundscheck.py
Labels: 5 - Ready to merge, Effort - short

#8320 Add __name__ support for GUFuncs
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/vectorizers.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short

#8336 Fix typos of "Generalized" in GUFunc-related code
  numba/cuda/vectorizers.py
  numba/np/ufunc/decorators.py
  numba/np/ufunc/deviceufunc.py
Labels: 5 - Ready to merge, Effort - short

#8299 Fix build for mingw toolchain
  numba/np/ufunc/omppool.cpp
  numba/np/ufunc/workqueue.c
  setup.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8325 Remove use of mk_unique_var in stencil.py
  numba/stencils/stencil.py
Labels: 5 - Ready to merge

#8158 adding -pthread for linux-ppc64le in setup.py
  numba/np/ufunc/omppool.cpp
  setup.py
Labels: 5 - Ready to merge, Effort - medium

#8354 pin setuptools to < 65 and switch from mamba to conda on RTD
  .readthedocs.yml
  buildscripts/gpuci/build.sh
  docs/environment.yml
Labels: 5 - Ready to merge, Effort - short

#8356 Update setup.py, buildscripts, CI and docs to require setuptools<60.
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/gpuci/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/environment.yml
  docs/source/user/installing.rst
  setup.py
Labels: 5 - Ready to merge, Effort - short

#8061 Migrate random `glue_lowering` to `overload` where easy
  numba/core/typing/randomdecl.py
  numba/cpython/randomimpl.py
  numba/tests/test_random.py
Labels: 5 - Ready to merge

#8216 chore: Set permissions for GitHub actions
  .github/workflows/stale.yml
Labels: 5 - Ready to merge

#8295 Add get_const_mem_size method to Dispatcher
  docs/source/cuda-reference/kernel.rst
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8310 CUDA: Fix Issue #8309 - atomics don't work on complex components
  numba/core/typing/arraydecl.py
  numba/cuda/tests/cudapy/test_complex.py
  numba/np/arrayobj.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8321 Fix literal_unroll pass erroneously exiting on non-conformant loop.
  numba/core/untyped_passes.py
  numba/tests/test_mixed_tuple_unroller.py
Labels: 5 - Ready to merge, Effort - short

#8335 Remove deprecated pycc script and related source.
  docs/source/developer/repomap.rst
  numba/pycc/__init__.py
  numba/pycc/pycc
  numba/tests/test_pycc.py
  setup.py
Labels: 5 - Ready to merge, Effort - short

#8338 Calculate reductions before fusion so that use of reduction vars can stop fusion.
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, Effort - medium

#8342 Upgrade to ubuntu-20.04 for azure pipeline CI
  azure-pipelines.yml
Labels: 5 - Ready to merge, Effort - short

#8343 Eliminate references to type annotation in compile_ptx
  numba/cuda/compiler.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#8357 Clean up the buildscripts directory.
  buildscripts/appveyor/run_with_env.cmd
  buildscripts/condarecipe_clone_icc_rt/bld.bat
  buildscripts/condarecipe_clone_icc_rt/build.sh
  buildscripts/condarecipe_clone_icc_rt/meta.yaml
  buildscripts/condarecipe_clone_icc_rt/scripts/build.py
  docs/source/developer/repomap.rst
Labels: 5 - Ready to merge, Effort - short

#8359 adding warnings about cache behaviour
  docs/source/developer/caching.rst
  docs/source/user/jit.rst
Labels: doc, 5 - Ready to merge, Effort - short

#8331 Extend docs with info on how to call C functions from Numba
  docs/source/user/cfunc.rst
Labels: 5 - Ready to merge, Effort - short

#8266 Remove `mk_unique_var` in `untyped_passes.py`
  numba/core/untyped_passes.py
Labels: 5 - Ready to merge, Effort - medium

#8256 Migrate linear algebra functions from glue_lowering
  numba/core/typing/npydecl.py
  numba/np/linalg.py
Labels: 5 - Ready to merge

#8384 Move strace() check into tests that actually need it.
  numba/tests/support.py
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge, Effort - short

#8374 Don't pickle LLVM IR for CUDA code libraries
  numba/cuda/codegen.py
  numba/cuda/tests/cudapy/cache_usecases.py
  numba/cuda/tests/cudapy/jitlink.ptx
  numba/cuda/tests/cudapy/test_caching.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8377 Add support for NumPy 1.23.
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  docs/source/user/installing.rst
  numba/cuda/cudadrv/devicearray.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8407 Pin NumPy version to 1.18-1.24
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/installing.rst
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge
