Repository numba/numba, pull requests merged in 2023-05, with the labels that each got.

#8932 Fix 0.57 release changelog
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#8935 Cherrypick for 0.57 final release
  CHANGE_LOG
Labels: 5 - Ready to merge, Effort - short

#8854 Updated mk_alloc to support Numba-Dpex compute follows data.
  numba/core/ir_utils.py
Labels: ParallelAccelerator, 5 - Ready to merge

#8730 Update dev-docs
  docs/source/developer/contributing.rst
Labels: 5 - Ready to merge

#8491 Added support for multidimensional array indexing
  docs/source/reference/numpysupported.rst
  numba/core/typing/arraydecl.py
  numba/np/arrayobj.py
  numba/tests/test_fancy_indexing.py
  numba/tests/test_indexing.py
Labels: 5 - Ready to merge, Effort - long

#8885 Fix np.allclose not handling default args
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#8937 Remove old Website development documentation
  MANIFEST.in
  docs/gh-pages.py
  docs/source/developer/contributing.rst
  docs/source/developer/repomap.rst
Labels: doc, 5 - Ready to merge

#7262 fix order of handling and casting
  numba/tests/test_listobject.py
  numba/tests/test_typedlist.py
  numba/typed/listobject.py
Labels: 5 - Ready to merge

#8633 DOC: Convert vectorize and guvectorize examples to doctests
  docs/source/user/vectorize.rst
  numba/tests/doc_examples/test_examples.py
Labels: 5 - Ready to merge

#8958 resurrect the import, this time in the registry initialization
  numba/core/cpu.py
  numba/cuda/target.py
Labels: 5 - Ready to merge

#8964 fix missing nopython keyword in cuda random module
  numba/cuda/random.py
Labels: CUDA, 5 - Ready to merge

#8965 fix return dtype for np.angle
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#8976 Fix index URL for ptxcompiler/cubinlinker packages.
  docs/source/cuda/minor_version_compatibility.rst
Labels: doc, CUDA, 5 - Ready to merge

#8968 Cherry-pick #8895 into release0.57 (CUDA: Enable caching functions that use CG)
  numba/cuda/codegen.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/cache_usecases.py
  numba/cuda/tests/cudapy/test_caching.py
Labels: BuildFarm Passed, 5 - Ready to merge

#8979 Cherry-pick #8976 (fix index URL for ptxcompiler/cubinlinker packages) for Release 0.57.1
  docs/source/cuda/minor_version_compatibility.rst
Labels: doc, CUDA, 5 - Ready to merge

#8978 Import MVC packages when using MVCLinker.
  numba/cuda/cudadrv/driver.py
  numba/cuda/tests/cudadrv/test_mvc.py
  numba/misc/numba_sysinfo.py
Labels: CUDA, 5 - Ready to merge

#8983 Fix typo in deprecation.rst
  docs/source/reference/deprecation.rst
Labels: doc, 5 - Ready to merge
