Repository numba/numba, pull requests merged in 2023-12, with the labels that each got.

#9255 Fix SSA to consider variables whose use is not dominated by the definition
  docs/upcoming_changes/9242.bug_fix.rst
  numba/core/ssa.py
  numba/core/typed_passes.py
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
  numba/tests/test_ssa.py
Labels: 5 - Ready to merge, Effort - medium

#9267 CUDA: Fix dropping of kernels by nvjitlink, by implementing the used list
  docs/upcoming_changes/9267.cuda.rst
  numba/core/lowering.py
  numba/core/utils.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/target.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudapy/test_debug.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#9307 Upgrade to cloudpickle 3.0.0
  numba/cloudpickle/__init__.py
  numba/cloudpickle/cloudpickle.py
  numba/cloudpickle/cloudpickle_fast.py
  numba/cloudpickle/compat.py
Labels: 5 - Ready to merge, skip_release_notes

#9309 Continue #9044, prevent compilation on the CPU target when listing tests.
  docs/upcoming_changes/9309.change.rst
  numba/stencils/stencil.py
  numba/tests/chained_assign_usecases.py
  numba/tests/errorhandling_usecases.py
  numba/tests/inlining_usecases.py
  numba/tests/npyufunc/test_ufuncbuilding.py
  numba/tests/npyufunc/ufuncbuilding_usecases.py
  numba/tests/test_chained_assign.py
  numba/tests/test_errorhandling.py
  numba/tests/test_inlining.py
  numba/tests/test_recursion.py
  numba/tests/test_runtests.py
  numba/tests/test_serialize.py
  numba/tests/test_typedlist.py
  numba/tests/typedlist_usecases.py
Labels: 5 - Ready to merge

#9318 GPU CI: Test with Python 3.9-3.12
  buildscripts/gpuci/build.sh
Labels: CUDA, 5 - Ready to merge, Effort - short, skip_release_notes

#9326 Add docs for LOAD_FAST_AND_CLEAR changes
  docs/source/developer/bytecode.rst
  docs/source/developer/index.rst
Labels: 5 - Ready to merge, skip_release_notes

#9336 Add TargetLibraryInfo pass to CPU LLVM pipeline.
  docs/upcoming_changes/9336.improvement.rst
  numba/_helperlib.c
  numba/_helpermod.c
  numba/core/codegen.py
  numba/np/npyfuncs.py
  numba/tests/npyufunc/test_ufunc.py
Labels: BuildFarm Passed, 5 - Ready to merge

#9342 Fix flake8 checks for v6.1.0
  numba/np/arraymath.py
  numba/np/numpy_support.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9303 Add category to warning
  numba/core/errors.py
  numba/np/ufunc/parallel.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9168 fix the `get_template_info` method in `overload_method` template
  numba/core/typing/templates.py
  numba/tests/test_typeinfer.py
Labels: 5 - Ready to merge, skip_release_notes

#9334 Fix parfor reduction issue with Python 3.12.
  docs/upcoming_changes/9334.bug_fix.rst
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#9058 Fix gufunc with multiple outputs
  docs/upcoming_changes/9049.bug_fix.rst
  numba/np/ufunc/gufunc.py
  numba/tests/npyufunc/test_gufunc.py
Labels: 5 - Ready to merge, Effort - short

#9341 Add configuration variable to force llvmlite memory manager on / off
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9341.new_feature.rst
  numba/core/codegen.py
  numba/core/config.py
Labels: 5 - Ready to merge, Effort - short

#9335 Add validation capability for user generated towncrier .rst files.
  .github/workflows/towncrier.yml
  docs/upcoming_changes/9089.bug_fix.rst
  docs/upcoming_changes/9141.np_support.rst
  docs/upcoming_changes/9144.bug_fix.rst
  docs/upcoming_changes/9154.np_support.rst
  docs/upcoming_changes/9169.bug_fix.rst
  docs/upcoming_changes/9189.bug_fix.rst
  docs/upcoming_changes/9244.bug_fix.rst
  docs/upcoming_changes/9246.highlight.rst
  docs/upcoming_changes/9249.np_support.rst
  docs/upcoming_changes/9310.highlight.rst
  docs/upcoming_changes/9315.change.rst
  docs/upcoming_changes/9335.infrastructure.rst
  docs/upcoming_changes/README.rst
  maint/towncrier_rst_validator.py
Labels: 5 - Ready to merge

#9279 CUDA: Add support for CUDA 12.0 Windows conda packages
  docs/upcoming_changes/9279.cuda.rst
  numba/cuda/cuda_paths.py
Labels: CUDA, 5 - Ready to merge

#9353 Remove `numba.generated_jit`
  docs/source/developer/custom_pipeline.rst
  docs/source/reference/deprecation.rst
  docs/source/reference/jit-compilation.rst
  docs/source/user/generated-jit.rst
  docs/source/user/index.rst
  docs/upcoming_changes/9353.expired.rst
  numba/__init__.py
  numba/core/bytecode.py
  numba/core/decorators.py
  numba/core/dispatcher.py
  numba/core/funcdesc.py
  numba/tests/cache_usecases.py
  numba/tests/serialize_usecases.py
  numba/tests/test_caching.py
  numba/tests/test_deprecations.py
  numba/tests/test_dictimpl.py
  numba/tests/test_dispatcher.py
  numba/tests/test_nested_calls.py
  numba/tests/test_pipeline.py
  numba/tests/test_serialize.py
Labels: 5 - Ready to merge

#9356 Refactor print tests to avoid NRT leak issue.
  numba/tests/test_print.py
Labels: 5 - Ready to merge, skip_release_notes

#9352 Removing object mode fallback from `@jit`.
  docs/source/reference/deprecation.rst
  docs/source/user/5minguide.rst
  docs/upcoming_changes/9352.expired.rst
  numba/core/boxing.py
  numba/core/compiler.py
  numba/core/decorators.py
  numba/core/dispatcher.py
  numba/core/object_mode_passes.py
  numba/tests/npyufunc/test_ufuncbuilding.py
  numba/tests/test_analysis.py
  numba/tests/test_annotations.py
  numba/tests/test_builtins.py
  numba/tests/test_closure.py
  numba/tests/test_deprecations.py
  numba/tests/test_dispatcher.py
  numba/tests/test_event.py
  numba/tests/test_gil.py
  numba/tests/test_indexing.py
  numba/tests/test_jitmethod.py
  numba/tests/test_looplifting.py
  numba/tests/test_npdatetime.py
  numba/tests/test_object_mode.py
  numba/tests/test_recursion.py
  numba/tests/test_vectorization_type_inference.py
  numba/tests/test_warnings.py
Labels: 5 - Ready to merge, Effort - medium

#9346 Setting ``NUMBA_CAPTURED_ERRORS=old_style`` will now raise warnings.
  docs/upcoming_changes/9346.deprecation.rst
  numba/core/config.py
  numba/core/errors.py
  numba/tests/support.py
  numba/tests/test_config.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge, Effort - medium

#9351 Made Python 3.12 support rst note more verbose
  docs/upcoming_changes/9246.highlight.rst
Labels: 5 - Ready to merge, skip_release_notes

#9357 Fix a typo in `_set_init_process_lock` warning.
  numba/np/ufunc/parallel.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9358 Remove note about OpenMP restriction in wheels.
  docs/source/user/threading-layer.rst
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9359 Fix test_jit_module test against objmode fallback.
  numba/tests/test_jit_module.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9347 Make Numba's deprecation warnings subclasses of the builtin ones.
  docs/upcoming_changes/9347.improvement.rst
  numba/core/errors.py
  numba/tests/test_warnings.py
Labels: 5 - Ready to merge, Effort - medium

#9360 AzureCI changes. RVSDG test config should still test its assigned test slice
  buildscripts/incremental/test.sh
Labels: 5 - Ready to merge, skip_release_notes

#9362 Fix ``np.MachAr`` warning matching in test.
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, skip_release_notes

#9368 Added 0.59.0 release notes
  docs/source/release/0.59.0-notes.rst
Labels: 5 - Ready to merge, skip_release_notes

#9371 Pin versions for release0.59
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  numba/testing/main.py
  setup.py
Labels: 4 - Waiting on CI, skip_release_notes
