Repository numba/numba, pull requests merged in 2023-03, with the labels that each got.

#8736 Implement np.lib.stride_tricks.sliding_window_view
  docs/source/reference/numpysupported.rst
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
Labels: numpy, 5 - Ready to merge

#8339 Fix #8291 parfor leak of redtoset variable
  numba/parfors/parfor_lowering.py
Labels: 5 - Ready to merge, Effort - short

#8691 NumPy 1.24
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/gpuci/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/user/installing.rst
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/np/arraymath.py
  numba/np/ufunc/_internal.c
  numba/stencils/stencilparfor.py
  numba/tests/test_array_methods.py
  numba/tests/test_comprehension.py
  numba/tests/test_linalg.py
  numba/tests/test_mathlib.py
  numba/tests/test_np_functions.py
Labels: highpriority, 5 - Ready to merge, Effort - medium

#8781 Ensure gc.collect() is called before checking refcount in tests.
  numba/tests/support.py
  numba/tests/test_generators.py
  numba/tests/test_lists.py
  numba/tests/test_np_randomgen.py
  numba/tests/test_record_dtype.py
  numba/tests/test_sets.py
Labels: 5 - Ready to merge, Effort - short

#8790 CUDA compare and swap with index
  docs/source/cuda-reference/kernel.rst
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/simulator/kernelapi.py
  numba/cuda/stubs.py
  numba/cuda/tests/cudapy/test_atomics.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#8711 Python 3.11 tracing support (continuation of #8670).
  numba/_dispatcher.cpp
  numba/_helperlib.c
  numba/tests/test_profiler.py
Labels: 5 - Ready to merge, Python 3.11

#7255 CUDA: Support CUDA Toolkit conda packages from NVIDIA
  docs/source/cuda/minor_version_compatibility.rst
  numba/cuda/cuda_paths.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvvm.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - long

#8024 Allow converting NumPy datetimes to int
  numba/core/typing/builtins.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge

#8594 Fix various CUDA lineinfo issues
  numba/core/compiler.py
  numba/core/debuginfo.py
  numba/core/lowering.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/decorators.py
  numba/cuda/dispatcher.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_debuginfo.py
  numba/cuda/tests/cudapy/test_inspect.py
  numba/cuda/tests/cudapy/test_lineinfo.py
Labels: highpriority, BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - long

#8771 Update vendored Versioneer from 0.14 to 0.28
  .flake8
  numba/_version.py
  numba/misc/help/inspector.py
  setup.cfg
  setup.py
  versioneer.py
Labels: 5 - Ready to merge

#8795 Add pending-deprecation warnings for ``numba.pycc``
  docs/source/reference/aot-compilation.rst
  docs/source/reference/deprecation.rst
  docs/source/user/pycc.rst
  numba/pycc/__init__.py
  numba/tests/support.py
  numba/tests/test_deprecations.py
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge, Effort - medium

#8535 LLVM14
  buildscripts/condarecipe.local/meta.yaml
  numba/core/callconv.py
  numba/core/codegen.py
  numba/misc/llvm_pass_timings.py
  numba/tests/test_array_reductions.py
  numba/tests/test_debuginfo.py
  numba/tests/test_np_functions.py
  numba/tests/test_np_randomgen.py
  numba/tests/test_parfors.py
  numba/tests/test_refop_pruning.py
  numba/tests/test_svml.py
Labels: 4 - Waiting on CI, Effort - long

#8810 Fix llvmlite dependency in meta.yaml
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge

#8167 CUDA: Facilitate and document passing arrays / pointers to foreign functions
  docs/source/cuda/cuda_ffi.rst
  docs/source/cuda/cudapysupported.rst
  numba/cuda/target.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/data/jitlink.cu
  numba/cuda/tests/cudadrv/data/jitlink.ptx
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_caching.py
  numba/cuda/tests/cudapy/test_cffi.py
  numba/cuda/tests/data/__init__.py
  numba/cuda/tests/data/cuda_include.cu
  numba/cuda/tests/data/error.cu
  numba/cuda/tests/data/jitlink.cu
  numba/cuda/tests/data/jitlink.ptx
  numba/cuda/tests/data/warn.cu
  numba/cuda/tests/doc_examples/ffi/functions.cu
  numba/cuda/tests/doc_examples/test_ffi.py
  setup.py
Labels: highpriority, BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8183 Add `n_keys` option to Dict.empty()
  numba/_helpermod.c
  numba/cext/dictobject.c
  numba/cext/dictobject.h
  numba/tests/test_dictimpl.py
  numba/typed/dictobject.py
  numba/typed/typeddict.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - medium

#8238 Advanced Indexing Support #1
  numba/core/typing/arraydecl.py
  numba/tests/test_array_manipulation.py
  numba/tests/test_fancy_indexing.py
  numba/tests/test_record_dtype.py
Labels: 5 - Ready to merge, Effort - medium

#8803 Attempted fix to #8789 by changing `compile_ptx` to accept a signature instead of argument tuple
  numba/cuda/compiler.py
  numba/cuda/tests/cudapy/test_casting.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_libdevice.py
Labels: CUDA, 5 - Ready to merge

#8826 CUDA CFFI test: conditionally require cffi module
  numba/cuda/tests/cudapy/test_cffi.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#8822 Merge py3.11 branch to main
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  numba/_devicearray.cpp
  numba/_dispatcher.cpp
  numba/_dynfunc.c
  numba/_helperlib.c
  numba/cloudpickle/__init__.py
  numba/cloudpickle/cloudpickle.py
  numba/cloudpickle/cloudpickle_fast.py
  numba/cloudpickle/compat.py
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/controlflow.py
  numba/core/interpreter.py
  numba/core/ir.py
  numba/core/ir_utils.py
  numba/core/lowering.py
  numba/core/runtime/_nrt_python.c
  numba/core/runtime/context.py
  numba/core/transforms.py
  numba/core/utils.py
  numba/cpython/hashing.py
  numba/experimental/jitclass/_box.c
  numba/mviewbuf.c
  numba/np/ufunc/_internal.c
  numba/np/ufunc/array_exprs.py
  numba/tests/support.py
  numba/tests/test_debug.py
  numba/tests/test_exceptions.py
  numba/tests/test_extended_arg.py
  numba/tests/test_flow_control.py
  numba/tests/test_hashing.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_operators.py
  numba/tests/test_parfors.py
  numba/tests/test_profiler.py
  numba/tests/test_runtests.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
  setup.py
Labels: 5 - Ready to merge, Effort - medium

#8833 Fix typeguard import hook location.
  runtests.py
Labels: 5 - Ready to merge, Effort - short

#8836 Fix failing typeguard test.
  numba/tests/test_typeguard.py
Labels: 5 - Ready to merge, Effort - short

#8843 Pin typeguard to 3.0.1 in AzureCI.
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, Effort - short

#8341 CUDA: Support multiple outputs for Generalized Ufuncs
  docs/source/cuda/ufunc.rst
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/vectorizers.py
  numba/np/ufunc/deviceufunc.py
Labels: highpriority, BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8476 Make setuptools optional at runtime.
  numba/pycc/__init__.py
  numba/pycc/cc.py
  numba/pycc/platform.py
  numba/tests/pycc_distutils_usecase/setup_distutils.py
  numba/tests/pycc_distutils_usecase/setup_distutils_nested.py
  numba/tests/pycc_distutils_usecase/setup_setuptools.py
  numba/tests/pycc_distutils_usecase/setup_setuptools_nested.py
  numba/tests/support.py
  numba/tests/test_extending.py
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge, Effort - medium

#8837 Update AzureCI matrix for Python 3.11/NumPy 1.21..1.24
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge, Effort - short

#8839 Add Dynamic Shared Memory example.
  docs/source/cuda/memory.rst
Labels: doc, CUDA, 5 - Ready to merge

#8134 Support non-constant exception values in JIT
  .flake8
  docs/source/reference/pysupported.rst
  numba/_helperlib.c
  numba/_helpermod.c
  numba/core/callconv.py
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/generators.py
  numba/core/ir.py
  numba/core/lowering.py
  numba/core/pythonapi.py
  numba/core/rewrites/static_raise.py
  numba/core/serialize.py
  numba/core/typeinfer.py
  numba/core/untyped_passes.py
  numba/pycc/compiler.py
  numba/pycc/modulemixin.c
  numba/tests/test_errorhandling.py
  numba/tests/test_exceptions.py
Labels: 5 - Ready to merge, Effort - long

#8819 Support "static" __getitem__ on Numba types in `@njit` code.
  docs/source/reference/types.rst
  numba/core/typing/builtins.py
  numba/np/arrayobj.py
  numba/tests/test_getitem_on_types.py
Labels: 5 - Ready to merge, Effort - medium

#8842 Fix buildscripts, setup.py, docs for setuptools becoming optional.
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/test.sh
  docs/source/user/installing.rst
  docs/source/user/pycc.rst
  numba/tests/test_pycc.py
  setup.py
Labels: 5 - Ready to merge, Effort - medium

#8848 added lifted loops to glossary term
  docs/source/glossary.rst
Labels: 5 - Ready to merge, Effort - short

#8852 Disable SLP vectorisation due to miscompilations.
  docs/source/reference/envvars.rst
  numba/core/config.py
  numba/tests/test_vectorization.py
Labels: 5 - Ready to merge, Effort - short

#7009 Add writable args
  docs/source/user/vectorize.rst
  numba/core/options.py
  numba/np/ufunc/_ufunc.c
  numba/np/ufunc/decorators.py
  numba/np/ufunc/deviceufunc.py
  numba/np/ufunc/gufunc.py
  numba/np/ufunc/parallel.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/npyufunc/test_update_inplace.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - long

#8294 CUDA: Add trig ufunc support
  docs/source/cuda/cudapysupported.rst
  docs/source/cuda/examples.rst
  numba/core/typing/npydecl.py
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/mathimpl.py
  numba/cuda/simulator/cudadrv/devicearray.py
  numba/cuda/target.py
  numba/cuda/tests/cudapy/test_ufuncs.py
  numba/cuda/tests/doc_examples/test_ufunc.py
  numba/cuda/ufuncs.py
  numba/np/npyimpl.py
  numba/tests/test_ufuncs.py
Labels: highpriority, BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - long

#8634 Add new method is_fp16_supported
  docs/source/cuda-reference/host.rst
  docs/source/cuda-reference/kernel.rst
  numba/cuda/api.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/simulator/api.py
  numba/cuda/tests/cudadrv/test_is_fp16.py
Labels: CUDA, 5 - Ready to merge

#8744 Update CtypesLinker::add_cu error message to include fp16 usage
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_linker.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#8809 Update LLVM versions for 0.57 release
  .readthedocs.yml
  docs/source/user/installing.rst
  numba/__init__.py
Labels: doc, 5 - Ready to merge

#8855 DOC: `pip` into double backticks in installing.rst
  docs/source/user/installing.rst
Labels: 5 - Ready to merge, Effort - short

#8858 Update deprecation notice for objmode fallback RE ``@jit`` use.
  docs/source/reference/deprecation.rst
Labels: 5 - Ready to merge, Effort - short

#8864 Remove obsolete deprecation notices
  docs/source/reference/deprecation.rst
Labels: doc, 5 - Ready to merge, Effort - short

#8866 Revise CUDA deprecation notices
  docs/source/cuda/overview.rst
  docs/source/reference/deprecation.rst
  docs/source/user/installing.rst
  numba/core/config.py
  numba/cuda/api.py
  numba/cuda/compiler.py
  numba/cuda/simulator/api.py
Labels: doc, BuildFarm Passed, CUDA, 5 - Ready to merge

#8334 Add dict(*iterable) constructor
  docs/source/reference/pysupported.rst
  numba/core/typing/dictdecl.py
  numba/tests/test_dictobject.py
  numba/tests/test_dicts.py
  numba/typed/dictimpl.py
  numba/typed/typeddict.py
Labels: 5 - Ready to merge, Effort - long
