Repository numba/numba, pull requests merged in 2023-08, with the labels that each got.

#9105 NumPy 1.25 support (PR #9011) continued
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/gpuci/build.sh
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/source/user/installing.rst
  docs/upcoming_changes/9011.np_support.rst
  numba/core/typing/npdatetime.py
  numba/cpython/numbers.py
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/cuda/tests/cudapy/test_ufuncs.py
  numba/cuda/ufuncs.py
  numba/np/arraymath.py
  numba/np/ufunc_db.py
  numba/tests/npyufunc/test_gufunc.py
  numba/tests/test_array_methods.py
  numba/tests/test_array_reductions.py
  numba/tests/test_fancy_indexing.py
  numba/tests/test_npdatetime.py
  numba/tests/test_ufuncs.py
Labels: highpriority, numpy, 5 - Ready to merge

#9114 update np min to 122
  docs/source/user/5minguide.rst
  docs/upcoming_changes/9093.np_support.rst
  numba/__init__.py
  numba/np/arraymath.py
  numba/np/random/distributions.py
  numba/np/random/generator_core.py
  numba/np/ufunc_db.py
  numba/tests/test_array_reductions.py
  numba/tests/test_np_functions.py
  numba/tests/test_ufuncs.py
Labels: BuildFarm Passed, 5 - Ready to merge

#9112 Fixups for PR#9100
  docs/upcoming_changes/7262.bug_fix.rst
  docs/upcoming_changes/7543.np_support.rst
  docs/upcoming_changes/8462.improvement.rst
  docs/upcoming_changes/8885.bug_fix.rst
  docs/upcoming_changes/8892.new_feature.rst
  docs/upcoming_changes/8906.new_feature.rst
  docs/upcoming_changes/8911.improvement.rst
  docs/upcoming_changes/8916.change.rst
  docs/upcoming_changes/8944.bug_fix.rst
  docs/upcoming_changes/8974.cuda.rst
  docs/upcoming_changes/8988.cuda.rst
  docs/upcoming_changes/8995.np_support.rst
  docs/upcoming_changes/9035.cuda.rst
Labels: 5 - Ready to merge, Effort - short

#9100 Add towncrier news snippets for PRs that are missing them.
  docs/upcoming_changes/7262.bug_fix.rst
  docs/upcoming_changes/7543.np_support.rst
  docs/upcoming_changes/8462.improvement.rst
  docs/upcoming_changes/8736.np_support.rst
  docs/upcoming_changes/8885.bug_fix.rst
  docs/upcoming_changes/8892.new_feature.rst
  docs/upcoming_changes/8906.new_feature.rst
  docs/upcoming_changes/8911.improvement.rst
  docs/upcoming_changes/8916.change.rst
  docs/upcoming_changes/8944.bug_fix.rst
  docs/upcoming_changes/8974.cuda.rst
  docs/upcoming_changes/8988.cuda.rst
  docs/upcoming_changes/8995.np_support.rst
  docs/upcoming_changes/9035.cuda.rst
Labels: doc, abandoned, skip_release_notes

#9094 Add support for a 'max' level to NUMBA_OPT environment variable.
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9094.new_feature.rst
  numba/core/codegen.py
  numba/core/config.py
  numba/tests/test_config.py
Labels: 5 - Ready to merge, Effort - medium

#9083 Removed windows 32 references from code and documentation
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/condarecipe.local/run_test.bat
  docs/source/reference/envvars.rst
  docs/source/reference/numpysupported.rst
  docs/source/user/5minguide.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9083.highlight.rst
  numba/core/config.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge

#7582 Use get_parfor_writes to detect illegal array access that prevents fusion.
  docs/upcoming_changes/7582.bug_fix.rst
  numba/core/ir_utils.py
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: ParallelAccelerator, 5 - Ready to merge

#9111 Fixes ReST syntax error in PR#9099
  docs/upcoming_changes/9099.bug_fix.rst
  numba/cpython/randomimpl.py
  numba/experimental/jitclass/overloads.py
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/linalg.py
  numba/tests/test_extending.py
  numba/tests/test_np_functions.py
  numba/tests/test_random.py
Labels: 5 - Ready to merge

#9072 Fix support for overloading dispatcher with non-compatible first-class functions
  docs/upcoming_changes/9072.bug_fix.rst
  numba/core/dispatcher.py
  numba/core/types/functions.py
  numba/tests/test_function_type.py
Labels: 5 - Ready to merge, Effort - short

#9095 Support dtype keyword in arange_parallel_impl
  docs/upcoming_changes/9095.bug_fix.rst
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#9086 Support NVRTC using ctypes binding
  LICENSES.third-party
  docs/upcoming_changes/9086.cuda.rst
  numba/cuda/api.py
  numba/cuda/cuda_fp16.h
  numba/cuda/cuda_fp16.hpp
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/error.py
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvrtc.py
  numba/cuda/dispatcher.py
  numba/cuda/simulator/cudadrv/error.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_is_fp16.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_math.py
  numba/cuda/tests/cudapy/test_operator.py
  numba/cuda/tests/doc_examples/test_ffi.py
  setup.py
Labels: BuildFarm Passed, CUDA, 5 - Ready to merge

#9127 Fix accidental cffi test deps, refactor cffi skipping
  numba/cuda/tests/cudapy/test_cffi.py
  numba/cuda/tests/doc_examples/test_ffi.py
  numba/tests/support.py
  numba/tests/test_cffi.py
  numba/tests/test_cfunc.py
  numba/tests/test_errorhandling.py
  numba/tests/test_nrt.py
  numba/tests/test_typeof.py
Labels: BuildFarm Passed, 5 - Ready to merge, Effort - short, skip_release_notes

#9120 Update conda-recipe for numba-rvsdg
  buildscripts/condarecipe.local/meta.yaml
  numba/core/rvsdg_frontend/__init__.py
Labels: 5 - Ready to merge, skip_release_notes

#9128 Merge rvsdg_frontend branch to main
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9012.new_feature.rst
  mypy.ini
  numba/core/analysis.py
  numba/core/compiler.py
  numba/core/config.py
  numba/core/rvsdg_frontend/__init__.py
  numba/core/rvsdg_frontend/bcinterp.py
  numba/core/rvsdg_frontend/rvsdg/__init__.py
  numba/core/rvsdg_frontend/rvsdg/bc2rvsdg.py
  numba/core/rvsdg_frontend/rvsdg/regionpasses.py
  numba/core/rvsdg_frontend/rvsdg/regionrenderer.py
  numba/core/untyped_passes.py
  numba/core/utils.py
Labels: 5 - Ready to merge

#9118 Add support for np.resize()
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9118.np_support.rst
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
Labels: numpy, 5 - Ready to merge

#9087 Add trimseq from np.polynomial.polyutils and polyadd, polysub, polymul from np.polynomial.polynomial
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9087.np_support.rst
  numba/np/polynomial.py
  numba/tests/test_polynomial.py
Labels: 5 - Ready to merge, Effort - medium

#9082 Add np.vsplit, np.hsplit, and np.dsplit
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9082.np_support.rst
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Effort - medium

#9117 Fixed towncrier template rendering
  docs/source/release/template.rst
  docs/upcoming_changes/6647.change.rst
  docs/upcoming_changes/7262.bug_fix.rst
  docs/upcoming_changes/7543.np_support.rst
  docs/upcoming_changes/7582.bug_fix.rst
  docs/upcoming_changes/8462.improvement.rst
  docs/upcoming_changes/8792.new_feature.rst
  docs/upcoming_changes/8885.bug_fix.rst
  docs/upcoming_changes/8892.new_feature.rst
  docs/upcoming_changes/8906.new_feature.rst
  docs/upcoming_changes/8911.improvement.rst
  docs/upcoming_changes/8916.change.rst
  docs/upcoming_changes/8944.bug_fix.rst
  docs/upcoming_changes/8974.cuda.rst
  docs/upcoming_changes/8988.cuda.rst
  docs/upcoming_changes/8995.np_support.rst
  docs/upcoming_changes/9007.cuda.rst
  docs/upcoming_changes/9011.np_support.rst
  docs/upcoming_changes/9034.cuda.rst
  docs/upcoming_changes/9035.cuda.rst
  docs/upcoming_changes/9040.cuda.rst
  docs/upcoming_changes/9051.cuda.rst
  docs/upcoming_changes/9068.np_support.rst
  docs/upcoming_changes/9072.bug_fix.rst
  docs/upcoming_changes/9083.highlight.rst
  docs/upcoming_changes/9085.np_support.rst
  docs/upcoming_changes/9088.cuda.rst
  docs/upcoming_changes/9093.np_support.rst
  docs/upcoming_changes/9094.new_feature.rst
  docs/upcoming_changes/9095.bug_fix.rst
  docs/upcoming_changes/9099.bug_fix.rst
  docs/upcoming_changes/README.rst
  docs/upcoming_changes/template.rst
  towncrier.toml
Labels: 5 - Ready to merge, skip_release_notes

#9137 Changelog 0.58
  CHANGE_LOG
Labels: skip_release_notes

#9138 Release Actions 0.58
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  numba/testing/main.py
  setup.py
Labels: 4 - Waiting on CI, skip_release_notes

#9159 Fix uncaught exception in `find_file()`
  numba/misc/findlib.py
  numba/tests/test_findlib.py
Labels: 5 - Ready to merge, skip_release_notes

#9101 Add misc script to find missing towncrier news files
  maint/towncrier_checker.py
Labels: 5 - Ready to merge, skip_release_notes

#9171 Fix the implementation of a special method
  numba/core/controlflow.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9173 Towncrier fixups (Continue #9158 and retarget to main branch)
  docs/source/index.rst
  docs/source/release-notes-overview.rst
  docs/source/release-notes.rst
  docs/source/release/0.58.0-notes.rst
  docs/upcoming_changes/6647.change.rst
  docs/upcoming_changes/7262.bug_fix.rst
  docs/upcoming_changes/7543.np_support.rst
  docs/upcoming_changes/7582.bug_fix.rst
  docs/upcoming_changes/8462.improvement.rst
  docs/upcoming_changes/8792.new_feature.rst
  docs/upcoming_changes/8885.bug_fix.rst
  docs/upcoming_changes/8892.new_feature.rst
  docs/upcoming_changes/8906.new_feature.rst
  docs/upcoming_changes/8911.improvement.rst
  docs/upcoming_changes/8916.change.rst
  docs/upcoming_changes/8944.bug_fix.rst
  docs/upcoming_changes/8974.cuda.rst
  docs/upcoming_changes/8988.cuda.rst
  docs/upcoming_changes/8995.np_support.rst
  docs/upcoming_changes/9007.cuda.rst
  docs/upcoming_changes/9011.np_support.rst
  docs/upcoming_changes/9012.new_feature.rst
  docs/upcoming_changes/9034.cuda.rst
  docs/upcoming_changes/9035.cuda.rst
  docs/upcoming_changes/9040.cuda.rst
  docs/upcoming_changes/9051.cuda.rst
  docs/upcoming_changes/9068.np_support.rst
  docs/upcoming_changes/9072.bug_fix.rst
  docs/upcoming_changes/9074.new_feature.rst
  docs/upcoming_changes/9082.np_support.rst
  docs/upcoming_changes/9083.highlight.rst
  docs/upcoming_changes/9085.np_support.rst
  docs/upcoming_changes/9086.cuda.rst
  docs/upcoming_changes/9087.np_support.rst
  docs/upcoming_changes/9088.cuda.rst
  docs/upcoming_changes/9090.deprecation.rst
  docs/upcoming_changes/9093.np_support.rst
  docs/upcoming_changes/9094.new_feature.rst
  docs/upcoming_changes/9095.bug_fix.rst
  docs/upcoming_changes/9099.bug_fix.rst
  docs/upcoming_changes/9113.np_support.rst
  docs/upcoming_changes/9118.np_support.rst
Labels: 5 - Ready to merge, skip_release_notes
