Repository numba/numba, pull requests merged in 2023-02, with the labels that each got.

#8746 Fix failing test_dispatcher test case
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: CUDA, 5 - Ready to merge

#8752 Flake8 fixes for py311 branch
  .flake8
  numba/core/analysis.py
  numba/core/cgutils.py
  numba/core/event.py
  numba/core/inline_closurecall.py
  numba/core/serialize.py
  numba/core/untyped_passes.py
  numba/cpython/unicode.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_nondet.py
  numba/np/arraymath.py
  numba/np/numpy_support.py
  numba/np/random/random_methods.py
  numba/tests/test_ssa.py
  numba/tests/test_stencils.py
  numba/typed/listobject.py
Labels: 5 - Ready to merge, Effort - short, Python 3.11

#8720 Enable coverage for subprocess testing
  numba/tests/support.py
Labels: 5 - Ready to merge, Effort - short

#8735 Update bot to close PRs waiting on authors for more than 3 months
  .github/workflows/stale.yml
Labels: 5 - Ready to merge, Effort - short

#8748 Suppress known test failures for py3.11
  numba/tests/support.py
  numba/tests/test_operators.py
  numba/tests/test_profiler.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
Labels: 5 - Ready to merge, Python 3.11

#8751 Recycle test runners more aggressively
  numba/testing/main.py
Labels: 5 - Ready to merge, Effort - short

#8760 Bump llvmlite PR in py3.11 branch testing
  buildscripts/incremental/build.sh
Labels: 5 - Ready to merge, Effort - short, Python 3.11

#8387 Add support for compute capability in IR Lowering
  numba/cuda/compiler.py
  numba/cuda/dispatcher.py
  numba/cuda/mathimpl.py
  numba/cuda/testing.py
  numba/cuda/tests/cudapy/test_fastmath.py
  numba/cuda/tests/cudapy/test_mandel.py
Labels: highpriority, CUDA, 5 - Ready to merge

#8766 Stale bot: Use `abandoned - stale` label for closed PRs
  .github/workflows/stale.yml
Labels: 5 - Ready to merge

#8764 CUDA tidy-up: remove some unneeded methods
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_math.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#8775 Revert PR#8751 for buildfarm stability
  numba/testing/main.py
Labels: 5 - Ready to merge, Effort - short

#8180 CUDA: Initial support for Minor Version Compatibility
  buildscripts/gpuci/axis.yaml
  buildscripts/gpuci/build.sh
  docs/source/cuda/index.rst
  docs/source/cuda/minor_version_compatibility.rst
  docs/source/cuda/overview.rst
  docs/source/user/installing.rst
  numba/core/config.py
  numba/cuda/codegen.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_cooperative_groups.py
  numba/cuda/tests/doc_examples/test_cg.py
  numba/cuda/tests/doc_examples/test_laplace.py
  numba/cuda/tests/doc_examples/test_sessionize.py
  numba/misc/numba_sysinfo.py
Labels: highpriority, BuildFarm Passed, CUDA, 5 - Ready to merge, Effort - medium

#8348 Add get_max_threads_per_block method to Dispatcher
  docs/source/cuda-reference/kernel.rst
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudadrv/test_linker.py
  numba/cuda/tests/cudapy/test_dispatcher.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#8732 Add numpy argpartition function support
  docs/source/reference/numpysupported.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: numpy, 5 - Ready to merge

#8765 BLD: remove distutils
  setup.py
Labels: BuildFarm Passed, 5 - Ready to merge

#8780 Improved documentation for Atomic CAS
  numba/cuda/stubs.py
Labels: doc, CUDA, 5 - Ready to merge, Effort - short

#8782 Changed wording of the escape error
  numba/core/ir_utils.py
Labels: doc, 5 - Ready to merge, Effort - short

#8786 Upgrade stale GitHub action
  .github/workflows/stale.yml
Labels: 5 - Ready to merge
