Repository numba/numba, pull requests merged in 2023-11, with the labels that each got.

#9144 Fix error when literal is wrongly propagated in a PHI node
  docs/upcoming_changes/9126.bug_fix.rst
  numba/core/untyped_passes.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge, Effort - short

#9189 Align `searchsorted` behaviour with numpy
  docs/upcoming_changes/9189.bug_fix.rst
  numba/cpython/builtins.py
  numba/np/arraymath.py
  numba/np/arrayobj.py
  numba/np/numpy_support.py
  numba/tests/test_np_functions.py
  numba/tests/test_sort.py
Labels: numpy, 5 - Ready to merge

#9244 Fix Recursion error in parfor lookup
  docs/upcoming_changes/9244.bug_fix.rst
  numba/parfors/parfor.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge

#9245 Fix slow InlineInlineable
  docs/upcoming_changes/9245.performance.rst
  numba/core/ir.py
Labels: 5 - Ready to merge

#9246 Support for Python 3.12
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  docs/upcoming_changes/9246.highlight.rst
  numba/_devicearray.cpp
  numba/_dispatcher.cpp
  numba/_dynfunc.c
  numba/_helperlib.c
  numba/_helpermod.c
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/controlflow.py
  numba/core/interpreter.py
  numba/core/pythonapi.py
  numba/core/registry.py
  numba/core/runtime/_nrt_python.c
  numba/core/untyped_passes.py
  numba/core/utils.py
  numba/cpython/unicode.py
  numba/cuda/tests/cudadrv/test_context_stack.py
  numba/cuda/tests/cudadrv/test_cuda_ndarray.py
  numba/cuda/tests/cudapy/test_debug.py
  numba/cuda/tests/cudapy/test_dispatcher.py
  numba/cuda/tests/cudapy/test_frexp_ldexp.py
  numba/cuda/tests/cudapy/test_intrinsics.py
  numba/cuda/tests/cudapy/test_userexc.py
  numba/experimental/jitclass/_box.c
  numba/mviewbuf.c
  numba/np/ufunc/_internal.c
  numba/tests/doc_examples/test_interval_example.py
  numba/tests/support.py
  numba/tests/test_closure.py
  numba/tests/test_comprehension.py
  numba/tests/test_debug.py
  numba/tests/test_dicts.py
  numba/tests/test_dispatcher.py
  numba/tests/test_exceptions.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_itanium_mangler.py
  numba/tests/test_jitmethod.py
  numba/tests/test_lists.py
  numba/tests/test_looplifting.py
  numba/tests/test_mangling.py
  numba/tests/test_mathlib.py
  numba/tests/test_mixed_tuple_unroller.py
  numba/tests/test_np_functions.py
  numba/tests/test_parfors.py
  numba/tests/test_profiler.py
  numba/tests/test_sets.py
  numba/tests/test_slices.py
  numba/tests/test_try_except.py
  numba/tests/test_withlifting.py
  setup.py
Labels: 4 - Waiting on author, Effort - long, 3.12

#9308 Fix typo in azure ci script
  azure-pipelines.yml
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9302 add missing backtick to example git tag command
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, skip_release_notes

#9301 Release Notes 0.58.1 for main
  docs/source/release-notes-overview.rst
  docs/source/release/0.58.1-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9222.bug_fix.rst
  docs/upcoming_changes/9227.np_support.rst
Labels: 5 - Ready to merge, skip_release_notes

#9292 CUDA: Switch cooperative groups to use overloads
  numba/cuda/cg.py
  numba/cuda/cudadecl.py
  numba/cuda/cudaimpl.py
  numba/cuda/device_init.py
  numba/cuda/stubs.py
  numba/cuda/testing.py
Labels: CUDA, 5 - Ready to merge, Effort - short, skip_release_notes

#9249 add support for checking dtypes equal
  docs/upcoming_changes/9249.np_support.rst
  numba/core/typing/npydecl.py
  numba/np/arrayobj.py
  numba/tests/test_array_attr.py
Labels: 5 - Ready to merge, Effort - short

#9169 Update `np.digitize` handling of np.nan bin edge(s)
  docs/upcoming_changes/9169.bug_fix.rst
  numba/np/arraymath.py
  numba/tests/test_np_functions.py
Labels: numpy, 5 - Ready to merge

#9310 Remove Python 3.8 support.
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/gpuci/axis.yaml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/environment.yml
  docs/source/user/installing.rst
  docs/upcoming_changes/9310.highlight.rst
  numba/__init__.py
  numba/_devicearray.cpp
  numba/_dispatcher.cpp
  numba/_dynfunc.c
  numba/_helperlib.c
  numba/_helpermod.c
  numba/core/analysis.py
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/controlflow.py
  numba/core/event.py
  numba/core/interpreter.py
  numba/core/pythonapi.py
  numba/core/runtime/_nrt_python.c
  numba/core/transforms.py
  numba/core/utils.py
  numba/cpython/unicode.py
  numba/cuda/tests/cudapy/test_debug.py
  numba/experimental/jitclass/_box.c
  numba/mviewbuf.c
  numba/np/ufunc/_internal.c
  numba/tests/support.py
  numba/tests/test_builtins.py
  numba/tests/test_debug.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_parfors.py
  numba/tests/test_pycc.py
  numba/tests/test_tuples.py
  numba/tests/test_withlifting.py
  setup.py
Labels: Effort - medium
