Repository numba/numba, pull requests merged in 2024-12, with the labels that each got.

#9823 Initialize 0.62.0dev : Bump llvmlite to next dev version
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/environment.yml
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge, skip_release_notes

#9837 Replace "hard-errors" with NumbaErrors.
  docs/upcoming_changes/9837.bug_fix.rst
  numba/core/base.py
  numba/core/byteflow.py
  numba/core/types/functions.py
  numba/core/typing/arraydecl.py
  numba/core/typing/bufproto.py
  numba/core/typing/context.py
  numba/core/typing/new_builtins.py
  numba/core/typing/npdatetime.py
  numba/core/typing/npydecl.py
  numba/core/typing/old_builtins.py
  numba/core/typing/typeof.py
  numba/cpython/new_builtins.py
  numba/cpython/randomimpl.py
  numba/cuda/intrinsics.py
  numba/np/arrayobj.py
  numba/np/linalg.py
  numba/np/new_arraymath.py
  numba/np/numpy_support.py
  numba/np/old_arraymath.py
  numba/np/ufunc/dufunc.py
  numba/stencils/stencil.py
  numba/stencils/stencilparfor.py
  numba/tests/test_array_manipulation.py
  numba/tests/test_array_methods.py
  numba/tests/test_numpy_support.py
  numba/tests/test_stencils.py
  numba/typed/dictobject.py
  numba/typed/listobject.py
  numba/typed/typedobjectutils.py
Labels: BuildFarm Passed, 5 - Ready to merge

#9821 Add debug print to debug test_monitoring_multiple_threads failing on …
  numba/tests/test_sys_monitoring.py
Labels: 5 - Ready to merge, skip_release_notes

#9848 Fix #9846. GET_ITER in comprehension changed to NOP.
  docs/upcoming_changes/9848.bug_fix.rst
  numba/core/bytecode.py
Labels: 3 - Ready for Review

#9843 Cherry-picks and Changelog entries for 0.61.0rc2
  docs/source/release/0.61.0-notes.rst
  numba/core/base.py
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/types/functions.py
  numba/core/typing/arraydecl.py
  numba/core/typing/bufproto.py
  numba/core/typing/context.py
  numba/core/typing/new_builtins.py
  numba/core/typing/npdatetime.py
  numba/core/typing/npydecl.py
  numba/core/typing/old_builtins.py
  numba/core/typing/typeof.py
  numba/cpython/new_builtins.py
  numba/cpython/randomimpl.py
  numba/cuda/intrinsics.py
  numba/np/arrayobj.py
  numba/np/linalg.py
  numba/np/new_arraymath.py
  numba/np/numpy_support.py
  numba/np/old_arraymath.py
  numba/np/ufunc/dufunc.py
  numba/stencils/stencil.py
  numba/stencils/stencilparfor.py
  numba/tests/test_array_manipulation.py
  numba/tests/test_array_methods.py
  numba/tests/test_numpy_support.py
  numba/tests/test_stencils.py
  numba/tests/test_sys_monitoring.py
  numba/typed/dictobject.py
  numba/typed/listobject.py
  numba/typed/typedobjectutils.py
Labels: Pending BuildFarm, skip_release_notes
