Repository numba/numba, pull requests merged in 2024-02, with the labels that each got.

#9425 Post release for 0.59.0
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/environment.yml
  docs/source/release/0.59.0-notes.rst
  docs/source/user/installing.rst
  numba/__init__.py
  setup.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9364 Release notes fixes for appropriate Towncrier header underlines
  docs/source/release/0.58.0-notes.rst
  docs/source/release/0.58.1-notes.rst
  docs/upcoming_changes/9048.bug_fix.rst
  docs/upcoming_changes/9089.bug_fix.rst
  docs/upcoming_changes/9123.new_feature.rst
  docs/upcoming_changes/9126.np_support.rst
  docs/upcoming_changes/9140.np_support.rst
  docs/upcoming_changes/9141.np_support.rst
  docs/upcoming_changes/9144.bug_fix.rst
  docs/upcoming_changes/9154.np_support.rst
  docs/upcoming_changes/9169.bug_fix.rst
  docs/upcoming_changes/9189.bug_fix.rst
  docs/upcoming_changes/9235.cuda.rst
  docs/upcoming_changes/9244.bug_fix.rst
  docs/upcoming_changes/9245.performance.rst
  docs/upcoming_changes/9246.highlight.rst
  docs/upcoming_changes/9249.np_support.rst
  docs/upcoming_changes/9310.highlight.rst
  docs/upcoming_changes/9315.change.rst
  docs/upcoming_changes/9335.infrastructure.rst
  docs/upcoming_changes/README.rst
  docs/upcoming_changes/template.rst
  maint/towncrier_rst_validator.py
Labels: 5 - Ready to merge, skip_release_notes

#9378 Add `float(<string literal>)` ctor
  docs/upcoming_changes/9378.new_feature.rst
  numba/core/typing/builtins.py
  numba/cpython/builtins.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge, Effort - short

#9394 fix `TypeError: '_DeviceContextManager' object is not callable`
  docs/source/cuda-reference/host.rst
  docs/upcoming_changes/9394.doc.rst
Labels: 5 - Ready to merge, Effort - short

#9450 Fix gpuci versions
  buildscripts/gpuci/build.sh
  numba/cuda/cudadrv/nvvm.py
Labels: CUDA, 5 - Ready to merge, skip_release_notes

#9456 Update release checklist
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: doc, 5 - Ready to merge, Effort - short, skip_release_notes

#9448 Fix `np.searchsorted` regression
  docs/upcoming_changes/9448.performance.rst
  numba/np/arraymath.py
Labels: 5 - Ready to merge, performance - run time

#9455 Support datetime types in `isinstance()`
  docs/upcoming_changes/9455.improvement.rst
  numba/cpython/builtins.py
  numba/tests/test_npdatetime.py
Labels: enhancement, 5 - Ready to merge, Effort - short

#9468 adding git-copy.py script
  maint/git-copy.py
Labels: 5 - Ready to merge, skip_release_notes
