Repository numba/numba, pull requests merged in 2024-08, with the labels that each got.

#9508 Add compile-time coverage for compiled code
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  docs/source/user/code_coverage.rst
  docs/source/user/index.rst
  docs/upcoming_changes/9508.new_feature.rst
  numba/core/lowering.py
  numba/misc/coverage_support.py
  numba/tests/test_misc_coverage_support.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#9670 Move creation of mpm to optimize_final_module
  docs/upcoming_changes/9670.improvement.rst
  numba/core/codegen.py
  numba/tests/test_debuginfo.py
  numba/tests/test_optimisation_pipelines.py
Labels: 5 - Ready to merge

#9683 Fix C99 `I` not working with NumPy 2.0.1
  numba/_helperlib.c
Labels: 5 - Ready to merge, skip_release_notes

#9686 Type system implementation #1: Added initial implementation for a new type system using redundancies.
  docs/upcoming_changes/9662.highlight.rst
  numba/core/datamodel/new_models.py
  numba/core/ir_utils.py
  numba/core/itanium_mangler.py
  numba/core/new_boxing.py
  numba/core/pythonapi.py
  numba/core/typeconv/rules.py
  numba/core/types/__init__.py
  numba/core/types/new_scalars/__init__.py
  numba/core/types/new_scalars/machine_types.py
  numba/core/types/new_scalars/numpy_types.py
  numba/core/types/new_scalars/python_types.py
  numba/core/typing/bufproto.py
  numba/core/typing/new_builtins.py
  numba/core/typing/new_cmathdecl.py
  numba/core/typing/new_mathdecl.py
  numba/core/typing/typeof.py
  numba/cpython/listobj.py
  numba/cpython/new_builtins.py
  numba/cpython/new_hashing.py
  numba/cpython/new_mathimpl.py
  numba/cpython/new_numbers.py
  numba/cpython/new_tupleobj.py
  numba/cpython/rangeobj.py
  numba/cpython/unicode.py
  numba/cuda/simulator/vector_types.py
  numba/misc/quicksort.py
  numba/np/linalg.py
  numba/np/numpy_support.py
  numba/np/random/new_distributions.py
  numba/np/random/new_random_methods.py
  numba/tests/test_new_type_system.py
  numba/tests/test_np_randomgen.py
  numba/typed/listobject.py
Labels: BuildFarm Passed, 5 - Ready to merge, skip_release_notes

#9701 update flake8 version in pre-commit config
  .pre-commit-config.yaml
Labels: 5 - Ready to merge, skip_release_notes

#9691 Fix #9678. parfor issue with build_map
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, skip_release_notes

#9709 activate compilers for linux-aarch64
  buildscripts/condarecipe.local/conda_build_config.yaml
  buildscripts/condarecipe.local/meta.yaml
Labels: BuildFarm Passed, 5 - Ready to merge, skip_release_notes

#9705 Fix sum_expand return_type missing cast to integer for bool arrays
  docs/upcoming_changes/9705.bug_fix.rst
  numba/core/typing/arraydecl.py
  numba/tests/test_array_methods.py
  numba/tests/test_np_functions.py
Labels: 3 - Ready for Review, 5 - Ready to merge
