Repository numba/numba, pull requests merged in 2024-10, with the labels that each got.

#9726 Remove Python 3.9 support
  .github/workflows/towncrier.yml
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  docs/environment.yml
  docs/source/user/installing.rst
  docs/upcoming_changes/9726.highlight.rst
  numba/__init__.py
  numba/_devicearray.cpp
  numba/_dispatcher.cpp
  numba/_dynfunc.c
  numba/_helperlib.c
  numba/_helpermod.c
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/controlflow.py
  numba/core/entrypoints.py
  numba/core/interpreter.py
  numba/core/pythonapi.py
  numba/core/runtime/_nrt_python.c
  numba/cpython/new_hashing.py
  numba/cpython/old_hashing.py
  numba/cpython/unicode.py
  numba/cuda/tests/cudapy/test_debug.py
  numba/experimental/jitclass/_box.c
  numba/mviewbuf.c
  numba/np/ufunc/_internal.c
  numba/tests/test_analysis.py
  numba/tests/test_debug.py
  numba/tests/test_entrypoints.py
  numba/tests/test_flow_control.py
  numba/tests/test_hashing.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_operators.py
  numba/tests/test_parfors.py
  numba/tests/test_try_except.py
  numba/tests/test_tuples.py
  setup.py
Labels: 5 - Ready to merge

#9711 Add dead-branch-prune pass after SSA pass
  docs/upcoming_changes/9711.improvement.rst
  numba/core/compiler.py
  numba/tests/test_remove_dead.py
Labels: 5 - Ready to merge, Effort - short

#9715 Replace uses of `pprint.pformat` for `_lazy_pformat` in logging
  numba/core/byteflow.py
  numba/core/compiler_machinery.py
  numba/core/event.py
  numba/core/ssa.py
  numba/core/utils.py
  numba/tests/test_event.py
Labels: 5 - Ready to merge, skip_release_notes

#9743 Fixed GHA versions in towncrier script
  .github/workflows/towncrier.yml
  docs/upcoming_changes/9743.infrastructure.rst
Labels: 5 - Ready to merge, Effort - short

#9746 Move Azure to use macos-13
  azure-pipelines.yml
Labels: 5 - Ready to merge, skip_release_notes

#9739 Update the minimum supported NumPy to 1.24
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/meta.yaml
  docs/source/user/5minguide.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9739.highlight.rst
  numba/__init__.py
  numba/np/arrayobj.py
  numba/np/new_arraymath.py
  numba/np/old_arraymath.py
  numba/tests/test_array_methods.py
  numba/tests/test_comprehension.py
  numba/tests/test_np_functions.py
  setup.py
Labels: 5 - Ready to merge

#9119 `memcpy` static buffer content into newly allocated buffer
  docs/upcoming_changes/9119.bug_fix.rst
  numba/_typeof.cpp
  numba/tests/test_typeof.py
Labels: 5 - Ready to merge

#9741 Add Support for NumPy 2.1
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  docs/upcoming_changes/9741.highlight.rst
  numba/core/typing/arraydecl.py
  numba/cpython/randomimpl.py
  numba/np/arrayobj.py
  numba/np/math/numbers.py
  numba/np/npyfuncs.py
  numba/np/random/_constants.py
  numba/np/random/old_distributions.py
  numba/np/ufunc_db.py
  numba/tests/test_array_methods.py
  numba/tests/test_ufuncs.py
Labels: 5 - Ready to merge

#9747 Fix two bugs in Generator.binomial().
  docs/upcoming_changes/9747.bug_fix.rst
  numba/np/random/old_distributions.py
  numba/tests/test_np_randomgen.py
Labels: 5 - Ready to merge

#9756 Fix PyRef leaks in unboxing of np.random.Generator
  docs/upcoming_changes/9756.bug_fix.rst
  numba/core/old_boxing.py
Labels: 5 - Ready to merge

#9757 Fix some memory leaks/poor memory behaviour
  docs/upcoming_changes/9757.bug_fix.rst
  numba/core/dispatcher.py
Labels: 5 - Ready to merge

#9758 Fix miscompile in branch pruning of SSA form IR.
  docs/upcoming_changes/9758.bug_fix.rst
  numba/core/analysis.py
  numba/tests/test_remove_dead.py
Labels: 5 - Ready to merge

#9738 Revert RVSDG frontend.
  azure-pipelines.yml
  buildscripts/condarecipe.local/meta.yaml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/incremental/test.sh
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9738.change.rst
  mypy.ini
  numba/core/compiler.py
  numba/core/config.py
  numba/core/rvsdg_frontend/__init__.py
  numba/core/rvsdg_frontend/bcinterp.py
  numba/core/rvsdg_frontend/rvsdg/__init__.py
  numba/core/rvsdg_frontend/rvsdg/bc2rvsdg.py
  numba/core/rvsdg_frontend/rvsdg/regionpasses.py
  numba/core/rvsdg_frontend/rvsdg/regionrenderer.py
  numba/core/untyped_passes.py
Labels: 5 - Ready to merge

#9397 Reorder block traversal order for correct hoisting.
  docs/upcoming_changes/9397.bug_fix.rst
  numba/core/types/abstract.py
  numba/core/types/containers.py
  numba/parfors/parfor_lowering.py
Labels: ParallelAccelerator, 5 - Ready to merge

#9693 Fix #9677. Fixed list repr in ipython environments
  docs/upcoming_changes/9693.improvement.rst
  numba/tests/test_typedlist.py
  numba/typed/typedlist.py
Labels: 5 - Ready to merge

#9718 Replace find_topo_order with an iterative implementation
  docs/upcoming_changes/9718.improvement.rst
  numba/core/ir_utils.py
Labels: 5 - Ready to merge, skip_release_notes

#9763 Update docs regarding power8 support.
  docs/source/developer/contributing.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9763.change.rst
Labels: 5 - Ready to merge

#9773 Remove old-style captured errors for 0.61
  docs/source/extending/high-level.rst
  docs/source/reference/deprecation.rst
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9773.deprecation.rst
  numba/core/compiler.py
  numba/core/compiler_machinery.py
  numba/core/config.py
  numba/core/errors.py
  numba/core/typeinfer.py
  numba/core/types/functions.py
  numba/core/utils.py
  numba/tests/test_config.py
  numba/tests/test_errorhandling.py
Labels: BuildFarm Passed, 5 - Ready to merge
