Repository numba/numba, pull requests merged in 2024-09, with the labels that each got.

#9727 Revert Junit XML PR that may be causing buildfarm issue related to multiprocessing.Pool error
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/test.sh
  docs/source/developer/contributing.rst
  docs/source/developer/index.rst
  docs/source/developer/testsuite.rst
  numba/testing/main.py
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge, skip_release_notes

#9719 add supported np.trapezoid
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9719.np_support.rst
  numba/np/new_arraymath.py
  numba/np/old_arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Effort - short

#9630 Allow numba functions within zip files to be cached
  docs/upcoming_changes/9630.improvement.rst
  numba/core/caching.py
  numba/tests/test_caching.py
Labels: 5 - Ready to merge, caching

#9338 Add np.in1d, np.isin, np.setxor1d, np.setdiff1d, extend np.intersect1d.
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9338.np_support.rst
  numba/np/new_arraymath.py
  numba/np/old_arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge, Effort - medium
