Repository numba/numba, pull requests merged in 2024-03, with the labels that each got.

#9445 Fix #9427 np.searchsorted on datetime64
  docs/upcoming_changes/9445.bug_fix.rst
  numba/np/arraymath.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge

#9437 Remove dependencies between Numba's Cpython and NumPy module
  .flake8
  numba/core/inline_closurecall.py
  numba/cpython/randomimpl.py
  numba/cpython/rangeobj.py
  numba/np/math/__init__.py
  numba/np/math/cmathimpl.py
  numba/np/math/mathimpl.py
  numba/np/math/numbers.py
  numba/np/npyfuncs.py
  numba/np/npyimpl.py
  numba/np/ufunc_db.py
  numba/tests/test_range.py
  numba/tests/test_unicode.py
Labels: 5 - Ready to merge, skip_release_notes

#9436 Add timing and junit xml output to testsuite
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/test.sh
  docs/source/developer/contributing.rst
  docs/source/developer/index.rst
  docs/source/developer/testsuite.rst
  numba/testing/main.py
  numba/tests/test_runtests.py
Labels: 5 - Ready to merge, skip_release_notes

#9459 Support pep695 type param syntax
  docs/upcoming_changes/9459.bug_fix.rst
  numba/core/ir.py
  numba/tests/test_exceptions.py
Labels: 5 - Ready to merge, Effort - short, 3.12

#9491 Fix non-deterministic bug caused by unstableness in SSA
  numba/core/ssa.py
  numba/core/utils.py
  numba/tests/parfor_iss9490_usecase.py
  numba/tests/support.py
  numba/tests/test_parfors.py
Labels: highpriority, 5 - Ready to merge, skip_release_notes

#9416 Add math.log2 support
  docs/source/reference/pysupported.rst
  docs/upcoming_changes/9416.new_feature.rst
  numba/core/typing/mathdecl.py
  numba/cpython/mathimpl.py
  numba/tests/test_mathlib.py
Labels: 5 - Ready to merge, Effort - short

#9480 Patches for 0.59.1
  buildscripts/azure/azure-windows.yml
  buildscripts/gpuci/build.sh
  docs/source/release/0.59.1-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9048.bug_fix.rst
  docs/upcoming_changes/9049.bug_fix.rst
  docs/upcoming_changes/9089.bug_fix.rst
  docs/upcoming_changes/9123.new_feature.rst
  docs/upcoming_changes/9126.np_support.rst
  docs/upcoming_changes/9140.np_support.rst
  docs/upcoming_changes/9141.np_support.rst
  docs/upcoming_changes/9144.bug_fix.rst
  docs/upcoming_changes/9154.np_support.rst
  docs/upcoming_changes/9169.bug_fix.rst
  docs/upcoming_changes/9189.bug_fix.rst
  docs/upcoming_changes/9223.cuda.rst
  docs/upcoming_changes/9235.cuda.rst
  docs/upcoming_changes/9242.bug_fix.rst
  docs/upcoming_changes/9244.bug_fix.rst
  docs/upcoming_changes/9245.performance.rst
  docs/upcoming_changes/9246.highlight.rst
  docs/upcoming_changes/9249.np_support.rst
  docs/upcoming_changes/9267.cuda.rst
  docs/upcoming_changes/9279.cuda.rst
  docs/upcoming_changes/9296.bug_fix.rst
  docs/upcoming_changes/9309.change.rst
  docs/upcoming_changes/9310.highlight.rst
  docs/upcoming_changes/9315.change.rst
  docs/upcoming_changes/9330.change.rst
  docs/upcoming_changes/9334.bug_fix.rst
  docs/upcoming_changes/9335.infrastructure.rst
  docs/upcoming_changes/9336.improvement.rst
  docs/upcoming_changes/9341.new_feature.rst
  docs/upcoming_changes/9346.deprecation.rst
  docs/upcoming_changes/9347.improvement.rst
  docs/upcoming_changes/9352.expired.rst
  docs/upcoming_changes/9353.expired.rst
  numba/core/ir.py
  numba/core/ssa.py
  numba/core/utils.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/dispatcher.py
  numba/cuda/tests/cudapy/test_caching.py
  numba/np/arraymath.py
  numba/tests/parfor_iss9490_usecase.py
  numba/tests/support.py
  numba/tests/test_exceptions.py
  numba/tests/test_npdatetime.py
  numba/tests/test_parfors.py
  numba/tests/test_unicode.py
Labels: Pending BuildFarm, 5 - Ready to merge, skip_release_notes

#9487 Add CUDA 12 conda installation docs
  buildscripts/condarecipe.local/meta.yaml
  docs/source/cuda/minor_version_compatibility.rst
  docs/source/cuda/overview.rst
  docs/source/reference/envvars.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9487.doc.rst
  numba/cuda/cudadrv/libs.py
  numba/cuda/cudadrv/nvvm.py
Labels: doc, CUDA, 5 - Ready to merge

#9502 Post release task for 0.59.1
  docs/source/release/0.59.1-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9048.bug_fix.rst
  docs/upcoming_changes/9049.bug_fix.rst
  docs/upcoming_changes/9089.bug_fix.rst
  docs/upcoming_changes/9123.new_feature.rst
  docs/upcoming_changes/9126.np_support.rst
  docs/upcoming_changes/9140.np_support.rst
  docs/upcoming_changes/9141.np_support.rst
  docs/upcoming_changes/9144.bug_fix.rst
  docs/upcoming_changes/9154.np_support.rst
  docs/upcoming_changes/9169.bug_fix.rst
  docs/upcoming_changes/9189.bug_fix.rst
  docs/upcoming_changes/9223.cuda.rst
  docs/upcoming_changes/9235.cuda.rst
  docs/upcoming_changes/9242.bug_fix.rst
  docs/upcoming_changes/9244.bug_fix.rst
  docs/upcoming_changes/9245.performance.rst
  docs/upcoming_changes/9246.highlight.rst
  docs/upcoming_changes/9249.np_support.rst
  docs/upcoming_changes/9267.cuda.rst
  docs/upcoming_changes/9279.cuda.rst
  docs/upcoming_changes/9296.bug_fix.rst
  docs/upcoming_changes/9309.change.rst
  docs/upcoming_changes/9310.highlight.rst
  docs/upcoming_changes/9315.change.rst
  docs/upcoming_changes/9330.change.rst
  docs/upcoming_changes/9334.bug_fix.rst
  docs/upcoming_changes/9335.infrastructure.rst
  docs/upcoming_changes/9336.improvement.rst
  docs/upcoming_changes/9341.new_feature.rst
  docs/upcoming_changes/9346.deprecation.rst
  docs/upcoming_changes/9347.improvement.rst
  docs/upcoming_changes/9352.expired.rst
  docs/upcoming_changes/9353.expired.rst
  docs/upcoming_changes/9445.bug_fix.rst
  docs/upcoming_changes/9447.cuda.rst
  docs/upcoming_changes/9448.performance.rst
  docs/upcoming_changes/9459.bug_fix.rst
  maint/towncrier_checker.py
  numba/tests/support.py
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, skip_release_notes

#9239 ufunc.at
  docs/upcoming_changes/9239.new_feature.rst
  numba/np/ufunc/dufunc.py
  numba/tests/npyufunc/test_dufunc.py
Labels: 5 - Ready to merge, Effort - long
