Repository numba/numba, pull requests merged in 2024-04, with the labels that each got.

#8984 Support @gufunc inside @jit
  docs/source/user/vectorize.rst
  docs/upcoming_changes/8984.new_feature.rst
  numba/core/typing/npydecl.py
  numba/cuda/tests/cudapy/test_gufunc.py
  numba/np/npyimpl.py
  numba/np/ufunc/dufunc.py
  numba/np/ufunc/gufunc.py
  numba/np/ufunc/ufunc_base.py
  numba/tests/doc_examples/test_examples.py
  numba/tests/npyufunc/test_gufunc.py
Labels: numpy, 5 - Ready to merge

#9417 Add np.log* bindings for CUDA
  docs/source/cuda/cudapysupported.rst
  docs/upcoming_changes/9417.cuda.rst
  numba/cuda/cudadecl.py
  numba/cuda/tests/cudapy/test_ufuncs.py
  numba/cuda/ufuncs.py
Labels: CUDA, 5 - Ready to merge, Effort - short

#9488 Update overview.rst
  docs/source/cuda/overview.rst
Labels: doc, CUDA, 5 - Ready to merge, Effort - short, skip_release_notes

#9504 added np.size() overload and added tests
  docs/upcoming_changes/9504.np_support.rst
  numba/np/arrayobj.py
  numba/tests/test_array_manipulation.py
  numba/tests/test_record_dtype.py
Labels: numpy, 5 - Ready to merge

#9274 CUDA: Add support for compilation to LTO-IR
  docs/source/cuda-reference/host.rst
  docs/source/cuda/cuda_compilation.rst
  docs/upcoming_changes/9274.cuda.rst
  numba/cuda/__init__.py
  numba/cuda/codegen.py
  numba/cuda/compiler.py
  numba/cuda/cudadrv/driver.py
  numba/cuda/cudadrv/nvvm.py
  numba/cuda/simulator/compiler.py
  numba/cuda/simulator/cudadrv/devices.py
  numba/cuda/simulator/cudadrv/driver.py
  numba/cuda/simulator/cudadrv/nvvm.py
  numba/cuda/testing.py
  numba/cuda/tests/cudadrv/test_inline_ptx.py
  numba/cuda/tests/cudadrv/test_nvvm_driver.py
  numba/cuda/tests/cudapy/test_compiler.py
  numba/cuda/tests/cudapy/test_const_string.py
  numba/cuda/tests/cudapy/test_debuginfo.py
  numba/cuda/tests/cudapy/test_exception.py
  numba/cuda/tests/cudapy/test_fastmath.py
  numba/cuda/tests/cudapy/test_userexc.py
  numba/cuda/tests/nocuda/test_nvvm.py
Labels: CUDA, 5 - Ready to merge, Effort - medium

#9531 Module pass manager: Don't add passes for unsupported LLVM versions
  numba/core/codegen.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9532 Fix hoisting bug to exclude variables used in containers or calls.
  docs/upcoming_changes/9532.bug_fix.rst
  numba/parfors/parfor_lowering.py
  numba/tests/test_parfors.py
Labels: ParallelAccelerator, 5 - Ready to merge

#9539 Revert PR #6870 `numba.core.retarget`
  docs/source/developer/repomap.rst
  docs/upcoming_changes/9539.expired.rst
  numba/_dispatcher.cpp
  numba/core/compiler.py
  numba/core/cpu.py
  numba/core/decorators.py
  numba/core/dispatcher.py
  numba/core/options.py
  numba/core/retarget.py
  numba/core/types/functions.py
  numba/np/ufunc/ufuncbuilder.py
  numba/tests/parfors_max_label_error.py
  numba/tests/test_compiler_flags.py
  numba/tests/test_parfors.py
  numba/tests/test_retargeting.py
Labels: 5 - Ready to merge, Effort - short

#9482 Add support for `sys.monitoring` events.
  docs/source/developer/index.rst
  docs/source/developer/sys_monitoring.rst
  docs/upcoming_changes/9482.improvement.rst
  numba/_dispatcher.cpp
  numba/tests/support.py
  numba/tests/test_profiler.py
  numba/tests/test_sys_monitoring.py
Labels: Pending BuildFarm, 5 - Ready to merge, Effort - long

#9454 Don't attempt to register overloads that aren't for this target in `BaseContext` and related fixes
  numba/core/errors.py
  numba/core/extending.py
  numba/core/target_extension.py
  numba/core/typing/context.py
  numba/core/typing/templates.py
  numba/cuda/tests/cudapy/test_overload.py
  numba/tests/test_target_extension.py
Labels: 5 - Ready to merge, skip_release_notes

#9549 Make new_style the default error capturing mode
  buildscripts/azure/azure-windows.yml
  buildscripts/condarecipe.local/run_test.bat
  buildscripts/condarecipe.local/run_test.sh
  buildscripts/incremental/test.sh
  docs/upcoming_changes/9549.deprecation.rst
  numba/core/config.py
  numba/core/utils.py
  numba/tests/test_config.py
  numba/tests/test_errorhandling.py
Labels: 5 - Ready to merge, Effort - medium
