Repository numba/numba, pull requests merged in 2024-11, with the labels that each got.

#9774 Test on gpuCI with supported NumPy and Python versions
  buildscripts/gpuci/build.sh
Labels: CUDA, 5 - Ready to merge, test suite, skip_release_notes

#9780 Default to turn off `sys.monitoring`
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9780.change.rst
  numba/_dispatcher.cpp
  numba/core/config.py
  numba/core/dispatcher.py
  numba/tests/test_profiler.py
  numba/tests/test_sys_monitoring.py
Labels: 5 - Ready to merge

#9761 Add CI for py313
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
Labels: 5 - Ready to merge, skip_release_notes

#9583 Remove `resolve_argument_type()` from typing context
  numba/core/dispatcher.py
  numba/core/typing/context.py
  numba/cuda/dispatcher.py
Labels: CUDA, 5 - Ready to merge, Effort - short, skip_release_notes

#9772 Emit warnings when missing authors are dectected in `gitlog2changelog`
  maint/gitlog2changelog.py
Labels: 5 - Ready to merge, skip_release_notes

#9768 Deprecation of built-in CUDA target
  docs/source/conf.py
  docs/source/cuda-reference/host.rst
  docs/source/cuda-reference/index.rst
  docs/source/cuda-reference/kernel.rst
  docs/source/cuda-reference/libdevice.rst
  docs/source/cuda-reference/memory.rst
  docs/source/cuda-reference/types.rst
  docs/source/cuda/bindings.rst
  docs/source/cuda/caching.rst
  docs/source/cuda/cooperative_groups.rst
  docs/source/cuda/cuda_array_interface.rst
  docs/source/cuda/cuda_compilation.rst
  docs/source/cuda/cuda_ffi.rst
  docs/source/cuda/cudapysupported.rst
  docs/source/cuda/device-functions.rst
  docs/source/cuda/device-management.rst
  docs/source/cuda/examples.rst
  docs/source/cuda/external-memory.rst
  docs/source/cuda/faq.rst
  docs/source/cuda/fastmath.rst
  docs/source/cuda/index.rst
  docs/source/cuda/intrinsics.rst
  docs/source/cuda/ipc.rst
  docs/source/cuda/kernels.rst
  docs/source/cuda/memory.rst
  docs/source/cuda/minor_version_compatibility.rst
  docs/source/cuda/overview.rst
  docs/source/cuda/random.rst
  docs/source/cuda/reduction.rst
  docs/source/cuda/simulator.rst
  docs/source/cuda/ufunc.rst
  docs/source/reference/deprecation.rst
  docs/upcoming_changes/9768.deprecation.rst
Labels: 5 - Ready to merge

#9799 Fix regression in exception handling against 0.60.
  docs/upcoming_changes/9799.bug_fix.rst
  numba/core/typeinfer.py
  numba/core/typing/templates.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge

#9800 Added changelog for `0.61.0` and updated release versioning table
  docs/source/release/0.61.0-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9077.improvement.rst
  docs/upcoming_changes/9119.bug_fix.rst
  docs/upcoming_changes/9295.improvement.rst
  docs/upcoming_changes/9297.improvement.rst
  docs/upcoming_changes/9338.np_support.rst
  docs/upcoming_changes/9397.bug_fix.rst
  docs/upcoming_changes/9495.new_feature.rst
  docs/upcoming_changes/9508.new_feature.rst
  docs/upcoming_changes/9586.bug_fix.rst
  docs/upcoming_changes/9630.improvement.rst
  docs/upcoming_changes/9636.bug_fix.rst
  docs/upcoming_changes/9662.highlight.rst
  docs/upcoming_changes/9670.improvement.rst
  docs/upcoming_changes/9682.highlight.rst
  docs/upcoming_changes/9693.improvement.rst
  docs/upcoming_changes/9705.bug_fix.rst
  docs/upcoming_changes/9711.improvement.rst
  docs/upcoming_changes/9718.improvement.rst
  docs/upcoming_changes/9719.np_support.rst
  docs/upcoming_changes/9726.highlight.rst
  docs/upcoming_changes/9738.change.rst
  docs/upcoming_changes/9739.highlight.rst
  docs/upcoming_changes/9741.highlight.rst
  docs/upcoming_changes/9743.infrastructure.rst
  docs/upcoming_changes/9747.bug_fix.rst
  docs/upcoming_changes/9755.bug_fix.rst
  docs/upcoming_changes/9756.bug_fix.rst
  docs/upcoming_changes/9757.bug_fix.rst
  docs/upcoming_changes/9758.bug_fix.rst
  docs/upcoming_changes/9763.change.rst
  docs/upcoming_changes/9768.deprecation.rst
  docs/upcoming_changes/9773.deprecation.rst
  docs/upcoming_changes/9780.change.rst
  docs/upcoming_changes/9799.bug_fix.rst
Labels: skip_release_notes

#9804 Release branch pins for 0.61
  buildscripts/condarecipe.local/meta.yaml
  numba/__init__.py
  numba/testing/main.py
  setup.py
Labels: 3 - Ready for Review, skip_release_notes
