Repository numba/numba, pull requests merged in 2025-09, with the labels that each got.

#10214 skip test_prange_fastmath_check_works
  numba/tests/test_parfors.py
Labels: 5 - Ready to merge, skip_release_notes

#10195 Make `types.ListType` evaluable
  docs/upcoming_changes/10195.bug_fix.rst
  numba/core/types/containers.py
Labels: 5 - Ready to merge

#10212 Revert 9973
  docs/source/release/0.62.0-notes.rst
  numba/core/typing/builtins.py
  numba/tests/test_ir.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_range.py
Labels: 3 - Ready for Review, skip_release_notes

#10216 Update conda_build_config.yaml to pin osx compiler version to 19
  buildscripts/condarecipe.local/conda_build_config.yaml
  buildscripts/condarecipe.local/meta.yaml
Labels: 3 - Ready for Review, skip_release_notes

#10232 Update release date and change-log for 0.62.0
  docs/source/release/0.62.0-notes.rst
  docs/source/user/installing.rst
Labels: 3 - Ready for Review, skip_release_notes

#10247 Release notes for 0.62
  docs/source/release/0.62.1-notes.rst
  docs/source/user/installing.rst
Labels: 4 - Waiting on reviewer, skip_release_notes

#10150 Python 3.14
  docs/upcoming_changes/10150.improvement.rst
  numba/_devicearray.cpp
  numba/_dispatcher.cpp
  numba/_dynfunc.c
  numba/_hashtable.cpp
  numba/_helperlib.c
  numba/_pymodule.h
  numba/_typeof.cpp
  numba/core/bytecode.py
  numba/core/byteflow.py
  numba/core/controlflow.py
  numba/core/interpreter.py
  numba/core/runtime/_nrt_python.c
  numba/core/typing/asnumbatype.py
  numba/cpython/unicode.py
  numba/experimental/jitclass/_box.c
  numba/experimental/jitclass/base.py
  numba/experimental/jitclass/boxing.py
  numba/mviewbuf.c
  numba/np/ufunc/_internal.c
  numba/tests/support.py
  numba/tests/test_analysis.py
  numba/tests/test_complex.py
  numba/tests/test_debug.py
  numba/tests/test_dyn_array.py
  numba/tests/test_exceptions.py
  numba/tests/test_extended_arg.py
  numba/tests/test_extending.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_object_mode.py
  numba/tests/test_operators.py
  numba/tests/test_parfors.py
  numba/tests/test_sys_monitoring.py
  numba/tests/test_try_except.py
  numba/tests/test_unicode.py
  numba/tests/test_withlifting.py
  setup.py
Labels: 5 - Ready to merge

#10248 GHA/ fix win-64 lib lookup paths
  .github/workflows/numba_linux-64_wheel_builder.yml
  .github/workflows/numba_linux-aarch64_wheel_builder.yml
  .github/workflows/numba_osx-arm64_wheel_builder.yml
  .github/workflows/numba_win-64_wheel_builder.yml
  setup.py
Labels: 5 - Ready to merge, skip_release_notes

#10252 update trove classifier for 3.14
  setup.py
Labels: 3 - Ready for Review, skip_release_notes
