Repository numba/numba, pull requests merged in 2025-06, with the labels that each got.

#10103 Pin python 3.13 to 3.13.3 in CI
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
Labels: 5 - Ready to merge, skip_release_notes

#10081 Resolve NumPy `DeprecationWarning` in `constant_record`
  docs/upcoming_changes/10081.bug_fix.rst
  numba/np/arrayobj.py
Labels: 5 - Ready to merge

#10072 Docs: Fix jit decorator parameter name from 'signature' to 'signature_or_function'
  docs/source/reference/jit-compilation.rst
Labels: 5 - Ready to merge, skip_release_notes

#10044 Document and test `as_numba_type`'s role in instance checks
  docs/source/extending/interval-example.rst
  docs/source/reference/types.rst
  docs/upcoming_changes/10044.improvement.rst
  numba/core/typing/asnumbatype.py
  numba/tests/test_asnumbatype.py
  numba/tests/test_builtins.py
Labels: 5 - Ready to merge

#10106 Fix list-comprehension for python 3.13.4
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  docs/upcoming_changes/10106.change.rst
  numba/core/bytecode.py
Labels: 5 - Ready to merge, Python 3.13

#10102 Fix error for unsupported `axis` kwarg in `average`
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/10102.bug_fix.rst
  numba/np/old_arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#10097 Add support for `posinf` and `neginf` in `nan_to_num`
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/10097.np_support.rst
  numba/np/arrayobj.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#10050 Fixed invert in overload and added testcase.
  docs/source/user/jitclass.rst
  docs/upcoming_changes/10050.bug_fix.rst
  numba/experimental/jitclass/boxing.py
  numba/experimental/jitclass/overloads.py
  numba/tests/test_jitclasses.py
Labels: 5 - Ready to merge

#9805 Handle empty arrays in np.median implementation and add datetime check
  docs/upcoming_changes/9805.bug_fix.rst
  numba/np/old_arraymath.py
  numba/tests/test_array_reductions.py
Labels: 5 - Ready to merge

#10107 gha/seperate wheel build and test matrices
  .github/workflows/numba_linux-64_wheel_builder.yml
  .github/workflows/numba_linux-arm64_wheel_builder.yml
  .github/workflows/numba_osx-64_wheel_builder.yml
  .github/workflows/numba_osx-arm64_wheel_builder.yml
  .github/workflows/numba_win-64_wheel_builder.yml
  .github/workflows/workflow_matrix.json
Labels: 5 - Ready to merge, skip_release_notes

#9862 Fix coverage support to respect include and omit and other options
  docs/upcoming_changes/9862.bug_fix.rst
  numba/misc/coverage_support.py
Labels: 5 - Ready to merge

#9876 Support floating point arguments for `np.random.negative_binomial`
  docs/upcoming_changes/9876.bug_fix.rst
  numba/cpython/randomimpl.py
  numba/tests/test_random.py
Labels: 5 - Ready to merge
