Repository numba/numba, pull requests merged in 2025-01, with the labels that each got.

#9887 Add env-var NUMBA_JIT_COVERAGE to disable coverage
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9887.change.rst
  numba/core/config.py
  numba/misc/coverage_support.py
  numba/tests/test_misc_coverage_support.py
Labels: 5 - Ready to merge

#9831 Lint `core/tracing.py` using `flake8`
  .flake8
  numba/core/tracing.py
Labels: 5 - Ready to merge, skip_release_notes

#9828 Add new type-checking level
  mypy.ini
Labels: 5 - Ready to merge, skip_release_notes

#9789 Upgrade GitHub Actions stale
  .github/workflows/stale.yml
Labels: 5 - Ready to merge, skip_release_notes

#9893 [DUX] fix use of rstcheck in towncrier check script
  docs/upcoming_changes/9893.bug_fix.rst
  maint/towncrier_rst_validator.py
Labels: 5 - Ready to merge

#9892 [UX] TypedDict: better error message for KeyError
  docs/upcoming_changes/9892.improvement.rst
  numba/tests/test_dictobject.py
  numba/typed/dictobject.py
Labels: 5 - Ready to merge

#9861 Fall back on inspect.getsourcelines() in first line finder
  docs/upcoming_changes/9861.improvement.rst
  numba/misc/firstlinefinder.py
  numba/tests/test_firstlinefinder.py
Labels: 5 - Ready to merge

#9847 Update checklist post 0.61.0rc1
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, skip_release_notes

#9904 Update release checklist post 0.61.0
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 5 - Ready to merge, skip_release_notes

#9832 Lint `core/withcontexts.py` using `flake8`
  .flake8
  numba/core/withcontexts.py
Labels: BuildFarm Passed, 5 - Ready to merge, skip_release_notes

#9905 Cherry-pick change-log and version support table modifications to main
  docs/source/release/0.61.0-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9837.bug_fix.rst
  docs/upcoming_changes/9848.bug_fix.rst
  docs/upcoming_changes/9887.change.rst
Labels: 4 - Waiting on reviewer, skip_release_notes
