Repository numba/numba, pull requests merged in 2025-05, with the labels that each got.

#10063 gha/add numba linux-64 wheel builder
  .github/workflows/numba_linux-64_wheel_builder.yml
  .github/workflows/workflow_matrix.json
  buildscripts/github/build_wheel_linux.sh
  buildscripts/github/repair_wheel_linux.sh
Labels: 5 - Ready to merge, skip_release_notes

#9676 Move Numba to LLVM's NewPassManager
  docs/source/reference/envvars.rst
  docs/upcoming_changes/9676.improvement.rst
  numba/core/codegen.py
  numba/core/config.py
  numba/core/llvm_bindings.py
  numba/misc/llvm_pass_timings.py
  numba/tests/test_llvm_pass_timings.py
  numba/tests/test_refop_pruning.py
Labels: BuildFarm Passed, 5 - Ready to merge

#9888 Prevent bools from if ops being interpreted as user variables
  docs/upcoming_changes/9888.bug_fix.rst
  numba/core/interpreter.py
  numba/tests/test_debuginfo.py
Labels: 5 - Ready to merge

#10043 Backport change-log and version support table modifications for `0.61.2` to `main`.
  docs/source/release/0.61.1-notes.rst
  docs/source/release/0.61.2-notes.rst
  docs/source/user/installing.rst
  docs/upcoming_changes/9919.highlight.rst
  docs/upcoming_changes/9945.bug_fix.rst
  docs/upcoming_changes/9972.bug_fix.rst
Labels: 5 - Ready to merge, skip_release_notes

#10047 Fix `IntEnumMember.can_convert_to()` when no conversions found
  docs/upcoming_changes/10047.bug_fix.rst
  numba/core/types/new_scalars/scalars.py
  numba/core/types/old_scalars.py
  numba/tests/test_types.py
Labels: 5 - Ready to merge

#10052 Fix bug in `np.searchsorted` when the arguments have `float32` dtype
  docs/upcoming_changes/10052.bug_fix.rst
  numba/np/new_arraymath.py
  numba/np/old_arraymath.py
  numba/tests/test_np_functions.py
Labels: 5 - Ready to merge

#10068 Document the inline and forceinline kwargs
  docs/source/developer/inlining.rst
  docs/source/reference/jit-compilation.rst
Labels: doc, 5 - Ready to merge, Effort - short, skip_release_notes

#10073 Fix C++ linkage for Python builds with Valgrind
  numba/_dispatcher.cpp
Labels: 5 - Ready to merge, skip_release_notes

#10023 gha/add numba osx-64 conda builder
  .github/workflows/numba_osx-64_conda_builder.yml
  buildscripts/condarecipe.local/conda_build_config.yaml
  buildscripts/github/MacOSX10.10.sdk.checksum
  buildscripts/github/setup_platform.sh
Labels: 5 - Ready to merge, skip_release_notes

#10079 Fix looplifting issue in for-zip, for-enumerate
  docs/upcoming_changes/10079.improvement.rst
  numba/core/untyped_passes.py
  numba/tests/test_looplifting.py
Labels: 5 - Ready to merge, Effort - short

#9401 Add type annotations for @intrinsic
  mypy.ini
  numba/_helperlib.pyi
  numba/core/extending.py
  numba/core/extending.pyi
Labels: 5 - Ready to merge, skip_release_notes

#10078 fix/revert gha numba recipe change
  .github/workflows/numba_osx-64_conda_builder.yml
  buildscripts/condarecipe.local/conda_build_config.yaml
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, skip_release_notes
