Repository numba/numba, pull requests merged in 2025-03, with the labels that each got.

#9943 Direct CUDA issues to the numba-cuda repo
  .github/ISSUE_TEMPLATE/config.yml
Labels: 5 - Ready to merge, skip_release_notes

#9916 More lazy strings.
  docs/upcoming_changes/9916.improvement.rst
  numba/core/byteflow.py
  numba/core/interpreter.py
  numba/core/transforms.py
  numba/core/utils.py
Labels: 5 - Ready to merge

#9961 Fix flake8 issue on main branch.
  numba/core/byteflow.py
Labels: 5 - Ready to merge, skip_release_notes

#9850 Handle empty traceback in get_loc method to prevent IndexError
  numba/core/types/functions.py
Labels: 5 - Ready to merge, skip_release_notes

#9964 remove upper pin on NumPy
  buildscripts/condarecipe.local/meta.yaml
Labels: 5 - Ready to merge, skip_release_notes

#9919 Support for NumPy 2.2
  .github/workflows/numba_win-64_builder.yml
  azure-pipelines.yml
  buildscripts/azure/azure-windows.yml
  docs/source/reference/pysupported.rst
  docs/upcoming_changes/9919.highlight.rst
  numba/cuda/tests/cudadrv/test_cuda_array_slicing.py
  numba/np/arrayobj.py
  numba/np/npdatetime.py
  numba/np/old_arraymath.py
  numba/tests/test_conditions_as_predicates.py
  numba/tests/test_hashing.py
  numba/tests/test_np_functions.py
  numba/tests/test_npdatetime.py
Labels: 5 - Ready to merge

#9945 Add type stub to numba.core.types to help static type checkers.
  docs/upcoming_changes/9945.bug_fix.rst
  numba/core/types/__init__.pyi
Labels: 5 - Ready to merge, Effort - short

#9972 Fix issue with error handling in slice assignment.
  docs/upcoming_changes/9972.bug_fix.rst
  numba/cuda/tests/cudapy/test_slicing.py
  numba/np/arrayobj.py
  numba/tests/test_indexing.py
Labels: CUDA, 5 - Ready to merge
