Repository numba/numba, pull requests merged in 2025-04, with the labels that each got.

#9390 Add .tobytes() method
  docs/source/reference/numpysupported.rst
  docs/upcoming_changes/9390.np_support.rst
  numba/cpython/randomimpl.py
  numba/np/arrayobj.py
  numba/tests/test_array_methods.py
Labels: 5 - Ready to merge, skip_release_notes

#9955 Use linkonce_odr linkage for `__excinfo_unwrap_args` global
  numba/core/callconv.py
  numba/pycc/compiler.py
  numba/tests/compile_with_pycc.py
  numba/tests/test_pycc.py
Labels: 5 - Ready to merge, Effort - short, skip_release_notes

#9973 Prevent unsafe type conversions use in `range`.
  docs/upcoming_changes/9973.bug_fix.rst
  numba/core/typing/old_builtins.py
  numba/tests/test_ir.py
  numba/tests/test_ir_inlining.py
  numba/tests/test_range.py
Labels: 5 - Ready to merge, Effort - short

#10028 update release notes 0.61.1
  docs/source/release/0.61.1-notes.rst
Labels: skip_release_notes

#10032 Updated dates in version support table and release notes
  docs/source/release/0.61.1-notes.rst
  docs/source/release/0.61.2-notes.rst
  docs/source/user/installing.rst
Labels: skip_release_notes

#10036 Bump azure ubuntu from 20.04 to 24.04
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
Labels: 5 - Ready to merge, skip_release_notes

#10035 Add support for PYCC for functions that has indirect dependency on Environment object
  docs/upcoming_changes/10035.improvement.rst
  numba/pycc/compiler.py
  numba/pycc/modulemixin.c
Labels: 5 - Ready to merge
